Repository volcano-sh/volcano, pull requests merged in 2019-07, with the labels that each got.

#270 Enable coverage stats for UT
  .travis.yml
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#269 Bump Volcano-sh/Scheduler
  Gopkg.lock
  pkg/controllers/job/job_controller_handler_test.go
  test/e2e/util.go
  vendor/github.com/kubernetes-sigs/kube-batch/cmd/kube-batch/app/options/options.go
  vendor/github.com/kubernetes-sigs/kube-batch/cmd/kube-batch/app/server.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/actions/allocate/allocate.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/actions/backfill/backfill.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/actions/preempt/preempt.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/actions/reclaim/reclaim.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/job_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/node_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/resource_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/types.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/unschedule_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/cache.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/cache/interface.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/framework/job_updater.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/framework/session.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/framework/session_plugins.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/plugins/gang/gang.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/plugins/nodeorder/nodeorder.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/plugins/predicates/predicates.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/plugins/proportion/proportion.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/plugins/util/util.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/util/assert/assert.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XXL

#271 UT Cases for Job Package
  pkg/controllers/job/job_controller_util_test.go
Labels: approved, lgtm, size/XL

#273 Additional UT in cli, queue,jo info pkg
  pkg/cli/job/delete_test.go
  pkg/cli/job/list_test.go
  pkg/cli/job/resume_test.go
  pkg/cli/job/run_test.go
  pkg/cli/job/suspend_test.go
  pkg/cli/job/view_test.go
  pkg/controllers/apis/job_info_test.go
  pkg/controllers/queue/queue_controller_test.go
Labels: approved, lgtm, size/L

#279 Try kind 0.4.0 for travis
  .travis.yml
  hack/e2e-kind-config.yaml
Labels: approved, lgtm, size/S

#276 Lowercase first letter in json response
  pkg/apis/batch/v1alpha1/job.go
Labels: approved, lgtm, size/XS

#277 Fix log issue when failed to update job
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#254 fix some bug about event and workqueue
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
  pkg/controllers/cache/cache.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/state/aborting.go
  pkg/controllers/job/state/inqueue.go
  pkg/controllers/job/state/pending.go
  pkg/controllers/job/state/running.go
  test/e2e/command.go
  test/e2e/job_controlled_resource.go
  test/e2e/job_error_handling.go
  test/e2e/job_scheduling.go
  test/e2e/mpi.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#283 Fix update issue
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#253 add more vkctl command and fix bugs
  cmd/cli/vkctl.go
  pkg/cli/job/delete.go
  pkg/cli/job/list.go
  pkg/cli/job/list_test.go
  pkg/cli/job/resume.go
  pkg/cli/job/run.go
  pkg/cli/job/run_test.go
  pkg/cli/job/suspend.go
  pkg/cli/job/util.go
  pkg/cli/job/util_test.go
  pkg/cli/job/view.go
  pkg/cli/job/view_test.go
Labels: approved, lgtm, size/XL

#281 Inherit kube-batch owners
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#287 add scripts for syncing scheduler code into tree
  hack/sync-scheduler-code.sh
Labels: approved, lgtm, size/L

#278 Propose TommyLike as reviewers and approvers of controller packages
  pkg/controllers/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#289 count unknown pod as [Unknown] in job status
  pkg/apis/batch/v1alpha1/job.go
  pkg/cli/job/list.go
  pkg/cli/job/view.go
  pkg/cli/job/view_test.go
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#291 migrate image to volcanosh
  docs/samples/kubecon-2019-china/gang/mpi-example.yaml
  docs/samples/kubecon-2019-china/horovod-sample/lm-horovod-tf-mnist-v0.5.yaml
  docs/samples/kubecon-2019-china/mpi-sample/mpi-example.yaml
  docs/samples/kubecon-2019-china/spark-sample/spark-pi.yaml
  docs/samples/kubecon-2019-china/tf-sample/tf-example.yaml
Labels: approved, lgtm, size/S

#292 Update readme document
  .gitignore
  README.md
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S

#296 Add kube-batch notes.
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#297 Update README.md
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#301 Add tiller log when process failed
  .travis.yml
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/XS

#302 move hzxuzhonghu to scheduler owners
  OWNERS
  pkg/scheduler/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#306 Fix the scheduler panic whenever the GPU is lost on node
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
Labels: approved, lgtm, size/M

#307 Some yaml fix and cleanups after kube-batch in tree
  cmd/deepcopy-gen/main.go
  cmd/kube-batch/app/server.go
  cmd/kube-batch/main.go
  docs/design/job-api.md
  example/integrations/mpi/mpi-example.yaml
  example/integrations/mxnet/train/train-mnist-cpu.yaml
  example/integrations/tensorflow/tf-example.yaml
  example/invalid_jobs/duplicatedPolicyEvent-webhook-deny.yaml
  example/invalid_jobs/duplicatedTaskName-webhook-deny.yaml
  example/invalid_jobs/minAvailable-webhook-deny.yaml
  example/job.yaml
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/L

#295 Updating submodule before testing
  .travis.yml
Labels: approved, lgtm, size/XS

#309 calc PGMinResources for Resources.Limits
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/job_controller_util_test.go
Labels: approved, lgtm, size/S

#285 Support multiple events in the lifecycle policy
  pkg/admission/admission_controller.go
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/L

#312 Update vk- to vc-
  Makefile
  README.md
  cmd/controllers/app/server.go
  installer/dockerfile/admission/Dockerfile
  installer/dockerfile/controllers/Dockerfile
  installer/dockerfile/kube-batch/Dockerfile
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/M

#316 Removing logs which does not belong to volcano job
  pkg/controllers/job/job_controller_handler.go
Labels: approved, lgtm, size/S

#319 Fix vk & vc issue
  Makefile
Labels: approved, lgtm, size/XS

#320 set drf dominant resource name
  pkg/scheduler/plugins/drf/drf.go
Labels: approved, lgtm, size/M

#322 change SchedulerName in cli from kube-batch to volcano
  pkg/cli/job/run.go
  pkg/cli/queue/common.go
Labels: approved, lgtm, size/XS

#313 Update kube-batch to scheduler
  Makefile
  README.md
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  hack/run-e2e-kind.sh
  installer/dockerfile/scheduler/Dockerfile
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#326 Fix issue in makefile
  Makefile
Labels: approved, lgtm, size/XS

#315 Adding e2e test case for multiple events in lifecycle policy
  test/e2e/job_error_handling.go
Labels: approved, lgtm, size/M

#190 sync job works concurrently
  cmd/controllers/app/options/options.go
  cmd/controllers/app/options/options_test.go
  cmd/controllers/app/server.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins_test.go
Labels: approved, lgtm, size/L

#336 vkctl job list --all-namespaces show ns
  pkg/cli/job/list.go
Labels: approved, lgtm, size/M

#337 fix ExitCode panic
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
Labels: approved, lgtm, size/S

#330 omit pods not controlled by volcano
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/M

#340 Change vkctl to vcctl
  .travis.yml
  Makefile
  cmd/cli/job.go
  cmd/cli/vkctl.go
  docs/design/queue.md
  docs/samples/kubecon-2019-china/scripts/watch.sh
  test/e2e/command.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#341 Fix default queue create issue
  installer/helm/chart/volcano/templates/default-queue.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
Labels: approved, lgtm, size/XS

#332 Register webhook in codes
  cmd/admission/app/configure/configure.go
  cmd/admission/main.go
  installer/helm/chart/volcano/templates/admission-config.yaml
  installer/helm/chart/volcano/templates/admission.yaml
Labels: approved, lgtm, size/L

#342 add slack invitation to project readme
  README.md
Labels: approved, kind/cleanup, kind/docs, lgtm, retest-not-required-docs-only, size/S

#343 E2E for vcctl help option
  test/e2e/cli_util.go
  test/e2e/vcctl.go
Labels: approved, lgtm, size/L

#344 Support release volcano in Travis
  .travis.yml
  Makefile
  hack/generate-yaml.sh
  hack/publish.sh
  installer/README.md
  installer/helm/chart/volcano/templates/NOTES.txt
  installer/namespace.yaml
Labels: approved, lgtm, size/L

#346 Update readme document
  README.md
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XL

#349 Added Volcano introduction.
  docs/samples/kubecon-2019-china/volcano-introduction.pdf
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#350 Add design
  docs/design/delay-pod-creation.md
  docs/design/drf.md
  docs/design/execution-flow.md
  docs/design/fairshare.md
  docs/design/images/drfjobordering.png
  docs/design/images/gangwithdrf.png
  docs/design/metrics.md
  docs/design/node-priority.md
  docs/design/plugin-conf.md
  docs/design/podgroup-status.md
  docs/design/preempt-action.md
  docs/design/reclaim-action.md
  docs/design/reclaim-design.md
  docs/design/task-order.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XL

#351 Added fossa check.
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#345 Add one click install script
  Makefile
  README.md
  hack/lib/install.sh
  hack/local-up-volcano.sh
  hack/run-e2e-kind.sh
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/L

#356 Read me slack links were not working so changed the same
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#362 Some cleanups after kube-batch intree
  Gopkg.lock
  Gopkg.toml
  docs/samples/kubecon-2019-china/scripts/node-info.go
  hack/generate-yaml.sh
  hack/lib/golang.sh
  hack/run-e2e-kind.sh
  installer/README.md
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
  pkg/scheduler/cache/event_handlers.go
  vendor/github.com/kubernetes-sigs/kube-batch/LICENSE
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/doc.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/labels.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/register.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/types.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/cluster_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/helpers.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/job_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/node_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/pod_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/queue_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/resource_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/test_utils.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/types.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/api/unschedule_info.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/scheduler/util/assert/assert.go
Labels: approved, lgtm, size/XXL

#366 E2E for Predicates
  test/e2e/predicates.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#363 E2E job life cycle
  test/e2e/job_lifecycle.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#372 Publish Docker Image in Daily Build
  .travis.yml
Labels: approved, lgtm, size/XS

#375 E2E additional scenario
  test/e2e/job_error_handling.go
  test/e2e/job_lifecycle.go
Labels: approved, lgtm, size/M

#352 Add development guide
  code_of_conduct.md
  community-membership.md
  contribute.md
  docs/development/development.md
  docs/development/perepare-for-development.md
  docs/getting-started/feature-lifecycle.md
  docs/getting-started/getting-started.md
  docs/getting-started/reporting_bugs.md
  docs/getting-started/support.md
  docs/troubleshooting/troubleshooting.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XL

#373 Add Verify Job to check consistency between generate yaml and the yam…
  .travis.yml
  Makefile
  hack/check-generated-yaml.sh
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M

#387 Add all valid policy actions
  pkg/admission/admission_controller.go
  pkg/admission/admit_job_test.go
  pkg/apis/batch/v1alpha1/job.go
Labels: approved, lgtm, size/S

#382 E2E admission
  test/e2e/admission.go
Labels: approved, lgtm, size/L

#379 added e2e test case with exist pvc in job
  test/e2e/job_controlled_resource.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#383 E2E Task Priority
  test/e2e/job_error_handling.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#364 migrate queue/podgroup to v1alpha2
  hack/publish.sh
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/templates/scheduling_v1alpha2_podgroup.yaml
  installer/helm/chart/volcano/templates/scheduling_v1alpha2_queue.yaml
  installer/volcano-development.yaml
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
  pkg/cli/queue/create.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/queue/queue_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_test.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/util/test_utils.go
  test/e2e/admission.go
  test/e2e/command.go
  test/e2e/job_controlled_resource.go
  test/e2e/job_lifecycle.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#392 Add Best practises badge
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#393 Add E2E to verify Event Generation for Volcano Job
  test/e2e/job_lifecycle.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#380 support binpack policy
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/volcano-development.yaml
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/factory.go
  test/e2e/job_scheduling.go
Labels: approved, lgtm, size/XL

#391 Fix race condition issue
  Makefile
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#395 Add E2E for check functionality of all Plugins
  test/e2e/job_plugins.go
Labels: approved, lgtm, size/M

#398 Make use of test.Run
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/job/job_controller_util_test.go
  pkg/controllers/job/job_state_test.go
Labels: approved, lgtm

#399 Add `Inqueue` status
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha2/types.go
  pkg/controllers/queue/queue_controller.go
  pkg/scheduler/api/queue_info.go
Labels: approved, lgtm, size/S

#331 E2E test scenarios for task policy
  test/e2e/job_error_handling.go
Labels: approved, lgtm, size/L
