Repository volcano-sh/volcano, pull requests merged in 2019-11, with the labels that each got.

#504 Dynamic loading comfigmap about action and plugins of scheduler, move loadSchedulerConf processing from run to runOnce
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M

#506 Add events for pod with pipelined state
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#501 Add queue state management design proposal
  docs/design/queue/queue-state-management.md
  docs/design/queue/queue.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#508 Add state parameter to queueSpec and queueStatus for queue
  installer/helm/chart/volcano/templates/scheduling_v1alpha2_queue.yaml
  installer/volcano-development.yaml
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1alpha1/conversion.go
  pkg/apis/scheduling/v1alpha1/zz_generated.conversion.go
  pkg/apis/scheduling/v1alpha2/types.go
  pkg/apis/scheduling/v1alpha2/zz_generated.conversion.go
Labels: approved, lgtm, size/M

#510 Rename imported package alias
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/admission/main.go
  cmd/cli/vcctl.go
  cmd/controllers/app/server.go
  example/huawei-connection/Volcano-intro.pptx
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/controllers/apis/job_info.go
  pkg/controllers/apis/job_info_test.go
  pkg/controllers/cache/interface.go
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/job/job_controller_resync.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/plugins/env/const.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/ssh/const.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/const.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_test.go
Labels: approved, lgtm, size/XL

#511 Umbrealla cleanups
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/admission/admission_controller.go
  pkg/apis/helpers/helpers.go
  pkg/cli/job/delete_test.go
  pkg/cli/job/list_test.go
  pkg/cli/job/resume_test.go
  pkg/cli/job/run.go
  pkg/cli/job/run_test.go
  pkg/cli/job/suspend.go
  pkg/cli/job/suspend_test.go
  pkg/cli/job/util.go
  pkg/cli/job/view_test.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/queue/queue_test.go
  pkg/controllers/apis/job_info_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/interface/interface.go
  pkg/controllers/job/state/aborted.go
  pkg/controllers/job/state/aborting.go
  pkg/controllers/job/state/completing.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/finished.go
  pkg/controllers/job/state/pending.go
  pkg/controllers/job/state/restarting.go
  pkg/controllers/job/state/running.go
  pkg/controllers/job/state/terminating.go
  pkg/controllers/job/state/util.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_test.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/test_utils.go
  test/e2e/job_error_handling.go
  test/e2e/job_lifecycle.go
  test/e2e/job_scheduling.go
  test/e2e/mpi.go
  test/e2e/tensorflow.go
Labels: approved, lgtm, size/XXL

#513 fix podgroup phase
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/XS

#507 fix filter NotReady node
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/S

#518 Added Gitter
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#517 Add filter function for command watching of job controller
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/S

#520 Modify scheduling events for pod and podgroup
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha2/types.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/L

#523 pdb bug 修复
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
Labels: approved, lgtm, size/S

#525 Fixed import order.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
Labels: approved, lgtm, size/XS

#527 Add svc hosts volumeMount for InitContainers
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/S

#535 Add the --publish-not-ready-addresses param for the svc plugin
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/S

#536 Add QTT as adopter
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#537 Add queueAction queueEvent queueRequest type
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1alpha2/types.go
Labels: approved, lgtm, size/M

#515 ssh plugin support specifying private/public keys path
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/ssh/ssh_test.go
Labels: approved, lgtm, size/L

#544 Simplify job pvc create process
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/job_controller_util_test.go
  test/e2e/job_controlled_resource.go
Labels: approved, lgtm, size/L

#547 Modify comments on OnPodCreate function of svc plugin
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/S

#560 Move myself to controller owner
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#552 Support networkpolicy
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/M

#542 modify the 'vcctl job run' function
  pkg/cli/job/run.go
  pkg/cli/job/run_test.go
  test/e2e/vcctl.go
Labels: approved, lgtm, size/S

#563 Update to klog.
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/admission/main.go
  cmd/cli/vcctl.go
  cmd/controllers/app/server.go
  cmd/controllers/main.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/admission/admit_pod.go
  pkg/admission/mutate_job.go
  pkg/admission/server.go
  pkg/apis/helpers/helpers.go
  pkg/controllers/cache/cache.go
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_resync.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/queue/queue_controller.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util/assert/assert.go
  pkg/scheduler/util/scheduler_helper.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
Labels: approved

#567 Update admission to use pflag.
  cmd/admission/app/options/options.go
  cmd/admission/main.go
  cmd/controllers/main.go
Labels: approved, lgtm, size/M

#572 fix validate victims check for preempt action
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/XS
