Repository volcano-sh/volcano, pull requests merged in 2019-08, with the labels that each got.

#401 add podgroup controller
  cmd/controllers/app/options/options.go
  cmd/controllers/app/options/options_test.go
  cmd/controllers/app/server.go
  pkg/apis/batch/v1alpha1/labels.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
  test/e2e/pg_controller.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#385 Fix error resync logic
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#405 clean some redundant job/pg/gc controllers code
  cmd/controllers/app/server.go
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/garbagecollector/garbagecollector_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_test.go
Labels: approved, lgtm, size/L

#406 remove shadowPodgroup in scheduler
  pkg/scheduler/api/pod_group_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/util.go
  test/e2e/predicates.go
Labels: approved, lgtm, size/L

#408 fix: Add comments about the defaulting of queue
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha2/types.go
Labels: approved, lgtm, size/XS

#370 add admitPod
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/admission/main.go
  hack/e2e-admission-config.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/volcano-development.yaml
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
  pkg/admission/admit_pod.go
  pkg/admission/admit_pod_test.go
  pkg/admission/mutate_job.go
  pkg/admission/mutate_job_test.go
  pkg/admission/server.go
  pkg/apis/helpers/helpers.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/podgroup/pg_controller_handler.go
  test/e2e/admission.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#414 Revert code coverage temporarily
  .travis.yml
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#418 Added "enqueue" to the actions in defaultSchedulerConf to fix a bug
  pkg/scheduler/util.go
Labels: approved, lgtm, size/XS

#419 Added enqueue action.
  pkg/scheduler/util.go
Labels: approved, lgtm, size/XS

#396 [cleanup] Only generate required scheduler configmap
  hack/generate-yaml.sh
  hack/run-e2e-kind.sh
  installer/README.md
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#420 Fixed typo in error message.
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#381 E2E for TensorFlow Integration
  example/integrations/tensorflow/benchmark/Dockerfile
  example/integrations/tensorflow/benchmark/tf-example.yaml
  example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml
  hack/run-e2e-kind.sh
  test/e2e/tensorflow.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#421 remove inqueue job phase
  docs/design/job-api.md
  pkg/apis/batch/v1alpha1/job.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/inqueue.go
  pkg/controllers/job/state/pending.go
  test/e2e/command.go
  test/e2e/job_error_handling.go
  test/e2e/job_lifecycle.go
  test/e2e/job_scheduling.go
  test/e2e/tensorflow.go
  test/e2e/util.go
Labels: approved, lgtm, size/XL

#422 Updated volcano logo
  docs/images/volcano-logo.png
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#358 support fair share
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/apis/scheduling/v1alpha1/zz_generated.conversion.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/namespace_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/util_test.go
  test/e2e/job_scheduling.go
  test/e2e/util.go
Labels: approved, lgtm, size/XXL

#429 Remove namespace for ClusterRole&ClusterRoleBinding
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S
