Repository volcano-sh/volcano, pull requests merged in 2019-12, with the labels that each got.

#576 Enable networkpolicy create/get permission
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#577 Enable CI verify
  Makefile
  pkg/apis/scheduling/v1alpha2/zz_generated.conversion.go
  pkg/apis/scheduling/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#578 Add explict info about what todo to update generated yaml
  hack/check-generated-yaml.sh
  hack/generate-yaml.sh
Labels: approved, lgtm, size/XS

#581 Change Statement unevict method to call UpdateTask
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/XS

#584 change node not found errors
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/XS

#586 dep ensure
  Gopkg.lock
Labels: approved, lgtm, size/XS

#512 Add queue controller about state
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/controllers/queue/queue_controller_test.go
  pkg/controllers/queue/queue_controller_util.go
  pkg/controllers/queue/state/closed.go
  pkg/controllers/queue/state/closing.go
  pkg/controllers/queue/state/factory.go
  pkg/controllers/queue/state/open.go
  pkg/controllers/queue/state/unknown.go
Labels: approved, lgtm, size/XXL

#585 use future idle resources when checking if task can fit node
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/L

#587 Add arguments for action
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/enqueue/enqueue_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/L

#592 Add Vivo as adopter
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#589 Upgrade helm to v3.0.1
  docs/design/queue/queue-state-management.md
  hack/lib/install.sh
  hack/run-e2e-kind.sh
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/helm/chart/volcano/templates/bus_v1alpha1_command.yaml
  installer/helm/chart/volcano/templates/default-queue.yaml
  installer/helm/chart/volcano/templates/scheduling_v1alpha1_podgroup.yaml
  installer/helm/chart/volcano/templates/scheduling_v1alpha1_queue.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M

#590 Support queue action by vcctl
  cmd/cli/queue.go
  pkg/apis/helpers/helpers.go
  pkg/cli/queue/create.go
  pkg/cli/queue/delete.go
  pkg/cli/queue/delete_test.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/queue/operate.go
  pkg/cli/queue/operate_test.go
  pkg/cli/queue/queue_test.go
  pkg/cli/queue/util.go
Labels: approved, lgtm, size/L

#591 disp job in default queue
  pkg/cli/job/run.go
Labels: approved, lgtm, size/XS

#588 Cleanup e2e framework to speed up e2e
  docs/development/development.md
  hack/run-e2e-kind.sh
  test/e2e/admission.go
  test/e2e/cli_util.go
  test/e2e/command.go
  test/e2e/job_controlled_resource.go
  test/e2e/job_error_handling.go
  test/e2e/job_lifecycle.go
  test/e2e/job_plugins.go
  test/e2e/job_scheduling.go
  test/e2e/mpi.go
  test/e2e/pg_controller.go
  test/e2e/predicates.go
  test/e2e/queue.go
  test/e2e/tensorflow.go
  test/e2e/util.go
  test/e2e/vcctl.go
Labels: approved, lgtm, size/L

#570 added priority based preemption to priority plugin
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/priority/priority.go
  test/e2e/job_error_handling.go
  test/e2e/job_scheduling.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#597 when delete pod, a new shadowgroup will be created
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/XS

#599 Change lessequal function in Reclaimable function
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/L

#600 Remove kar, kube-batch.
  cmd/controllers/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
Labels: approved, lgtm, size/S

#601 Added localup script.
  hack/local-up-cluster.sh
Labels: approved, lgtm, size/L

#603 change storage of ssh pem from configmap to secret for ssh plugin
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
  pkg/apis/helpers/helpers.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/job/plugins/ssh/ssh.go
  test/e2e/job_plugins.go
Labels: approved, lgtm, size/L

#575 Admission Refactor.
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/admission/app/util.go
  cmd/admission/main.go
  hack/.golint_failures
  pkg/admission/jobs/mutate/mutate_job.go
  pkg/admission/jobs/mutate/mutate_job_test.go
  pkg/admission/jobs/validate/admit_job.go
  pkg/admission/jobs/validate/admit_job_test.go
  pkg/admission/jobs/validate/util.go
  pkg/admission/pods/admit_pod.go
  pkg/admission/pods/admit_pod_test.go
  pkg/admission/router/factory.go
  pkg/admission/router/interface.go
  pkg/admission/router/server.go
  pkg/admission/schema/schema.go
  pkg/admission/util/util.go
  test/e2e/admission.go
Labels: approved, lgtm, size/XXL

#606 Update webhook path.
  pkg/admission/jobs/mutate/mutate_job.go
  pkg/admission/jobs/validate/admit_job.go
  pkg/admission/pods/admit_pod.go
Labels: approved, lgtm, size/XS

#607 Fixed localup cluster script.
  hack/local-up-cluster.sh
Labels: approved, lgtm, size/S

#608 Enahcement cli.
  pkg/cli/job/list.go
Labels: approved, lgtm, size/XS

#609 Fixed build error of release-pkg.
  .travis.yml
  Makefile
  Makefile.def
  defs/Makefile.dev.def
  defs/Makefile.release.def
  hack/build-env.sh
Labels: approved, lgtm, size/M

#613 Added VC_TASK_INDEX and added env to initContainers.
  pkg/controllers/job/plugins/env/const.go
  pkg/controllers/job/plugins/env/env.go
Labels: approved, lgtm, size/S

#614 Update factory.go
  pkg/controllers/job/plugins/factory.go
Labels: approved, lgtm, size/XS

#610 Added hosts into environment.
  pkg/controllers/job/plugins/svc/const.go
  pkg/controllers/job/plugins/svc/svc.go
  test/e2e/job_plugins.go
Labels: approved, lgtm, size/M

#622 vcctl command line enhancement
  docs/design/command-line-enhancement.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#541 Pipeline task if task's request resource less than the releasing resource of node during performing allocate action
  pkg/scheduler/actions/allocate/allocate.go
  test/e2e/job_scheduling.go
Labels: approved, lgtm, size/XS

#625 Update job_controller_util.go
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#626 Added Xiaohongshu as one of adopters
  docs/community/adopters.md
Labels: approved, retest-not-required-docs-only, size/XS

#627 remove repeated code.
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#605 Rename binaries.
  Makefile
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  cmd/webhook-manager/main.go
  docs/development/development.md
  hack/lib/install.sh
  hack/local-up-cluster.sh
  hack/publish.sh
  installer/README.md
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile.base
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/controllers/job/job_controller.go
  pkg/controllers/queue/queue_controller.go
Labels: approved, lgtm, size/M

#632 remove redundant type conversion
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#631 Push job back to queue if task is assigned in reclaim action
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, lgtm, size/XS

#636 Modify error check of return error
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/XS

#630 Added Roadmap
  docs/community/roadmap.md
Labels: approved, retest-not-required-docs-only, size/M

#637 Update version to 0.3
  Makefile
Labels: approved, lgtm, size/XS

#638 Remove duplicated check in jobEnqueueableFn of proportion
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#640 modify error check of return error
  pkg/scheduler/framework/statement.go
Labels: approved, cherry-pick-approved, lgtm, size/XS

#643 Added Volcano Intro.
  docs/volcano-introduction.pptx
Labels: approved

#642 Added cherry_pick_pull.sh
  hack/cherry_pick_pull.sh
Labels: approved, lgtm, size/L

#644 Refactor webhook org.
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  cmd/webhook-manager/main.go
  hack/.golint_failures
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/mutate/mutate_job_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/admission/jobs/validate/util.go
  pkg/webhooks/admission/pods/admit_pod.go
  pkg/webhooks/admission/pods/admit_pod_test.go
  pkg/webhooks/router/factory.go
  pkg/webhooks/router/interface.go
  pkg/webhooks/router/server.go
  pkg/webhooks/schema/schema.go
  pkg/webhooks/util/util.go
Labels: approved, lgtm, size/M

#633 fix the the Getting started link in contribute.md
  contribute.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#652 Use relative path for doc.
  contribute.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#654 Remove pdb support
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/L

#653 Gen install yaml without v1alpha queue and poggroup
  hack/generate-yaml.sh
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M

#647 Considering best-effort pods when calculating ready task number
  pkg/scheduler/api/job_info.go
  test/e2e/job_scheduling.go
Labels: approved, lgtm, size/M
