Repository volcano-sh/volcano, pull requests merged in 2019-09, with the labels that each got.

#431 Moved KubeCon 2019 China demo to example.
  example/kubecon-2019-china/drf/nginx-1.yaml
  example/kubecon-2019-china/drf/nginx-2.yaml
  example/kubecon-2019-china/drf/nginx.yaml
  example/kubecon-2019-china/gang/mpi-example.yaml
  example/kubecon-2019-china/gang/nginx.yaml
  example/kubecon-2019-china/horovod-sample/lm-horovod-tf-mnist-v0.5.yaml
  example/kubecon-2019-china/mpi-sample/mpi-example.yaml
  example/kubecon-2019-china/node-selector/nginx.yaml
  example/kubecon-2019-china/scripts/node-info.go
  example/kubecon-2019-china/scripts/watch.sh
  example/kubecon-2019-china/spark-sample/remove-all.sh
  example/kubecon-2019-china/spark-sample/spark-pi.yaml
  example/kubecon-2019-china/task-priority/elastic-job.yaml
  example/kubecon-2019-china/task-priority/high-priority.yaml
  example/kubecon-2019-china/task-priority/nginx.yaml
  example/kubecon-2019-china/task-priority/normal-priority.yaml
  example/kubecon-2019-china/tf-sample/tf-example.yaml
  example/kubecon-2019-china/volcano-introduction.pdf
Labels: approved, lgtm, size/XS

#434 Add demo about Click-Through-Rate distributed training with PaddlePad…
  example/integrations/paddlepaddle/README.md
  example/integrations/paddlepaddle/ctr-paddlepaddle-on-volcano.yaml
Labels: approved, lgtm, size/L

#433 Fix CRD Definition
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/helm/chart/volcano/templates/bus_v1alpha1_command.yaml
  installer/helm/chart/volcano/templates/scheduling_v1alpha1_podgroup.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#411 Skip verify volcano job container's Privileged mode
  pkg/admission/admit_job.go
  pkg/admission/admit_job_test.go
Labels: approved, lgtm, size/M

#412 Add maxRetry in job controller to prevent endless loop
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/S

#437 Change image repository of mxnet demo from private to volcanosh
  example/integrations/mxnet/train/train-mnist-cpu.yaml
Labels: approved, lgtm, size/XS

#439 set the json name of exitCode
  pkg/apis/batch/v1alpha1/job.go
Labels: approved, lgtm, size/XS

#442 Added adopters of Volcano.
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#440 simplify README
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#443 Add Baidu as adopter of Volcano.
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#444 bump golang version to 1.13.x and kind to v0.5.0 in ci
  .travis.yml
  hack/lib/golang.sh
Labels: approved, lgtm, size/XS

#446 Register healthz interface for controller and scheduler
  Gopkg.lock
  cmd/controllers/app/options/options.go
  cmd/controllers/app/options/options_test.go
  cmd/controllers/app/server.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  pkg/apis/helpers/helpers.go
  vendor/k8s.io/apiserver/pkg/server/healthz/doc.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/server/mux/OWNERS
  vendor/k8s.io/apiserver/pkg/server/mux/doc.go
  vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go
Labels: approved, lgtm, size/XL

#445 Queue refactor.
  pkg/controllers/queue/queue_controller.go
Labels: approved, lgtm, size/M

#451 Add Huawei-Cloud and GrandOmics
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#463 Add HC demo.
  example/huawei-connection/Volcano：基于云原生的高密计算解决方案.pptx
Labels: approved, lgtm, size/XS

#460 modify the return value of 'vcctl'
  cmd/cli/vkctl.go
  pkg/cli/job/run.go
  pkg/cli/job/view.go
Labels: approved, lgtm, size/S

#468 Added talks & integration into readme.
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S
