Repository volcano-sh/volcano, pull requests merged in 2019-10, with the labels that each got.

#471 Rename file name of volcano intro in HC.
  example/huawei-connection/Volcano-intro.pptx
Labels: approved, lgtm

#482 fix proportion OverusedFn
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#484 fix Resource Less/LessEqual
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/M

#478 check while ~/.kube/config is missing
  pkg/cli/job/common.go
  pkg/cli/job/util.go
Labels: approved, size/S

#485 Support KUBECON env.
  pkg/cli/job/common.go
  pkg/cli/job/util.go
Labels: approved, size/S

#486 fix vvctl e2e
  test/e2e/vcctl.go
Labels: size/S

#488 Admission: Fall back to v1alpha1 podgroup when v1alpha2 doesnot exist
  pkg/admission/admit_pod.go
Labels: approved, lgtm, size/S

#489 Added svg logo.
  docs/images/volcano-logo-svg.svg
Labels: approved, retest-not-required-docs-only

#490 Updated version to 0.2
  Makefile
Labels: approved

#493 Added execution flow img.
  docs/design/execution-flow.md
  docs/design/images/AllocateDesign.png
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#494 format function name
  pkg/admission/admission_controller.go
Labels: approved, lgtm, size/XS

#491 Control the number of feasible nodes to find and score in scheduling
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/L

#497 add priorityClassName to podgroup during creating of podgroup from pod
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/XS

#500 Request to be a reviewer
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, retest-not-required-docs-only, size/XS

#498 refresh volumes logic
  pkg/admission/admission_controller.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_util.go
  test/e2e/job_controlled_resource.go
Labels: approved, lgtm, size/L

#499 correct podgroup creating bug for single pod without ownerreference
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
Labels: approved, lgtm, size/L

#502 Fix deprecated dind in favor of kind in develop doc
  docs/development/prepare-for-development.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS
