Repository volcano-sh/volcano, pull requests merged in 2020-07, with the labels that each got.

#892 add e2e cases for preempt
  hack/e2e-kind-config.yaml
  test/e2e/job_scheduling.go
  test/e2e/preempt.go
  test/e2e/queue.go
  test/e2e/reclaim.go
Labels: approved, lgtm, size/L

#894 Trim white space using golang template
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#895 optimize code style according to reivew adivce in PR892
  test/e2e/preempt.go
Labels: approved, lgtm, size/M

#897 add preemption case when request resource cannot be satisfied by the …
  test/e2e/preempt.go
Labels: approved, lgtm, size/M

#898 Add placeholder support for e2e and some reclaim cases
  test/e2e/reclaim.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#903 fix issue 890
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#901 fix issue 890
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#899 add preemption case when mutli-preeptor-job with different priority c…
  test/e2e/preempt.go
Labels: approved, lgtm, size/M

#905 add drf e2e cases
  test/e2e/drf.go
  test/e2e/preempt.go
  test/e2e/reclaim.go
Labels: approved, lgtm, size/M

#852 Add gpu sharing in predicate logic.
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/well_known_labels.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/predicates/gpu.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L

#912 skip flake case
  test/e2e/preempt.go
Labels: approved, lgtm, size/XS

#906 e2e: add reclaim cases and fix placeholder nits
  test/e2e/reclaim.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#900 add some allocate cases
  test/e2e/allocate.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#914 e2e: fix placeholder problem by moving it
  test/e2e/util.go
Labels: approved, lgtm, size/XS

#902 Add gpu sharing user guide
  docs/images/gpu-share-flow.png
  docs/user-guide/how_to_use_gpu_sharing.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#907 Add release note for release 1.0
  CHANGELOG_1.0.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#913 e2e: additional cases to reclaim
  test/e2e/reclaim.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#919 UpdateJob when Job annotations or labels changed
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
Labels: approved, lgtm, size/M

#927 fix metrics defer issue
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#926 Split e2e to prevent travis timeout
  .travis.yml
  Makefile
  docs/development/development.md
  hack/.golint_failures
  hack/run-e2e-kind.sh
  test/e2e/job/admission.go
  test/e2e/job/cli_util.go
  test/e2e/job/command.go
  test/e2e/job/e2e_test.go
  test/e2e/job/job_controlled_resource.go
  test/e2e/job/job_error_handling.go
  test/e2e/job/job_lifecycle.go
  test/e2e/job/job_plugins.go
  test/e2e/job/job_scale_up_down.go
  test/e2e/job/main_test.go
  test/e2e/job/mpi.go
  test/e2e/job/pg_controller.go
  test/e2e/job/queue.go
  test/e2e/job/tensorflow.go
  test/e2e/job/util.go
  test/e2e/job/vcctl.go
  test/e2e/scheduling/allocate.go
  test/e2e/scheduling/drf.go
  test/e2e/scheduling/e2e_test.go
  test/e2e/scheduling/job_scheduling.go
  test/e2e/scheduling/main_test.go
  test/e2e/scheduling/predicates.go
  test/e2e/scheduling/preempt.go
  test/e2e/scheduling/reclaim.go
  test/e2e/scheduling/util.go
Labels: approved, lgtm, size/XXL

#931 Release 0.4.1
  CHANGELOG.md
  Makefile.def
Labels: approved, lgtm

#932 Update tag
  Makefile.def
Labels: approved, lgtm, size/XS

#929 modify task_scheduling_latency from microseconds to milliseconds
  pkg/scheduler/metrics/metrics.go
Labels: approved, lgtm, size/XS

#930 Add 0.4.1 changelog
  CHANGELOG.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#918 Fix wrong key name in secret volume
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/XS

#934 Short cicuit job deletion to prevent deepcopy
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#935 Add default trueValue for plugin config: EnabledBestNode.
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/S

#923 fix issue 864
  pkg/scheduler/framework/framework.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
Labels: approved, lgtm, size/L

#937 generate crds using kubebuilder
  Makefile
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/bases/bus.volcano.sh_commands.yaml
  config/crd/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  pkg/apis/batch/v1alpha1/doc.go
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/bus/v1alpha1/commands.go
  pkg/apis/bus/v1alpha1/doc.go
  pkg/apis/scheduling/v1beta1/doc.go
  pkg/apis/scheduling/v1beta1/types.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/batch_client.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/fake/fake_job.go
  pkg/client/clientset/versioned/typed/bus/v1alpha1/bus_client.go
  pkg/client/clientset/versioned/typed/bus/v1alpha1/fake/fake_command.go
  pkg/client/clientset/versioned/typed/scheduling/v1beta1/fake/fake_podgroup.go
  pkg/client/clientset/versioned/typed/scheduling/v1beta1/fake/fake_queue.go
  pkg/client/clientset/versioned/typed/scheduling/v1beta1/scheduling_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/webhooks/admission/pods/admit_pod_test.go
Labels: approved, lgtm, size/XXL

#944 Fix: set pod's scheduler name to job's if not set
  pkg/controllers/job/job_controller_util.go
  test/e2e/job/util.go
  test/e2e/scheduling/util.go
Labels: approved, lgtm, size/S

#942 fix ssh plugin
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/XS

#951 Fix podgroup status and event
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#952 Add default trueValue for plugin config: EnabledBestNode for all plugins
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/S

#953 Fix: set pod's scheduler name to job's if not set
  pkg/controllers/job/job_controller_util.go
  test/e2e/util.go
Labels: approved, lgtm, size/XS

#945 Support job scale down to zero
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/state/running.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  test/e2e/job/job_scale_up_down.go
Labels: approved, lgtm, size/L

#958 [Cherry-pick] Fix podgroup status and event when scale up and down
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#957 [Cherry-pick] fix ssh plugin
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/XS

#964 Fix volcano job patch
  test/e2e/job/util.go
  test/e2e/scheduling/util.go
Labels: approved, lgtm, size/S

#959 fix bug: capability validation failed when some running jobs finished or deleted
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#967 Revert "[Cherry-pick] fix ssh plugin"
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/XS

#966 Record Inqueue job resource request in queueAttr
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#971 Automated cherry pick of #959: fix bug of queue capability lose efficacy #966: Record Inqueue job resource request in queueAttr
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#961 remove unused kind-up-cluster
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S

#956 [Cherry-pick] Support job scale down to zero
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/state/running.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  test/e2e/job_scale_up_down.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#960 [Cherry-pick] Support job scale down to zero
  pkg/controllers/job/state/running.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  test/e2e/job_scale_up_down.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#972 v1.0.1: Add change log and update version
  CHANGELOG_1.0.md
  Makefile.def
Labels: approved, lgtm, size/S

#973 Add change log for 1.0.1
  CHANGELOG_1.0.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#970 update queue yaml name
  hack/local-up-volcano.sh
Labels: approved, lgtm, size/XS

#974 Automated cherry pick of #959: fix bug of queue capability lose efficacy #966: Record Inqueue job resource request in queueAttr
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#977 Skip check for doc change
  .travis.yml
Labels: approved, lgtm, size/XS

#980 FOSSA scanning Action added
  .github/workflows/fossa.yml
Labels: approved, lgtm, size/S
