Repository volcano-sh/volcano, pull requests merged in 2020-09, with the labels that each got.

#1023 fix duplicate preemptee in victims
  pkg/scheduler/plugins/drf/drf.go
Labels: approved, lgtm, size/XS

#1030 update the approver
  OWNERS
  pkg/scheduler/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1022 [cherry-pick][release-1.0] fix panic when volcano job use pvc
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1050 request approver for scheduler
  pkg/scheduler/OWNERS
Labels: approved, lgtm

#1045 fix typo in execution-flow.md
  docs/design/execution-flow.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1042 Fix Queue capability overuse when specify minAvailable less than task replicas
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1057 Fix spell issue
  docs/design/hdrf.md
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/S

#1060 better log level to improve scheduler performance
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XS

#1069 Modify minMemory definition to 1 byte.
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/S

#1072 Modify minMemory definition to 1 byte.
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/S

#1011 add big job resource reservation design doc
  docs/design/images/ReservationDesign.png
  docs/design/images/ReservationWorkflow.png
  docs/design/images/reservationDesign.png
  docs/design/images/reservationWorkflow.png
  docs/design/resource-reservation-design.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M
