Repository volcano-sh/volcano, pull requests merged in 2020-05, with the labels that each got.

#785 Add callback func bestNodeFn for plugins to attach nodeScores.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
Labels: approved, lgtm, size/M

#790 Add bestNodeFn for plugins to select best node of its own.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
Labels: approved, lgtm, size/M

#787 Implement job scale up and down
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/volcano-development.yaml
  pkg/apis/bus/v1alpha1/events.go
  pkg/apis/helpers/helpers.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/interface/interface.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/util.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  test/e2e/job_scale_up_down.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#793 Automated cherry pick of #784: Add validate job update
  pkg/controllers/job/job_controller_actions.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/util/util.go
  test/e2e/job_controlled_resource.go
Labels: approved, lgtm, size/L

#794 Automated cherry pick of #786: Fix Job crd definition to support job patch
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/volcano-development.yaml
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#782 Proposal: Volcano job support scale up and down
  docs/design/images/Job-scale-up-down.PNG
  docs/design/job-scale-up-down.md
Labels: approved, area/controllers, kind/documentation, lgtm, size/L

#795 Automated cherry pick of #789: Fix phase transition time set
  pkg/controllers/job/state/aborting.go
  pkg/controllers/job/state/pending.go
Labels: approved, lgtm, size/XS

#796 Automated cherry pick of #782: Support scale up and down
  docs/design/images/Job-scale-up-down.PNG
  docs/design/job-scale-up-down.md
Labels: size/L

#797 Automated cherry pick of #788: minAvailable must be greater than 0
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, size/S

#798 Automated cherry pick of #787: Implement Job scale up down
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/volcano-development.yaml
  log
  pkg/apis/bus/v1alpha1/events.go
  pkg/apis/helpers/helpers.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/interface/interface.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/util.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  test/e2e/job_scale_up_down.go
  test/e2e/util.go
Labels: approved, lgtm, size/XXL

#800 MinResource should be updated when minAvailable changes
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#801 Automated cherry pick of #800: MinResource should be updated when minAvailable changes
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#799 add golangci-lint to project
  .golangci.yml
  Makefile
Labels: approved, do-not-merge/invalid-commit-message, lgtm, size/M

#807 Added community meeting
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#808 Fix crd validation
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#811 Fix typo in version.go
  pkg/version/version.go
Labels: approved, lgtm, size/XS

#802 Upgrade: test volcano on k8s 1.16
  .travis.yml
  hack/e2e-kind-config.yaml
  hack/lib/install.sh
  installer/dockerfile/webhook-manager/Dockerfile.base
  test/e2e/util.go
Labels: approved, lgtm, size/S

#806 UpdateJob when Job annotations or labels changed
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
Labels: approved, lgtm, size/M

#812 cleanup spell issue
  CHANGELOG.md
  contribute.md
  docs/design/command-line-enhancement.md
  docs/troubleshooting/troubleshooting.md
  pkg/controllers/cache/cache_test.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/webhooks/admission/jobs/validate/util.go
Labels: approved, lgtm, size/S

#813 cleanup white noise
  cmd/cli/job.go
  community-membership.md
  contribute.md
  docs/design/command-line-enhancement.md
  docs/design/dedicated-volume.md
  docs/design/delay-pod-creation.md
  docs/design/drf.md
  docs/design/execution-flow.md
  docs/design/fairshare.md
  docs/design/images/Job-scale-up-down.PNG
  docs/design/job-api.md
  docs/design/job-scale-up-down.md
  docs/design/metrics.md
  docs/design/node-priority.md
  docs/design/podgroup-status.md
  docs/design/preempt-action.md
  docs/design/queue/queue-state-management.md
  docs/design/queue/queue.md
  docs/design/reclaim-action.md
  docs/design/reclaim-design.md
  docs/development/prepare-for-development.md
  docs/getting-started/getting-started.md
  docs/getting-started/support.md
  docs/volcano-introduction.pptx
  example/huawei-connection/Volcano-intro.pptx
  example/integrations/paddlepaddle/README.md
  example/kubecon-2019-china/tf-sample/tf-example.yaml
  hack/check-generated-yaml.sh
  hack/local-up-cluster.sh
  installer/README.md
  installer/volcano-development.yaml
  test/e2e/vcctl.go
Labels: approved, lgtm, size/L

#815 Add open source promotion plan - summer 2020
  docs/community/summer2020-cn.md
  docs/community/summer2020.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#821 Lint: fix all golint issue
  .golangci.yml
  hack/.golint_failures
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
  pkg/webhooks/admission/queues/mutate/mutate_queue_test.go
  test/e2e/admission.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#820 Lint: fix all govet issue
  pkg/controllers/queue/state/closed.go
  pkg/controllers/queue/state/closing.go
  pkg/controllers/queue/state/open.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/S

#823 fix the job validation to allow using fractional GPU
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/util.go
Labels: approved, lgtm, size/S

#826 Update summer2020 register way
  docs/community/summer2020-cn.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#814 Ignore pod with empty resource request when preempt
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/S

#829 Lint: fix ineffassign issue
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/router/server.go
  test/e2e/command.go
  test/e2e/job_scheduling.go
  test/e2e/util.go
Labels: approved, lgtm, size/S

#825 Lint: fix deadcode issue
  .golangci.yml
  pkg/apis/scheduling/register.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  test/e2e/util.go
Labels: approved, lgtm, size/M

#831 Add support for most requested priority
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/M

#824 Lint: fix gosimple issue
  pkg/apis/helpers/helpers.go
  pkg/cli/job/view_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/controllers/queue/state/closed.go
  pkg/controllers/queue/state/closing.go
  pkg/controllers/queue/state/open.go
  pkg/controllers/queue/state/unknown.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/util.go
  pkg/webhooks/admission/pods/admit_pod.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue.go
  test/e2e/job_controlled_resource.go
  test/e2e/job_plugins.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#827 Lint: fix dupl issue
  .golangci.yml
Labels: approved, lgtm, size/XS

#832 Allow specifying admission webhook port, by default 8443
  cmd/webhook-manager/app/options/options.go
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#835 Lint: fix stylecheck issue
  .golangci.yml
Labels: approved, lgtm, size/XS

#833 Lint: fix structcheck issue
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#839 Referesh volcano 1.0 roadmap
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#841 Lint:fix lints
  .golangci.yml
  cmd/cli/util/util.go
  cmd/cli/vcctl.go
  example/kubecon-2019-china/scripts/node-info.go
  pkg/cli/job/util.go
  pkg/cli/queue/create.go
  pkg/cli/util/util.go
  pkg/controllers/cache/cache_test.go
  pkg/controllers/job/job_controller_actions.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/util.go
  test/e2e/command.go
Labels: approved, lgtm, size/L
