Repository volcano-sh/volcano, pull requests merged in 2020-08, with the labels that each got.

#978 Add change log for v0.4.2
  CHANGELOG.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#981 Automated cherry pick of #978: Add change log for v0.4.2
  CHANGELOG.md
Labels: retest-not-required-docs-only, size/XS

#982 Update version to v0.4.2
  Makefile.def
Labels: size/XS

#984 Fix unallocate
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/XS

#987 CI：Speed up CI jobs with parallel
  .travis.yml
  Makefile
  hack/.golint_failures
  hack/run-e2e-kind.sh
  test/e2e/jobp/admission.go
  test/e2e/jobp/cli_util.go
  test/e2e/jobp/e2e_test.go
  test/e2e/jobp/job_controlled_resource.go
  test/e2e/jobp/job_lifecycle.go
  test/e2e/jobp/job_scale_up_down.go
  test/e2e/jobp/main_test.go
  test/e2e/jobp/mpi.go
  test/e2e/jobp/pg_controller.go
  test/e2e/jobp/util.go
  test/e2e/jobp/vcctl.go
  test/e2e/jobseq/cli_util.go
  test/e2e/jobseq/command.go
  test/e2e/jobseq/e2e_test.go
  test/e2e/jobseq/job_error_handling.go
  test/e2e/jobseq/job_plugins.go
  test/e2e/jobseq/main_test.go
  test/e2e/jobseq/queue.go
  test/e2e/jobseq/tensorflow.go
  test/e2e/jobseq/util.go
  test/e2e/schedulingaction/allocate.go
  test/e2e/schedulingaction/e2e_test.go
  test/e2e/schedulingaction/main_test.go
  test/e2e/schedulingaction/predicates.go
  test/e2e/schedulingaction/preempt.go
  test/e2e/schedulingaction/reclaim.go
  test/e2e/schedulingaction/util.go
  test/e2e/schedulingbase/drf.go
  test/e2e/schedulingbase/e2e_test.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/schedulingbase/main_test.go
  test/e2e/schedulingbase/util.go
Labels: approved, lgtm, size/XXL

#992 Scheduler: avoid pushing back empty jobs in allocate action
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/XS

#994 plugins/binpack: fix typo of BinpackMemory
  pkg/scheduler/plugins/binpack/binpack.go
Labels: approved, lgtm, size/XS

#989 Add comments to plugin interface
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/plugins/interface/interface.go
Labels: approved, lgtm, size/M

#995 get compilation environment and build corresponding binary automatically
  Makefile
Labels: approved, lgtm, size/S

#1000 add arm64 support
  Makefile
  README.md
  installer/dockerfile/controller-manager/Dockerfile.arm64
  installer/dockerfile/scheduler/Dockerfile.arm64
  installer/dockerfile/webhook-manager/Dockerfile.arm64
  installer/dockerfile/webhook-manager/Dockerfile.base.arm64
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XL

#996 Fix ssh authorize key and remove `no-root` flag
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/ssh/ssh_test.go
Labels: approved, lgtm, size/M

#1002 fix panic if minResource not set
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1006 Add stale bot
  .github/stale.yml
Labels: approved, lgtm, size/M

#1008 Automated cherry pick of #1002: fix panic if minResource not set
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1005 Remove controlled resource in `OnJobDelete`
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/M

#1010 Automated cherry pick of #1002: fix panic if minResource not set
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1013 Improve performance: remove priorityclass
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_resync.go
Labels: approved, lgtm, size/M

#1018 fix panic when volcano job use pvc
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1004 Add hdrf design doc
  docs/design/hdrf.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1016 Add file watcher for scheduler config file
  LICENSES/vendor/github.com/fsnotify/fsnotify/LICENSE
  go.mod
  pkg/filewatcher/filewatcher.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1020 rm unnecessary jobcache.JobKeyByReq
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/XS

#1024 [cherry-pick][release-0.4] fix panic when volcano job use pvc
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1026 update approver and reviewer
  pkg/scheduler/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1028 Add Zhonghu Xu as a top-level approver
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1027 update approver and reviewer
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS
