Repository volcano-sh/volcano, pull requests merged in 2020-06, with the labels that each got.

#845 adding mindspore example
  example/MindSpore-example/README.md
  example/MindSpore-example/mindspore_cpu/mindspore-cpu.yaml
  example/MindSpore-example/mindspore_gpu/gpu-test.py
  example/MindSpore-example/mindspore_gpu/mindspore-gpu.yaml
Labels: approved, lgtm, size/L

#846 issue840: lint fix
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  test/e2e/job_error_handling.go
Labels: approved, lgtm, size/M

#850 add pod admit e2e
  pkg/webhooks/admission/pods/admit_pod_test.go
  test/e2e/admission.go
Labels: approved, lgtm, size/M

#843 Skipped task if no candidate nodes.
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/XS

#848 add job e2e
  test/e2e/admission.go
Labels: approved, lgtm, size/XXL

#856 Increase timeout for e2e test
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/XS

#738 support basic batch job preempt
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/util/test_utils.go
  test/e2e/queue.go
Labels: approved, lgtm, size/L

#853 integration with argo
  example/integrations/argo/10-job-step.yaml
  example/integrations/argo/20-job-DAG.yaml
  example/integrations/argo/README.md
Labels: approved, lgtm, size/L

#861 integration with argo and optimize analyzing conditions of argo step
  example/integrations/argo/10-job-step.yaml
  example/integrations/argo/20-job-DAG.yaml
  example/integrations/argo/README.md
Labels: approved, lgtm, size/S

#860 Add kubeClient in scheduler framwork.Session
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M

#858 e2e: add test code for queue controller
  pkg/cli/util/util.go
  test/e2e/admission.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, lgtm, size/L

#870 fix e2e bug
  test/e2e/admission.go
Labels: approved, lgtm, size/XS

#874 Add CNCF banner in README
  README.md
  docs/images/cncf-logo.png
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#876 hack: add missing header
  hack/build-env.sh
  hack/local-up-cluster.sh
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/M

#872 add some e2e cases about queue
  test/e2e/admission.go
Labels: approved, lgtm, size/L

#862 Refactor statement
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/M

#878 Update wrong license
  LICENSES/LICENSE
  hack/update-vendor-licenses.sh
Labels: approved, lgtm, size/XS

#881 Added controller framework.
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  pkg/controllers/framework/factory.go
  pkg/controllers/framework/interface.go
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/garbagecollector/garbagecollector_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/job/job_controller_resync.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/controllers/queue/queue_controller_test.go
Labels: approved, lgtm, size/XL

#885 fix default Qeue e and webhook startup sequence
  pkg/scheduler/cache/cache.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
  pkg/webhooks/admission/queues/mutate/mutate_queue_test.go
Labels: approved, lgtm, size/M

#886 Upgrade go version to 1.14
  .travis.yml
  Makefile
  docs/development/prepare-for-development.md
  go.mod
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
  hack/update-vendor-licenses.sh
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/listers/batch/v1alpha1/job.go
  pkg/client/listers/bus/v1alpha1/command.go
  pkg/client/listers/scheduling/v1beta1/podgroup.go
  pkg/client/listers/scheduling/v1beta1/queue.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
