Repository volcano-sh/volcano, pull requests merged in 2020-12, with the labels that each got.

#1160 CI: switch to Github Action
  .github/workflows/main.yaml
  .github/workflows/release.ymal
  .travis.yml
Labels: approved, size/L

#1184 CI: fix indent issue
  .github/workflows/main.yaml
Labels: size/S

#1176 Fix queue cannot use idle resource issue
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#1179 generate v1 crds. remove subresource status in pg crd.
  Makefile
  README.md
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/bases/bus.volcano.sh_commands.yaml
  config/crd/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/bus.volcano.sh_commands.yaml
  config/crd/v1beta1/scheduling.volcano.sh_podgroups.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/bus/v1alpha1/commands.go
  pkg/apis/scheduling/v1beta1/types.go
Labels: approved, lgtm, size/XXL

#1189 update github action config
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  hack/lib/install.sh
Labels: approved

#1191 optimize local script
  hack/local-up-volcano.sh
Labels: approved, lgtm, size/XS

#1186 fix dose not delete network policy when job finished
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/S

#1170 feat: mutate default of job spec
  pkg/apis/batch/v1alpha1/job.go
  pkg/controllers/job/state/restarting.go
  pkg/controllers/job/state/util.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
Labels: approved, lgtm, size/M

#1200 [Feature] Add Queue & Namespace Support For Volcano Monitoring
  installer/helm/chart/volcano/templates/grafana.yaml
  pkg/apis/batch/v1alpha1/labels.go
  pkg/controllers/job/job_controller_util.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/metrics/metrics.go
Labels: approved, lgtm, size/S

#1199 typo and go format
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/M

#1201 fix: gox path err in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#1205 Fix: prepare-for-development dead link
  docs/development/prepare-for-development.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1167 Bug/fix scheduling duration update after complete
  hack/local-up-volcano.sh
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/XS

#1218 feat: support vc-scheduler loading custom plugins (#1215)
  .github/workflows/release.yaml
  Makefile
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  example/custom-plugin/README.md
  example/custom-plugin/go.mod
  example/custom-plugin/go.sum
  example/custom-plugin/magic.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/framework/plugins_test.go
Labels: approved, lgtm, size/XXL

#1222 add deployment example with volcano scheudling
  example/deployment.yaml
Labels: approved, lgtm, size/S

#1224 fix: Fix the wrong comments in the example
  example/deployment.yaml
Labels: approved, lgtm, size/XS

#1192 job event optimize
  pkg/apis/batch/v1alpha1/job.go
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#1209 fix allocate: high priority queue should not block others
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/M

#1208 fix(script): fix daily release err
  hack/generate-internal-groups.sh
Labels: approved, lgtm, size/S

#1194 fix proportion can not reclaim issue
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#1158 queue-resource design add
  docs/design/images/queue_reservation_allocate_workflow.png
  docs/design/images/queue_reservation_lock_workfow.png
  docs/design/queue-resource-reservation-design.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1138 fix: terminate job and release resources when drop job out of queue
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/XS

#1111 Some improvements of scheduler
  pkg/scheduler/api/node_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/XS

#1087 Add MaxRequeueNum as a controller-manager param
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/queue/queue_controller.go
Labels: approved, lgtm, size/M

#1228 release v1.1.1
  Makefile.def
Labels: approved, size/XS
