Repository volcano-sh/volcano, pull requests merged in 2020-11, with the labels that each got.

#1123 pkg/scheduler/util.go: fix a typo
  pkg/scheduler/util.go
Labels: approved, lgtm, size/XS

#1110 Check node cache before adding task into cache
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/S

#1127 Add podName and svcName length validate
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  test/e2e/jobseq/queue.go
  test/e2e/schedulingbase/job_scheduling.go
Labels: approved, lgtm, size/M

#1051 Added design from cpu careful regulation
  docs/design/cpu-careful-regulation.md
Labels: retest-not-required-docs-only, size/M

#1130 feature design for queue resource reservation
  docs/design/job-resource-reservation-design.md
  docs/design/queue-resource-reservation-design.md
Labels: approved, retest-not-required-docs-only, size/L

#1133 assign issue1094 to mikechengwei
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1151 Fix queue unknown state bug
  pkg/controllers/queue/state/closing.go
Labels: approved, lgtm, size/XS

#1132 Deployment: fix helm upgrade bugs on namespace hardcode
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/templates/prometheus.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M
