Repository volcano-sh/volcano, pull requests merged in 2021-04, with the labels that each got.

#1394 simplify unit-test
  Makefile
Labels: approved, lgtm, size/XS

#1389 add `zen-xu` to approvers
  pkg/scheduler/OWNERS
Labels: approved, do-not-merge/hold, retest-not-required-docs-only, size/XS

#1390 add shinytang6 to volcano approver
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
Labels: approved, do-not-merge/hold, retest-not-required-docs-only, size/XS

#1380 update CI timeout to five minutes
  test/e2e/jobseq/tensorflow.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/util/job.go
  test/e2e/util/podgroup.go
  test/e2e/util/queue.go
  test/e2e/util/replicaset.go
  test/e2e/util/util.go
Labels: approved, size/M

#1402 refactor(e2e): improve e2e scripts and comments for stability and readability
  hack/lib/install.sh
  hack/run-e2e-kind.sh
  test/e2e/jobp/job_lifecycle.go
  test/e2e/jobp/job_scale_up_down.go
  test/e2e/jobp/min_success.go
  test/e2e/jobp/pg_controller.go
  test/e2e/jobseq/job_error_handling.go
  test/e2e/jobseq/mpi.go
  test/e2e/util/job.go
  test/e2e/util/node.go
  test/e2e/util/podgroup.go
  test/e2e/util/queue.go
  test/e2e/util/replicaset.go
  test/e2e/util/util.go
Labels: approved, lgtm, size/L

#1404 allocate the feature of v1.3 to owners
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1409 fix CI
  test/e2e/schedulingaction/preempt.go
  test/e2e/vcctl/command.go
Labels: approved, lgtm, size/XS

#1360 fix wrong Pipeline in action allocate
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/XS

#1388 add `bindingTasks` to judge whether adding node to the snapshot.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/L

#1414 Fix typos in roadmap.md
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1412 fix: use task.Name to make podName in admission
  pkg/webhooks/admission/jobs/validate/admit_job.go
Labels: approved, lgtm, size/XS

#1423 add wpeng102 to reviewer
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1427 Optimize yaml unmarshal logic
  pkg/scheduler/util.go
Labels: approved, lgtm, size/XS

#1430 fix(scheduler): use nodeMap to fix anti-affinity problem
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/M

#1307 feat(scheduler): add most allocated algo to nodeorder
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/M

#1429 fix(controller): fix ssh missing when job update
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/S

#1434 Revert "fix(scheduler): use nodeMap to fix anti-affinity problem"
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, size/M

#1353 Add task-topology plugin for scheduling.
  docs/design/task-topology-plugin.md
  docs/user-guide/how_to_use_task_topology_plugin.md
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/task-topology/bucket.go
  pkg/scheduler/plugins/task-topology/manager.go
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/plugins/task-topology/topology_test.go
  pkg/scheduler/plugins/task-topology/util.go
Labels: approved, lgtm, size/XXL

#1443 scheduler need configmap role to enable elect funtion
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS
