Repository volcano-sh/volcano, pull requests merged in 2021-03, with the labels that each got.

#1334 fix(scheduler): remove `JobInfo.Pipelined` helper function
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/S

#1344 fix: prevent SelectBestNode func arise panic
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, lgtm, size/XS

#1352 [feat]support taintToleration preferNoschdule
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/L

#1354 support taint toleration preferNoScheduler in release-0.4
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/M

#1356 make timeout larger for CI
  test/e2e/jobp/util.go
  test/e2e/jobseq/util.go
  test/e2e/schedulingaction/util.go
  test/e2e/schedulingbase/util.go
Labels: approved, lgtm, size/L

#1343 fix(scheduler): move JobInfo helper functions to method
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/scheduling/v1beta1/labels.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#1365 fix sla jobOderFn when sla not set
  pkg/scheduler/plugins/sla/sla.go
Labels: approved, lgtm, size/XS

#1364 fix: it is possible to Occur OutOfCpu， when exist some pods including init container
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#1370 Update the roadmap
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1374 Support auto updating crd manifests in helm templates when run `make generate-yaml`
  Makefile
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/helm/chart/volcano/templates/bus_v1alpha1_command.yaml
  installer/helm/chart/volcano/templates/scheduling_v1beta1_podgroup.yaml
  installer/helm/chart/volcano/templates/scheduling_v1beta1_queue.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#1382 Update ca.crt and server.csr validity period to 10 years
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
Labels: approved, lgtm, size/XS

#1385 add additional printer columns to crd `Job`
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
  pkg/apis/batch/v1alpha1/job.go
Labels: approved, lgtm, size/L

#1386 Makefile add new target `update-development-yaml`
  Makefile
Labels: approved, lgtm, size/XS

#1375 feat(webhook): add podgroup admission
  cmd/webhook-manager/main.go
  pkg/apis/scheduling/v1beta1/types.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/pods/admit_pod.go
  pkg/webhooks/schema/schema.go
Labels: approved, size/L

#1384 Support minSuccess
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
  pkg/apis/batch/v1alpha1/job.go
  pkg/controllers/job/state/running.go
  test/e2e/jobp/min_success.go
  test/e2e/util/job.go
Labels: approved, lgtm, size/L
