Repository volcano-sh/volcano, pull requests merged in 2021-05, with the labels that each got.

#1161 feat: add task minAvailable design
  docs/design/task-minavailable.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1452 same job's diffenrent tasks should compare task's priority
  pkg/scheduler/plugins/priority/priority.go
Labels: approved, lgtm, size/S

#1453 Hotfix issue 1451: lose preemptor when considering Preemption between…
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/plugins/priority/priority.go
Labels: approved, lgtm, size/XS

#1403 doc: add multi schedulers design doc
  docs/design/images/multi-schedulers.png
  docs/design/multi-schedulers.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#1137 feat: support update priorityClassName
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
Labels: approved, lgtm, size/L

#1474 issue 1468: add queue annotation in deployment example and add queue.…
  example/deployment/deployment.yaml
  example/deployment/queue.yaml
Labels: approved, lgtm, size/S

#1480 update scheduler default QPS and Burst
  cmd/scheduler/app/options/options.go
Labels: approved, size/XS

#1477 vcctl queue support get kubeconfig from env
  pkg/cli/queue/common.go
Labels: approved, lgtm, size/S

#1478 don't return err message when the pod isn't in the nodeinfo cache
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/XS

#1481 doc: add schedulerName in gpu sharing user guide
  docs/user-guide/how_to_use_gpu_sharing.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1482 update go mod for volcano.sh/apis
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  go.mod
  go.sum
  hack/generate-yaml.sh
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-latest.yaml
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/job.go
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/labels.go
  vendor/volcano.sh/apis/pkg/apis/bus/v1alpha1/events.go
Labels: approved, lgtm, size/XXL

#1165 feat: add predicate with equivalence cache
  pkg/controllers/job/job_controller_util.go
  pkg/scheduler/plugins/predicates/cache.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L

#1483 fix the bug of CRD apiversion and installation volcano with kind
  Makefile
  hack/generate-yaml.sh
  hack/local-up-volcano.sh
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#1494 update vendor for resource reservation
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L
