Repository volcano-sh/volcano, pull requests merged in 2021-11, with the labels that each got.

#1806 Proposal: Add Machine Learning Framework Plugins in Volcano
  docs/design/distributed-framework-plugins.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#1732 fix(scheduler) gang plugin task min avaliable check
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#1820 add multiple tasks support
  docs/design/task-launch-order-within-job.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#1817 Remove default quota info in `NewNamespaceCollection`
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/namespace_info_test.go
Labels: approved, lgtm, size/M

#1823 clean up readAdmissionConf
  pkg/webhooks/config/config.go
Labels: approved, lgtm, size/S

#1829 clean addNumaInfo
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/S

#1828 cleanup AddPriorityClass
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, ok-to-test, size/S

#1831 cleanup scheduler cache informerFactory
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
Labels: approved, lgtm, ok-to-test, size/M

#1841 fix syntax error in function Remove GPUIndexPatch
  pkg/scheduler/api/pod_info.go
Labels: approved, lgtm, size/XS

#1843 Fix delete duplicate line.
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#1847 try to fixed scheduler crash fatal error: concurrent map writes
  pkg/scheduler/plugins/numaaware/numaaware.go
Labels: approved, lgtm, size/XS

#1719 Fix: All pods is existing when restart count exceed max retry
  pkg/controllers/job/job_controller_actions.go
  test/e2e/jobp/job_restart.go
  test/e2e/util/job.go
Labels: approved, lgtm, size/L

#1848 fix: avoid chan block within taintTolerationScore
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/XS

#1852 switch the order of patch and existence check
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/S

#1849 support to set healthz address and metrics address
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
Labels: approved, lgtm, size/S

#1857 ignore the update event if pod is allocated in cache but not present in NodeName
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/S

#1856 improve taintTolerationScore interPodAffinityScore throghput when failure occurs
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/S

#1851 fix pod cannot be allocated with sufficient resource
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/L
