Repository volcano-sh/volcano, pull requests merged in 2021-07, with the labels that each got.

#1595 Update tools version to fix CI and separate workflow to accelerate CI
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/main.yaml
  installer/helm/chart/volcano/templates/prometheus.yaml
  installer/volcano-monitoring-latest.yaml
  test/e2e/jobp/job_controlled_resource.go
  test/e2e/jobseq/job_plugins.go
  test/e2e/schedulingaction/predicates.go
Labels: approved, lgtm, size/L

#1569 Update Less function
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/L

#1573 add resource comparison doc
  docs/design/resource-comparison.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/M

#1611 add LessEqualInAllDimension function and remove LessEqual/LessEqualSt…
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/reservation/reservation.go
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/util/scheduler_helper.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/util/node.go
Labels: approved, lgtm, size/L

#1576 support multi-scheduler
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/main.go
  go.mod
  installer/helm/chart/volcano/config/volcano-admission.conf
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/pods/mutate/mutate_pod_test.go
  pkg/webhooks/admission/pods/mutate/namespace.go
  pkg/webhooks/config/config.go
  pkg/webhooks/router/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1565 add multi-scheduling design doc
  docs/design/images/multi-volcano-schedulers.png
  docs/design/images/pod-webhook-mutate.png
  docs/design/multi-scheduler.md
  docs/design/multi-volcano-schedulers.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#1615 Adds the missing field to the Webhook
  pkg/webhooks/admission/jobs/validate/util.go
Labels: approved, lgtm, size/XS

#1614 apply approver for wpeng102
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1582 improve: clean unready status when job ready
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/XS

#1618 fix: reset task.NodeName after call DeallocateFunc
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/S

#1622 update resource comparision doc
  docs/design/resource-comparison.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1448 fix job enqueue issue
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/overcommit/overcommit.go
Labels: approved, lgtm, size/M

#1574 Improve for issue 1572: func FeasibleNodesToFind to use list with a centain order
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, ok-to-test, size/L

#1613 add LessEqualPartly function
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/L

#1612 update LessPartly function
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/task-topology/topology.go
Labels: approved, lgtm, size/L

#1623 fix some typos
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/well_known_labels.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1578 Improve: reduce calculation of total nodes' resource in stead of storing it when snapshot
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1621 add Equal function
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/M

#1593 fix a problem about equivalence ecache feature
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/XS

#1583 doc: add resource quota plugin doc
  docs/design/resourcequota-plugin.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#1624 rename resource comparision functions
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/reservation/reservation.go
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/util/scheduler_helper.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/util/node.go
Labels: approved, lgtm, size/M

#1625 optimize CI configmap
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
Labels: approved, lgtm, size/XS

#1626 add task-spec in pod label
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#1139 feat: add maxRetry to taskSpec
  config/crd/bases/batch.volcano.sh_jobs.yaml
  hack/run-e2e-kind.sh
  pkg/controllers/cache/cache.go
  pkg/controllers/cache/interface.go
  pkg/controllers/job/job_controller_handler.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/mutate/mutate_job_test.go
  pkg/webhooks/admission/jobs/validate/util.go
  test/e2e/jobseq/job_error_handling.go
  test/e2e/util/job.go
  test/e2e/util/node.go
Labels: approved, lgtm, size/L

#1629 update roadmap
  docs/community/roadmap.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1628 fix bugs about resource comparison
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#1632 fix fossa
  .github/workflows/fossa.yml
Labels: approved, lgtm, size/XS

#1635 scheduler plugin framework support SharedInformerFactory()
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
Labels: approved, lgtm, size/S

#1639 format docs
  docs/design/tdm-plugin.md
  docs/user-guide/how_to_use_gpu_sharing.md
  docs/user-guide/how_to_use_numa_aware.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1636 delete bindingTasks from NodeInfo structure
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/M

#1645 enable configuring volcano webhooks
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/main.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  pkg/webhooks/router/admission.go
Labels: approved, lgtm, size/S

#1652 fix CI
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S

#1653 optimize function setOversubscription
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#1649 feat(core): upgrade controller tools to v0.6.0
  Makefile
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/bases/bus.volcano.sh_commands.yaml
  config/crd/bases/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/bus.volcano.sh_commands.yaml
  config/crd/v1beta1/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/v1beta1/scheduling.volcano.sh_podgroups.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/bases/nodeinfo.volcano.sh_numatopologies.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/v1beta1/nodeinfo.volcano.sh_numatopologies.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L
