Repository volcano-sh/volcano, pull requests merged in 2021-01, with the labels that each got.

#1230 Codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/M

#1233 feat: add shinytang6 as reviewer
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, retest-not-required-docs-only, size/XS

#1234 feat: add merryzhou as reviewer
  OWNERS
  pkg/scheduler/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, retest-not-required-docs-only, size/XS

#1238 Update OWNERS
  pkg/scheduler/OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, retest-not-required-docs-only, size/XS

#1239 fix: fix some small mistakes
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/event_handlers_test.go
Labels: approved, lgtm, size/S

#1225 Fix #1218 CI
  .github/workflows/main.yaml
Labels: approved, lgtm, size/M

#1248 fix(ci): add hacky retry mechanism
  .github/workflows/main.yaml
Labels: approved, lgtm, size/XS

#1219 doc: add custom plugin design doc (#1215)
  docs/design/custom-plugin.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L, v1.2.0

#1232 add reviewer for zen-xu
  pkg/scheduler/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1166 fix: fix scheduler deployment warnning log
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/XS

#1255 fix: more pods are reclaimed than required
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#1254 feat(example): add job plugin example
  example/integrations/mpi/mpi-example.yaml
  example/job-plugin.yaml
Labels: approved, lgtm, size/M

#1260 fix: more pods are reclaimed than required
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#1262 fix:e2e helm install timeout
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/XS

#1263 feat(controller): update ssh secret when job updated
  pkg/apis/helpers/helpers.go
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/M

#1274 refine deployment.yaml example
  example/deployment.yaml
Labels: approved, lgtm, size/XS

#1266 add Makefile flag `SUPPORT_PLUGINS`
  Makefile
  docs/design/custom-plugin.md
Labels: approved, lgtm, size/M
