Repository volcano-sh/volcano, pull requests merged in 2021-08, with the labels that each got.

#1643 refactor the preempt function in plugin gang
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/M

#1654 fix some commnents
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/plugins/interface/interface.go
Labels: approved, lgtm, size/S

#1655 docs: fix the broken URL
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1657 Not delete failed pods on last try
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#1660 format env key
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/S

#1656 fix addmission parsing bug
  cmd/webhook-manager/app/options/options.go
  pkg/webhooks/router/admission.go
Labels: approved, lgtm, size/XS

#1644 add user-provided rsa key-pair and mount rsa key-pair in InitContainers since we want to clone private git repository before run training task
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/ssh/ssh_test.go
Labels: approved, lgtm, size/M

#1662 fix OOM will occur if pod info is sync before node info
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/vcctl/command.go
Labels: approved, lgtm, size/S

#1667 feat: add jasonliu747 as reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#1659 fix some problems of golangci-lint
  .golangci.yml
  Makefile
  cmd/webhook-manager/app/server.go
  pkg/cli/queue/util.go
  pkg/controllers/apis/job_info.go
  pkg/controllers/apis/request.go
  pkg/controllers/cache/interface.go
  pkg/controllers/framework/factory.go
  pkg/controllers/framework/interface.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller_resync.go
  pkg/controllers/job/plugins/factory.go
  pkg/controllers/job/state/running.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/elect/elect.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/cache/util.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/plugins/reservation/reservation.go
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
  pkg/scheduler/util/test_utils.go
  pkg/webhooks/config/config.go
  pkg/webhooks/router/interface.go
Labels: approved, lgtm, ok-to-test, size/L

#1670 enable eight golangci-lint linters and fix lint errors
  .golangci.yml
  cmd/cli/vcctl.go
  cmd/webhook-manager/app/server.go
  pkg/cli/job/delete.go
  pkg/cli/job/view.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/vjobs/view.go
  pkg/cli/vqueues/get.go
  pkg/cli/vsub/run.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/job/state/completing.go
  pkg/controllers/job/state/restarting.go
  pkg/controllers/job/state/terminating.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/queue/queue_controller.go
  pkg/filewatcher/filewatcher.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/plugins/util/util.go
  pkg/webhooks/admission/jobs/validate/util.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/queues/validate/validate_queue.go
Labels: approved, lgtm, size/M

#1668 fix(interpodaffinity): make 'existing pods anti-affinity rules' work
  pkg/scheduler/plugins/util/k8s/snapshot.go
Labels: approved, lgtm, size/S

#1669 fix golangci-lint install
  Makefile
  hack/verify-golangci-lint.sh
Labels: approved, lgtm, size/M

#1666 add setting MinResources to pg for normal pod
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/volcano-development.yaml
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/L

#1673 fix(scheduler): modify default scheduler cfg
  pkg/scheduler/util.go
Labels: approved, lgtm, size/XS

#1674 fix typo
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#1675 ci code check transfer from golint to golangci-lint
  .github/workflows/code_verify.yaml
  Makefile
  hack/.golint_failures
  hack/verify-golint.sh
Labels: approved, lgtm, size/L

#1678 add revive linter as drop-in replacement of archived golint
  .golangci.yml
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
Labels: approved, lgtm, size/S

#1681 Automatically set GOMAXPROCS for scheduler & controller & webhook-manager
  LICENSES/vendor/go.uber.org/automaxprocs/LICENSE
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  cmd/webhook-manager/main.go
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/.codecov.yml
  vendor/go.uber.org/automaxprocs/.gitignore
  vendor/go.uber.org/automaxprocs/.travis.yml
  vendor/go.uber.org/automaxprocs/CHANGELOG.md
  vendor/go.uber.org/automaxprocs/CODE_OF_CONDUCT.md
  vendor/go.uber.org/automaxprocs/CONTRIBUTING.md
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/Makefile
  vendor/go.uber.org/automaxprocs/README.md
  vendor/go.uber.org/automaxprocs/automaxprocs.go
  vendor/go.uber.org/automaxprocs/glide.yaml
  vendor/go.uber.org/automaxprocs/go.mod
  vendor/go.uber.org/automaxprocs/go.sum
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1682 lower ssh key access permission
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, size/XS

#1683 Optimization register controller log
  pkg/controllers/framework/factory.go
Labels: approved, lgtm, size/XS

#1672 feat: expose detailed scheduling reason of pending tasks based on las…
  docs/design/scheduling-reason.md
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/unschedule_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/L

#1701 fix daily release job fails
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#1637 fix overused judgement when deal with allocate and proportion
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/L

#1702 add docker logout for daily release to remove credentials from docker…
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#1703 update go version to 1.16 and helm version to stable v3.6.3
  go.mod
  go.sum
  hack/generate-yaml.sh
  test/e2e/jobp/jobp.coverprofile
Labels: approved, lgtm, size/L
