Repository volcano-sh/volcano, pull requests merged in 2021-06, with the labels that each got.

#1497 fix select wrong queue when `proportion` is disable
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/S

#1489 change min resource to 0.1 in resource_info
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/M

#1511 CI e2e optimization
  test/e2e/jobseq/job_error_handling.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/S

#1510 use struct NodeScoreList better than HostPriorityList for score
  go.mod
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/util/scheduler_helper.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1499 fix(scheduler): use nodeMap to fix anti-affinity problem
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/S

#1512 the member Others should be copied in func (ni *NodeInfo) Clone()
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#1490 sort resource comparation functions, add accurate definitions and fix…
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/drf/drf.go
Labels: approved, lgtm, size/L

#1517 Improve: remove nodename from taskinfo when RemoveTask
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/S

#1520 update readme up to date
  README.md
  docs/images/volcano-architecture.png
  docs/images/volcano-horizontal-color.png
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#1523 add GOPATH for daily release
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#1528 add shinytang6 to volcano maintainer
  MAINTAINERS.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1521 support multi-cluster scheduling in framework
  LICENSES/vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/job_controller_util_test.go
  pkg/controllers/job/job_state_test.go
  pkg/scheduler/api/silo_cluster_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/go.mod
  vendor/github.com/agiledragon/gomonkey/v2/go.sum
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/labels.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: lgtm, size/XL

#1529 update volcano community introduction materials
  SECURITY.md
  contribute.md
  docs/community/adopters.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1531 feat: add shinytang6 to OWNERS
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1505 add min success design
  docs/design/images/min-success-1.png
  docs/design/images/min-success-2.png
  docs/design/minsuccess.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1515 add huone1 to the reviewers
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#1541 optimizing openSession
  pkg/scheduler/framework/framework.go
Labels: approved, lgtm, size/S

#1527 scheduling with proportion of resources #1369
  docs/design/images/proportional-diagram.png
  docs/design/proportional.md
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/plugins/predicates/proportional_test.go
Labels: approved, lgtm, size/L

#1540 fix(scheduler): reclaim action minus and comparison bug
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#1437 submit the guide files about numa-aware
  docs/design/images/numa-aware-process.png
  docs/design/numa-aware.md
  docs/user-guide/how_to_use_numa_aware.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#1546 fix resource comparasion bug in task topology
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/task-topology/topology.go
Labels: approved, lgtm, size/L

#1547 fix bug in predicates plugin
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/XS

#1552 fix static check warning in pkg folder
  cmd/webhook-manager/app/server.go
  pkg/cli/job/run.go
  pkg/cli/job/util.go
  pkg/cli/queue/delete.go
  pkg/cli/queue/delete_test.go
  pkg/cli/queue/operate.go
  pkg/cli/queue/operate_test.go
  pkg/cli/util/util.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/predicates/cache.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/sla/sla.go
  pkg/scheduler/plugins/util/k8s/snapshot.go
  pkg/scheduler/plugins/util/util.go
  pkg/scheduler/util.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/util.go
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, lgtm, size/L

#1556 Add arch node selectors to the installer arm&amd64
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XS

#1563 Improve: preempt break out if intersection is null
  pkg/scheduler/framework/session_plugins.go
Labels: approved, lgtm, size/S

#1566 support oversubscription in volcano framework
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/api/well_known_labels.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/L
