Repository volcano-sh/volcano, pull requests merged in 2021-12, with the labels that each got.

#1862 optimize the CA parse Process
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  cmd/webhook-manager/main.go
Labels: approved, lgtm, size/M

#1868 feat: add imagelocality priority to nodeOrder
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/imagelocality/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/imagelocality/image_locality.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1871 add rbac for csinode
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#1873 fix the security alert from Kubernetes
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/code-generator/third_party/forked/golang/LICENSE
  vendor/k8s.io/code-generator/third_party/forked/golang/PATENTS
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/kubernetes/pkg/controller/volume/scheduling/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources/most_allocated.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_fake_mounter.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_mount.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_mount_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_mount_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1875 add a argument csi-storage to control the storage capacity resource
  cmd/scheduler/app/options/options.go
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1883 fix the deep clone of JobInfo
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/pod_group_info.go
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, ok-to-test, size/S

#1888 add healthz and metric switch for deploy controller and scheduler
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M

#1890 Fix repeat not in log.
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/XS

#1893 update PriorityClass from scheduling.k8s.io/v1beta1 to scheduling.k8s…
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  test/e2e/util/util.go
Labels: approved, lgtm, size/L

#1895 enhance the security of TLS client authentication for webhook
  cmd/webhook-manager/app/util.go
Labels: approved, lgtm, size/S

#1897 update PriorityClass from v1beta1 to v1 for go-client
  pkg/controllers/job/job_controller.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#1874 Add tensorflow job plugin
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/plugins/distributed-framework/tensorflow/tensorflow.go
  pkg/controllers/job/plugins/distributed-framework/tensorflow/tensorflow_test.go
  pkg/controllers/job/plugins/factory.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  test/e2e/jobseq/tensorflow_plugin.go
Labels: approved, lgtm, size/XL

#1896 support label volcano.sh/task-priority
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#1834 [fix]add nodeSelector design doc
  docs/design/images/node-selector-1.png
  docs/design/images/node-selector-2.png
  docs/design/node-selector.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#1887 add elastic scheduler design doc
  docs/design/elastic-scheduler.md
  docs/design/images/elastic-scheduler-job1-1-2.png
  docs/design/images/elastic-scheduler-job1-1.png
  docs/design/images/elastic-scheduler-job1-2.png
  docs/design/images/elastic-scheduler-job1-3.png
  docs/design/images/elastic-scheduler-job2-1.png
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#1898 default sort task by index
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
  pkg/scheduler/framework/session_plugins.go
Labels: approved, lgtm, size/L

#1886 add eventhandler framework proposal
  docs/design/event-handler-framework.md
  docs/design/images/event-handler-arch.png
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#1906 optimize: reuse predicate error on same task group
  pkg/controllers/apis/job_info.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/util/predicate_helper.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/L

#1913 fix: allocate ut for "two Jobs on one node"
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/S

#1912 update golang to v1.17
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yaml
  hack/tool.go
Labels: approved, lgtm, size/S

#1821 support reserved node
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M

#1916 fix scheduling process starts even if resource synchronization is not complete
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#1833 task level advanced scheduling policy
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  docs/design/distributed-framework-plugins.md
  example/task-start-dependency/job.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-latest.yaml
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/distributed-framework/tensorflow/tensorflow.go
  pkg/controllers/job/plugins/env/env.go
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/job.go
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/bus/v1alpha1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/nodeinfo/v1alpha1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#1904 support reserved resources by guarantee field in QueueSpec doc
  docs/design/queue-guarantee-resource-reservation-design.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#1920 feat(webhook): add task dependson webhook
  pkg/controllers/cache/cache.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/plugins/svc/svc.go
  pkg/controllers/job/state/aborting.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_util.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/elect/elect_test.go
  pkg/scheduler/cache/util.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/predicates/proportional_test.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/admission/jobs/validate/util.go
  pkg/webhooks/admission/jobs/validate/util_test.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
Labels: approved, lgtm, size/L

#1905 support reserved resources by guarantee field in QueueSpec
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/api/helpers/helpers_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  test/e2e/schedulingaction/guarantee.go
  test/e2e/util/queue.go
Labels: approved, lgtm, size/L

#1762 enhance the volcano topology framework
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/well_known_labels.go
  pkg/scheduler/plugins/numaaware/numaaware.go
Labels: approved, lgtm, size/L

#1919 update CustomResourceDefinition version to v1
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/S

#1924 add mpi example for task dependency
  example/task-start-dependency/mpi.yaml
Labels: approved, lgtm, size/M

#1928 fix some log mistakes for e2e test
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/XS

#1926 [squash]Automatically generate the appropriate CRD
  installer/helm/chart/volcano/templates/_helpers.tpl
  installer/helm/chart/volcano/templates/batch_v1alpha1_job.yaml
  installer/helm/chart/volcano/templates/bus_v1alpha1_command.yaml
  installer/helm/chart/volcano/templates/nodeinfo_v1alpha1_numatopologies.yaml
  installer/helm/chart/volcano/templates/scheduling_v1beta1_podgroup.yaml
  installer/helm/chart/volcano/templates/scheduling_v1beta1_queue.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/S
