Repository volcano-sh/volcano, pull requests merged in 2022-06, with the labels that each got.

#2260 bugfix: avoid panic for query prometheus no data
  go.mod
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#2266 fix(scheduler): fix jobStarvingFn logic
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#2267 [cherry-pick] cherry pick important patchs to release-1.6
  go.mod
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/well_known_labels.go
  pkg/scheduler/cache/cache.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
Labels: approved, lgtm, size/L

#2271 [cherry-pick] fix(scheduler): fix jobStarvingFn logic
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#2268 Default queue name from namespace annotations, when no queue name in pod spec
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
Labels: approved, lgtm, size/S

#2288 fix some bugs about rescheduling plugin
  LICENSES/vendor/github.com/mitchellh/mapstructure/LICENSE
  go.mod
  go.sum
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
  pkg/scheduler/actions/shuffle/shuffle.go
  pkg/scheduler/plugins/rescheduling/low_node_utilization.go
  pkg/scheduler/plugins/rescheduling/node_utilization_util.go
  pkg/scheduler/plugins/rescheduling/rescheduling.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2293 bump volcano api definition to v1.6.0 in dependencies
  coverprofile.out
  go.mod
  go.sum
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
  vendor/sigs.k8s.io/yaml/.gitignore
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/README.md
  vendor/volcano.sh/apis/pkg/apis/flow/v1alpha1/doc.go
  vendor/volcano.sh/apis/pkg/apis/flow/v1alpha1/jobflow_types.go
  vendor/volcano.sh/apis/pkg/apis/flow/v1alpha1/jobtemplate_types.go
  vendor/volcano.sh/apis/pkg/apis/flow/v1alpha1/register.go
  vendor/volcano.sh/apis/pkg/apis/flow/v1alpha1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/clientset.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/fake/register.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/scheme/register.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/doc.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/fake/doc.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/fake/fake_flow_client.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/fake/fake_jobflow.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/fake/fake_jobtemplate.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/flow_client.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/generated_expansion.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/jobflow.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/flow/v1alpha1/jobtemplate.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/factory.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/flow/interface.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/flow/v1alpha1/interface.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/flow/v1alpha1/jobflow.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/flow/v1alpha1/jobtemplate.go
  vendor/volcano.sh/apis/pkg/client/informers/externalversions/generic.go
  vendor/volcano.sh/apis/pkg/client/listers/flow/v1alpha1/expansion_generated.go
  vendor/volcano.sh/apis/pkg/client/listers/flow/v1alpha1/jobflow.go
  vendor/volcano.sh/apis/pkg/client/listers/flow/v1alpha1/jobtemplate.go
Labels: approved, lgtm, size/XXL

#2294 update release version and tag to v1.6.0
  Makefile.def
Labels: approved, lgtm, size/XS

#2295 upadte the installer for v1.6.0
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/XS

#2297 fix: proportion metrics accuracy
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/proportion/proportion_test.go
Labels: approved, lgtm, size/L

#2227 nodegroup plugin design doc
  docs/design/images/node-group-case-1.png
  docs/design/images/node-group-case-2.png
  docs/design/node-group.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#2314 Add documentation on ttlSecondsAfterFinished
  docs/user-guide/how_to_use_job_ttl.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only
