Repository volcano-sh/volcano, pull requests merged in 2022-07, with the labels that each got.

#2326 fix defaultMetricsInternal variable
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#2309 change enqueue to optional action
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/scheduler.go
  test/e2e/schedulingaction/enqueue.go
  test/e2e/util/configmap.go
Labels: approved, lgtm, size/L

#2325 fix convertQuanToPercent func
  pkg/scheduler/plugins/rescheduling/node_utilization_util.go
Labels: approved, lgtm, size/XS

#2318 To record the start and end time of job scheduling
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/metrics/job.go
  pkg/scheduler/metrics/metrics.go
Labels: approved, lgtm, size/M

#2089 fix: fix admission not support ip address which will cause ssl error.…
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
Labels: approved, lgtm, size/S

#2307 fix scheduler cache waitforcachesync
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#2279 Validate queue closed state in Pod validation webhook
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
Labels: approved, lgtm, size/L

#2334 Support JobReady for extender plugin
  pkg/scheduler/plugins/extender/argument.go
  pkg/scheduler/plugins/extender/extender.go
Labels: approved, lgtm, size/S

#2275 use informerfactory start all informers
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/queue/queue_controller.go
Labels: approved, lgtm, size/L

#2342 filter the rescheduling strategies which contain victim fucntions
  pkg/scheduler/plugins/rescheduling/rescheduling.go
Labels: approved, lgtm, size/XS

#2343 [cherry-pick]filter the rescheduling strategies which contain victim fucntions
  pkg/scheduler/plugins/rescheduling/rescheduling.go
Labels: approved, lgtm, size/XS

#2347 add details for nodegroup doc
  docs/design/node-group.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2350 change e2e dependencies of makefile
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
  Makefile
Labels: approved, lgtm, size/M

#2354 fix ci error about mpi plugin struct naming is not standardized
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
Labels: approved, lgtm, size/M

#2149 add cooldown protection plugin
  docs/user-guide/how_to_use_cdp_plugin.md
  go.mod
  go.sum
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/plugins/cdp/cdp.go
  pkg/scheduler/plugins/cdp/cdp_test.go
  pkg/scheduler/plugins/factory.go
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
Labels: approved, lgtm, size/XL, priority/important-soon

#2360 clean up the code
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#2313 Add pytorch plugin
  docs/design/distributed-framework-plugins.md
  docs/user-guide/how_to_use_pytorch_plugin.md
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch_test.go
  pkg/controllers/job/plugins/distributed-framework/tensorflow/tensorflow.go
  pkg/controllers/job/plugins/factory.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  test/e2e/jobseq/pytorch_plugin.go
Labels: approved, lgtm, size/XL

#2351 fix bug in task dependsOn
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#2371 add csiNode cache for plugin
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/M

#2339 add jobflow desgin docs
  README.md
  docs/design/images/jobflow-1.png
  docs/design/images/jobflow-2.jpg
  docs/design/images/jobflow-3.png
  docs/design/images/jobflow-4.png
  docs/design/images/jobflow.gif
  docs/design/jobflow/jobflow.md
  example/jobflow/JobFlow.yaml
  example/jobflow/JobTemplate.yaml
Labels: approved, lgtm, size/XL

#2380 add owners file for webhook and scheduler plugin
  pkg/scheduler/plugins/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#2386 Update field comment
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go
Labels: approved, lgtm, size/XS

#2378 add rest config into ssn
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/S

#2353 update go to 1.18
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#2393 support multi scheduler name for scheduler and webhook
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/util.go
  pkg/scheduler/scheduler.go
  pkg/util/util.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  pkg/webhooks/router/interface.go
Labels: approved, lgtm, size/L

#2392 use patch to replace update pod operator
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
Labels: approved, lgtm, size/M

#2388 modify the meeting schedule for Europe and America area
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2399 get csinodes from ssn
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/XS
