Repository volcano-sh/volcano, pull requests merged in 2022-04, with the labels that each got.

#2105 support elastic annotation in preempt/reclaim plugin
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  test/e2e/schedulingaction/preempt.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/M

#2157 update readme that Volcano has been accepted as an incubating project
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2159 remove useless code in task-topology's manager.go
  pkg/scheduler/plugins/task-topology/manager.go
Labels: approved, lgtm, size/XS

#2023 add design doc for usage based scheduling
  docs/design/usage-based-scheduling.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2163 fix: Add mirror for Spark voclano IT
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/XS

#2164 fix controller warning message
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#2153 add user guidance of env plugin
  docs/user-guide/how_to_use_env_plugin.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#2172 Only enable merge check for spark IT
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/XS

#2168 add user guidance for ssh plugin
  docs/user-guide/how_to_use_ssh_plugin.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2154 allow no retry when task failed
  pkg/controllers/cache/cache.go
Labels: approved, lgtm, size/XS

#2178 Rename ClusterRole from prometheus to prometheus-volcano
  installer/helm/chart/volcano/templates/prometheus.yaml
Labels: approved, lgtm, size/XS

#2185 Add Image pull secret for volcano-admission-init job
  installer/helm/chart/volcano/templates/admission.yaml
Labels: approved, lgtm, size/XS

#2129 add usage based scheduling plugin
  go.sum
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/usage/usage.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2176 fix task MinAvailable issue
  pkg/scheduler/api/job_info.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, size/M

#2179 add user guidance about how to configure job and task policy
  docs/user-guide/how_to_use_job_policy.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2174 add shuffle action
  LICENSES/vendor/github.com/golang/mock/LICENSE
  go.mod
  go.sum
  pkg/scheduler/actions/factory.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/shuffle/shuffle.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/mock_gen/action_and_plugin.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/util/test_utils.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2177 add user guidance about how to configure volcano scheduler
  docs/user-guide/how_to_configure_scheduler.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2170 add overhead for pod request
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
Labels: approved, lgtm, size/M

#2151 design doc for Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod
  docs/design/Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md
  docs/design/images/original-process.png
  docs/design/images/workflow.png
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2169 fix controller job cache not sync latest version issue
  pkg/controllers/cache/cache.go
  pkg/controllers/cache/cache_test.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_state_test.go
Labels: approved, lgtm, size/L

#2173 support elastic
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#2196 remove unresonable UT for allocate action
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/S

#2197 update the dependency of apis up to date
  config/crd/bases/batch.volcano.sh_jobs.yaml
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-latest.yaml
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/job.go
  vendor/volcano.sh/apis/pkg/apis/helpers/helpers.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/clientset.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/batch/v1alpha1/batch_client.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/batch/v1alpha1/fake/fake_job.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/bus/v1alpha1/bus_client.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/bus/v1alpha1/fake/fake_command.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/fake/fake_numatopology.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/nodeinfo_client.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/scheduling/v1beta1/fake/fake_podgroup.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/scheduling/v1beta1/fake/fake_queue.go
  vendor/volcano.sh/apis/pkg/client/clientset/versioned/typed/scheduling/v1beta1/scheduling_client.go
Labels: approved, lgtm, size/L

#2200 add priorityClassName for rescheduler
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S
