Repository volcano-sh/volcano, pull requests merged in 2022-03, with the labels that each got.

#2038 Fix the resource calculation error for running jobs whose podgroup contains minResource
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/M

#2057 [cherry-pick] cherry pick recently fix to v1.5
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/M

#2055 [cherry-pick] cherry pick recently fix to v1.4
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/M

#2064 Upgrade Volcano webhook from v1beta1 to v1
  cmd/webhook-manager/app/util.go
  docs/design/queue/queue-state-management.md
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
  pkg/webhooks/admission/queues/mutate/mutate_queue_test.go
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
  pkg/webhooks/router/interface.go
  pkg/webhooks/router/server.go
  pkg/webhooks/schema/schema.go
  pkg/webhooks/util/util.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2030 update arm's yaml, and upgrade makefile to automatically generate arm's yaml
  Makefile
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XXL

#2061 fix that parse the scheduler configuration argument with blank error
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
Labels: approved, lgtm, size/M

#2069 Make sure Open state queue can be deleted
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
  test/e2e/jobp/admission.go
Labels: approved, lgtm, size/S

#2071 Change volcano docker release time to 2 times per day
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#2077 [cherry-pick] merge key bug fixes to release1.5
  cmd/webhook-manager/app/util.go
  docs/design/queue/queue-state-management.md
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
  pkg/webhooks/admission/queues/mutate/mutate_queue_test.go
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
  pkg/webhooks/router/interface.go
  pkg/webhooks/router/server.go
  pkg/webhooks/schema/schema.go
  pkg/webhooks/util/util.go
  test/e2e/jobp/admission.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2078 fix the driver pod can not be created due to unreasonable admit
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  test/e2e/jobp/admission.go
  test/e2e/schedulingaction/preempt.go
Labels: approved, lgtm, size/M

#2081 [cherry-pick]fix the driver pod can not be created due to unreasonable admit
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
  test/e2e/jobp/admission.go
  test/e2e/schedulingaction/preempt.go
Labels: approved, lgtm, size/M

#2082 update the version to v1.5.1-beta.0
  Makefile.def
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#2084 fix the jobShare metric when job terminated
  pkg/scheduler/cache/cache.go
  pkg/scheduler/metrics/job.go
Labels: approved, lgtm, size/XS

#2059 add key feautures roadmap for v1.6
  docs/community/roadmap.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#2091 release v1.5.1
  Makefile.def
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#2097 fix some spell error for drf doc
  docs/design/drf.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2104 Modify the way to install the controller-gen
  Makefile
Labels: approved, lgtm, size/XS

#2103 update helm version in install.sh
  hack/lib/install.sh
Labels: approved, lgtm, size/XS

#2117 Remove reduplicate code
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/XS

#2113 Add `E2E Spark Integration Test`
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/M

#2125 Skip verify init container SecurityContex.Privileged
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, size/M

#2133 fix dynamic provision ut case error
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/M

#2132 fix signal on operating system expcept windows
  pkg/signals/signal_posix.go
Labels: approved, lgtm, size/XS

#2122 [code refine] if only one candidate node, no need do scoring for it
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/S
