Repository volcano-sh/volcano, pull requests merged in 2022-09, with the labels that each got.

#2477 add plugin registration log
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/S

#2478 add action/plugin registration and loading log
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/S

#2480 Import volumeZone plugin.
  pkg/scheduler/plugins/predicates/predicates.go
  vendor/k8s.io/cloud-provider/volume/constants.go
  vendor/k8s.io/cloud-provider/volume/helpers/rounding.go
  vendor/k8s.io/cloud-provider/volume/helpers/zones.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumezone/volume_zone.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2483 fix scheduler panic issue when pv is not created
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#2484 [cherry-pick] Import volumeZone plugin.
  pkg/scheduler/plugins/predicates/predicates.go
  vendor/k8s.io/cloud-provider/volume/constants.go
  vendor/k8s.io/cloud-provider/volume/helpers/rounding.go
  vendor/k8s.io/cloud-provider/volume/helpers/zones.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumezone/volume_zone.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2489 fix 2488, scheduler panic
  pkg/scheduler/plugins/resourcequota/resourcequota.go
Labels: approved, lgtm, size/XS

#2495 Add Yikun as reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2497 Add jiangkaihua as reviewer.
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only, do-not-merge/invalid-owners-file

#2500 add selector spread plugin
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  vendor/k8s.io/component-helpers/node/topology/helpers.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/selectorspread/selector_spread.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2475 fix gpu shareing predictor allocate more than one gpu for pod
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/S

#2487 add podTopologySpread plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/common.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/plugin.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2504 fix printing volcano-scheduler-configmap loading log;
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#2506 add volume binding plugin
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/M

#2507 [cherry-pick] fix action/plugin register log-printing issues;
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#2509 bugfix: the csinode driver status failed updating
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/S

#2515 delete task qos limit in webhook
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, size/M

#2514 add podTopologySpread plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/common.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/plugin.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2513 delete task qos limit in webhook
  pkg/webhooks/admission/jobs/validate/admit_job.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, size/M
