Repository volcano-sh/volcano, pull requests merged in 2022-02, with the labels that each got.

#1923 add design doc for rescheduling
  docs/design/rescheduling.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#2000 optimize error function when return unschedulable info
  pkg/scheduler/api/unschedule_info.go
Labels: approved, lgtm, size/S

#1998 feat: implement extender plugin
  docs/design/extender.md
  docs/user-guide/how_to_use_extender.md
  example/extender/extender.go
  pkg/scheduler/plugins/extender/argument.go
  pkg/scheduler/plugins/extender/extender.go
  pkg/scheduler/plugins/factory.go
Labels: approved, lgtm, size/XL

#2004 Add individual development yamls for volcano 1.5
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2011 Automatically generate yaml files for arm64
  Makefile
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XXL

#2019 fix: demo missed queue default config
  example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml
Labels: approved, lgtm, size/XS

#2016 remove mutex during numa-cnt calculation
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/M

#2002 Add individual development yamls for volcano 1.4
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2026 [cherry-pick] optimize resource comparision functions for performance
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/L

#2029 Remove place holder port
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, lgtm, size/XS

#2013 update the version in deployment file for arm64
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XS

#2031 release v1.4.1
  Makefile.def
  coverprofile.out
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L

#2032 release v1.5.0
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/XS

#1861 fix queue allocated exceeds capability
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#2035 [cherry-pick]fix queue allocated exceeds capability
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#2036 [cherry-pick]fix queue allocated exceeds capability
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#1990 update config args to map[string]interface{} to extend the configs
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/sla/sla.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/plugins/tdm/tdm_test.go
Labels: approved, lgtm, size/M

#2043 add assert for interface to string to pass the CI
  pkg/scheduler/plugins/extender/extender.go
Labels: approved, lgtm, size/S

#2042 set the initial phase to be pending for podgroup
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/XS
