Repository volcano-sh/volcano, pull requests merged in 2022-10, with the labels that each got.

#2505 scheduler support ephemeral-storage resources
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/S

#2526 Realias scheduling api version name in package imports
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_state_test.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/M

#2537 upgrade golangci-lint to v1.50.0;
  hack/verify-golangci-lint.sh
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#2525 Use RWMutex in framework
  pkg/scheduler/framework/plugins.go
Labels: approved, kind/feature, size/S

#2542 merge pr from release-1.6
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/controllers/framework/interface.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  vendor/k8s.io/component-helpers/node/topology/helpers.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/selectorspread/selector_spread.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2523 enable https healthz listen;
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/helpers/helpers.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
Labels: approved, lgtm, size/L

#2541 fix unit test
  Makefile
  cmd/controller-manager/app/options/options_test.go
  pkg/cli/job/run_test.go
Labels: approved, lgtm, size/S

#2548 Fix unit test in cmd
  cmd/controller-manager/app/options/options_test.go
Labels: approved, kind/bug, lgtm, size/XS

#2553 fix issue queue is not met even if oldDeserved and deserved are the same
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#2557 cherry-pick: queue is not met even if oldDeserved and deserved are the same
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS
