Repository volcano-sh/volcano, pull requests merged in 2022-11, with the labels that each got.

#2561 Revert "add volume binding plugin"
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/M

#2555 Revert "merge #2506(add volume binding plugin) into scheduler/plugins/nodeorder;"
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/M

#2545 pod could be preempted by default
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/plugins/tdm/tdm_test.go
Labels: approved, lgtm, size/XS

#2568 fix extender plugin http send wrong action name
  pkg/scheduler/plugins/extender/extender.go
Labels: approved, lgtm, size/XS

#2577 fix(predicates/predicateGPUbyMemory): traversal key of map are not sequence
  pkg/scheduler/plugins/predicates/gpu.go
Labels: approved, lgtm, size/XS

#2550 add node lock mechanism to support multiple pods/containers with the same ammount of request
  docs/design/images/node-lock.jpg
  docs/design/node-lock.md
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/nodelock.go
Labels: approved, lgtm, size/L

#2580 move prefilter out of predicates to improve performance
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L

#2581 replace queueMap with sets.String in enqueue action to improve readable
  pkg/scheduler/actions/enqueue/enqueue.go
Labels: approved, lgtm, size/XS

#2574 Add enable overusedfn and allocatablefn switch
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/M

#2586 cherry pick 1.7：pod could be preempted by default；move prefilter out of predicates to improve performance
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/tdm/tdm_test.go
Labels: approved, lgtm, size/L
