Repository volcano-sh/volcano, pull requests merged in 2022-12, with the labels that each got.

#2590 Move spark e2e integration from self-hosted to github-hosted
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/M

#2595 🦄 refactor(binpack):optimize the code to get resourceWeight
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/binpack/binpack_test.go
Labels: approved, lgtm, size/S

#2597 :pencil2: fix nodeScoreMap to nodeScoreList
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XS

#2592 Add allocated field in queue status to indicate used resources in queue.
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/util/scheduler_helper.go
  test/e2e/util/queue.go
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2601 Added KubeRay docs
  README.md
  docs/community/adopters.md
  docs/getting-started/getting-started.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2599 :art: optimize the job-topology code and avoid the potential panic
  pkg/scheduler/plugins/task-topology/topology.go
Labels: approved, lgtm, size/S

#2593 Add node image information to the cache of the scheduler.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/L

#2603 🌈 style(task-topology): refactor hasPendingTasks as job method
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/plugins/task-topology/util.go
Labels: approved, lgtm, size/S

#2608 [cherry-pikc 1.7]Move spark e2e integration from self-hosted to github-hosted
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/M

#2605 [cherry-pick 1.7] Add node image information to the cache of the scheduler.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/L

#2604 [Cherry-pick] Add allocated field in queue status to indicate used resources in queue. #2592
  config/crd/bases/scheduling.volcano.sh_queues.yaml
  config/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/util/scheduler_helper.go
  test/e2e/util/queue.go
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/scheduling/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/types.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#2613 By default, the preemption function of gang and drf is turned off
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#2602 Remove `Undetermined` reason to fix cluster autoscaler compatibility
  docs/design/scheduling-reason.md
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/unschedule_info.go
Labels: approved, lgtm, size/S

#2614 [cherry-pick 1.7] Disable the preemption switch of gang and drf in the default configuration
  installer/helm/chart/volcano/config/volcano-scheduler-ci.conf
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#2618 The referenced Volcano API version is updated to 1.7
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#2619 [cherry-pick] Remove Undetermined reason to fix cluster autoscaler compatibility
  docs/design/scheduling-reason.md
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/unschedule_info.go
Labels: approved, lgtm, size/S

#2621 Added KubeRay docs
  README.md
  docs/community/adopters.md
  docs/getting-started/getting-started.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2623 Modify preempt victim order.
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/XS

#2626 [Cherry-pick] Modify preempt victim order.
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/XS

#2628 update image to v1.7.0-beta.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/release.yaml
  Makefile
  Makefile.def
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.7.0-beta.0.yaml
Labels: approved, lgtm, size/M

#2630 fix: deployment and pod, high priority cannot preempt low priority resources
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/XS

#2634 The preemption logic is only controlled by jobMinavailable in the gang plugin
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/XS

#2573 The requests of extended resource(such as nvidia.com/gpu) is missing in PodGroup's minResource
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/util/util.go
  pkg/controllers/util/util_test.go
  test/e2e/jobp/job_controlled_resource.go
Labels: approved, lgtm, size/L

#2635 Cherry pick for 1.7
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/util/util.go
  pkg/controllers/util/util_test.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/jobp/job_controlled_resource.go
Labels: approved, lgtm, size/L

#2636 update image to v1.7.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/release.yaml
  Makefile
  Makefile.def
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.7.0.yaml
Labels: approved, lgtm, size/M
