Repository volcano-sh/volcano, pull requests merged in 2022-08, with the labels that each got.

#2400 try get get old pg when new pg not exist
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#2401 [cherry-pick] get old pg when new pg not exist
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/M

#2372 update image version from latest to v1.6.0
  .github/workflows/code_verify.yaml
  Makefile
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.6.0.yaml
Labels: approved, lgtm, size/M

#2403 add hwdef as approver in controller and webhook submodule
  pkg/controllers/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2410 fix scheduler panic when webhook is not ready
  pkg/scheduler/cache/cache.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2411 [cherry-pick] fix scheduler panic when webhook is not ready
  pkg/scheduler/cache/cache.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2413 bugfix: panic if queue already exists
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#2418 fix defaultMetricsInternal variable
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#2420 fix nil pointer in jobCache.update
  pkg/controllers/cache/cache.go
Labels: approved, lgtm, size/S

#2421 fix nil pointer in jobCache.update
  pkg/controllers/cache/cache.go
Labels: approved, lgtm, size/S

#2423 Consider initContainer GPUs quota in calculating
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
Labels: approved, lgtm, size/L

#2427 fix README.md clearly
  README.md
  docs/design/jobflow/README.md
  example/jobflow/README.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#2346 deploy webhook by yaml
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#2431 [cherry-pick] Consider initContaienr GPUs in considering quota
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
Labels: approved, lgtm, size/L

#2432 [cherry-pick]Consider initContaienr GPUs in considering quota
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
Labels: approved, lgtm, size/L

#2433 [cherry-pick]Consider initContaienr GPUs in considering quota
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
Labels: approved, lgtm, size/L

#1692 Add GPU Numbers Predicates
  docs/images/gpu-number.png
  docs/user-guide/how_to_use_gpu_number.md
  docs/user-guide/how_to_use_gpu_sharing.md
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/plugins/predicates/gpu.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L, priority/important-soon

#2434 Some cleanups in job_info.go
  pkg/scheduler/api/job_info.go
Labels: approved, kind/cleanup, lgtm, size/M

#2441 Fix calculating available gpu num error
  pkg/scheduler/plugins/predicates/gpu.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, kind/bug, lgtm, size/M

#2435 add multi-arch image
  .github/workflows/e2e_spark.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  docs/development/development.md
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/controller-manager/Dockerfile.arm64
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/scheduler/Dockerfile.arm64
  installer/dockerfile/webhook-manager/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile.arm64
  installer/dockerfile/webhook-manager/Dockerfile.base
  installer/dockerfile/webhook-manager/Dockerfile.base.arm64
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/XXL

#2443 fix performance downgrade issue
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/framework/job_updater.go
Labels: approved, lgtm, size/S

#2444 fix performance downgrade issue
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/framework/job_updater.go
Labels: approved, lgtm, size/S

#2445 Optimize the way to build images in makefile
  Makefile
  hack/lib/install.sh
  hack/publish.sh
Labels: approved, lgtm, size/M

#2446 docs: fix error in how to configure scheduler
  docs/user-guide/how_to_configure_scheduler.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2448 fix error during daily release
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#2440 Add initContainer GPU number when calculating GPUs
  go.mod
  pkg/scheduler/api/device_info.go
  pkg/scheduler/api/device_info_test.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
Labels: approved, kind/feature, lgtm, size/L

#2450 deploy webhook by yaml
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#2458 Add nodeVolumeLimits plugin.
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/non_csi.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2461 add a flag to control whether inherit owner annotations when podgroup…
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/M

#2463 Update CA insert method in webhooks.
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/webhooks/router/admission.go
Labels: approved, lgtm, size/M

#2467 cherry-pick patch to release-1.6
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/app/util.go
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/webhooks/router/admission.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/non_csi.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2453 fix potential mem leakage in nodeorder.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/XS

#2465 fix bug predicateGPUbyMemory when gpu id not continuous
  pkg/scheduler/plugins/predicates/gpu.go
Labels: approved, lgtm, size/XS

#2470 chore: remove duplicate word in comments
  docs/design/dedicated-volume.md
  docs/design/queue-resource-reservation-design.md
  pkg/scheduler/plugins/numaaware/policy/policy.go
Labels: approved, lgtm, size/XS

#2472 fix wrong comments in nodeorder plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/XS
