Repository volcano-sh/volcano, pull requests merged in 2022-01, with the labels that each got.

#1939 add qiankunli to approver and reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#1936 add hwdef to reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#1941 [numa-aware]fix concurrent map read and map write
  pkg/scheduler/plugins/numaaware/numaaware.go
Labels: approved, lgtm, size/XS

#1950 supply the process for topology result submit
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#1949 Turn down level of enqueue logs to reduce log print in each session.
  pkg/scheduler/actions/enqueue/enqueue.go
Labels: approved, lgtm, size/XS

#1918 update github CI to match k8s v1.23.0
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
Labels: approved, lgtm, size/S

#1964 update the dependency of apis to v1.5.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/volcano.sh/apis/pkg/apis/helpers/helpers.go
  vendor/volcano.sh/apis/pkg/apis/scheduling/v1beta1/labels.go
Labels: approved, lgtm, size/M

#1965 update runc to v1.0.3 to fix the security warnning
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1968 cherry pick some bugfix to release1.5
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/numaaware/numaaware.go
Labels: approved, lgtm, size/XS

#1963 Add design doc for volcano extender plugin
  docs/design/extender.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#1970 fix panic in setNodeState function when node is nil
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#1952 fix possible panic when 'SetNode' is called
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/resource_info.go
Labels: approved, lgtm, size/L

#1969 cherry pick some bugfix to release1.4
  pkg/scheduler/plugins/numaaware/numaaware.go
Labels: approved, lgtm, size/XS

#1930 add UT coverage report for v1.5.0
  docs/ut_coverage/UT_coverage_v1.5.0.html
Labels: approved, lgtm, size/XXL

#1971 fix the scheduler stuck after delete resourcequota for namespace
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/namespace_info_test.go
Labels: approved, lgtm, size/M

#1974 fix docs
  docs/design/proportional.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#1975 change ssh key file's permission to 644 when is not root mode
  pkg/controllers/job/plugins/ssh/ssh.go
Labels: approved, lgtm, ok-to-test, size/XS

#1978 [cherry-pick] fix the scheduler stuck after delete resourcequota for namespace
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/namespace_info_test.go
Labels: approved, lgtm, size/M

#1987 update some parameters to match ginkgo v2
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/XS

#1988 rm `go.mod` due to dependency security
  example/custom-plugin/go.mod
  example/custom-plugin/go.sum
Labels: approved, lgtm, size/XL

#1981 fix misuse object name issue
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/elect/elect.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reserve/reserve.go
Labels: approved, lgtm, size/M

#1989 Improve the kubernetes version supported by volcano
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#1991 add comment for unused functions in example/custom-plugin to pass the…
  example/custom-plugin/magic.go
Labels: approved, lgtm, size/XS

#1994 ignore the golang lint check for folder example
  .golangci.yml
  example/custom-plugin/magic.go
Labels: approved, lgtm, size/XS

#1985 Update documentation
  GOVERNANCE.md
  SECURITY.md
  code_of_conduct.md
  community-membership.md
  contribute.md
Labels: approved, lgtm, ok-to-test, size/M, retest-not-required-docs-only

#1984 Fix pvc cache
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/L

#1986 Fix windows build
  pkg/signals/signal_posix.go
  pkg/signals/signal_windows.go
Labels: approved, lgtm, size/XS

#1976 add RBACs for pod finalizers for controller
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#1997 Fix: All pods is existing when restart count exceed max retry
  pkg/controllers/job/job_controller_actions.go
  test/e2e/jobp/job_restart.go
  test/e2e/util/job.go
Labels: approved, lgtm, size/L
