Repository volcano-sh/volcano, pull requests merged in 2022-05, with the labels that each got.

#2175 add additionalPrinterColumns
  installer/volcano-development-arm64.yaml
Labels: approved, lgtm, size/S

#2184 add rescheduling plugin
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/rescheduling/low_node_utilization.go
  pkg/scheduler/plugins/rescheduling/node_utilization_util.go
  pkg/scheduler/plugins/rescheduling/rescheduling.go
  pkg/scheduler/plugins/rescheduling/rescheduling_util.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XL

#2204 check and fix pr2171
  .github/workflows/e2e_spark.yaml
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#2215 fix id of gpu devices never delete when number gpu decrease
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#2218 fix helm install
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/templates/prometheus.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/S

#2216 numa divided by zero bugfix
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng.go
Labels: approved, lgtm, size/S

#2222 allow privilege containers to pass the admission webhook validation by default
  cmd/webhook-manager/app/options/options.go
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
  pkg/webhooks/admission/jobs/validate/admit_job.go
Labels: approved, lgtm, size/S

#2140 fix: add jobUID into job's podgroup name ensure podgroup's unique
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_util.go
  test/e2e/jobp/job_controlled_resource.go
  test/e2e/util/job.go
Labels: approved, lgtm, size/M

#2214 fix calculate inqueue resource bug in opensession
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/S

#2230 clean up metrics of deleted objects
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/metrics/job.go
  pkg/scheduler/metrics/queue.go
Labels: approved, lgtm, size/M

#2236 sunset the reservation plugin and elect reserve actions
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/elect/elect.go
  pkg/scheduler/actions/elect/elect_test.go
  pkg/scheduler/actions/factory.go
  pkg/scheduler/actions/reserve/reserve.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/reservation/reservation.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/L

#2194 add mpi plugin
  docs/user-guide/how_to_use_mpi_plugin.md
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
  pkg/controllers/job/plugins/factory.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/mutate/mutate_job_test.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  test/e2e/jobseq/mpi_plugin.go
Labels: approved, lgtm, size/XL

#2237 [cherry-pick]add mpi plugin
  docs/user-guide/how_to_use_mpi_plugin.md
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
  pkg/controllers/job/plugins/factory.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/jobs/mutate/mutate_job_test.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi_test.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  test/e2e/jobseq/mpi_plugin.go
Labels: approved, lgtm, size/XL

#1961 Inherit annotations from upper resources to k8s podgroup.
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/M

#2239 [cherry-pick] Inherit annotations from upper resources to k8s podgroup.
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development-arm64.yaml
  installer/volcano-development.yaml
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/M

#2240 fix bug that parse strategy array error
  pkg/scheduler/plugins/rescheduling/rescheduling.go
Labels: approved, lgtm, size/XS

#2241 [cherry-pick]fix bug that parse strategy array error
  pkg/scheduler/plugins/rescheduling/rescheduling.go
Labels: approved, lgtm, size/XS

#2242 remove redundant parameter for rescheduling
  docs/design/rescheduling.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#2249 fix bug that rescheduling execution time judge error
  pkg/scheduler/plugins/rescheduling/rescheduling.go
  pkg/scheduler/plugins/rescheduling/rescheduling_util.go
Labels: approved, lgtm, size/S

#2253 fix nil pointer in VictimTasks
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/rescheduling/rescheduling.go
Labels: approved, lgtm, size/S

#2251 Allow for admission webhook ignored namespaces to prevent admission controller crash point of failure
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/util.go
Labels: approved, lgtm, size/M

#2258 [cherry-pick] Allow customization of admission webhook ignored namespaces to fix point of failure on admission controller pod crash
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/util.go
Labels: approved, lgtm, size/M

#2257 [cherry-pick] Allow customization of admission webhook ignored namespaces to fix point of failure on admission controller pod crash
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/util.go
Labels: approved, lgtm, size/M

#2225 bugfix: api-server deny empty admission response with PatchType set
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/queues/mutate/mutate_queue.go
Labels: approved, lgtm, size/M

#2231 Feat/exclude unhealthy gpu devices
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/well_known_labels.go
Labels: approved, lgtm, size/M

#2228 feat(deploy): add more deploy switches on helm
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/S

#2234 high priority task cannot preemt low priority task when queue is over…
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/S
