Repository volcano-sh/volcano, pull requests merged in 2023-09, with the labels that each got.

#3077 update volcano.sh/apis to v1.8.0
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#3088 feat:add printing of MemStats in dumpall
  pkg/scheduler/cache/dumper.go
Labels: approved, lgtm, size/XS

#3093 [cherry-pick for release-1.8]Add featuregates for volcano capabilities
  pkg/controllers/job/job_controller.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/queue/queue_controller.go
  pkg/features/volcano_features.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/capabilities/volumebinding/volume_binding_test.go
Labels: approved, lgtm, size/L

#3083 fetaure adapt k8s v1.27
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yaml
  .golangci.yml
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/bus.volcano.sh_commands.yaml
  config/crd/volcano/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/volcano/v1beta1/bus.volcano.sh_commands.yaml
  go.mod
  go.sum
  hack/verify-golangci-lint.sh
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/bus.volcano.sh_commands.yaml
  installer/volcano-development.yaml
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/capabilities/volumebinding/assume_cache.go
  pkg/scheduler/capabilities/volumebinding/binder.go
  pkg/scheduler/capabilities/volumebinding/binder_test.go
  pkg/scheduler/capabilities/volumebinding/fake_binder.go
  pkg/scheduler/capabilities/volumebinding/test_utils.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/capabilities/volumebinding/volume_binding_test.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_assignment.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/util/test_utils.go
  test/e2e/jobp/job_controlled_resource.go
Labels: approved, kind/feature, lgtm, size/XXL

#3101 [cherry-pick for release 1.8]volcano adapt k8s v1.27
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yaml
  .golangci.yml
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/bus.volcano.sh_commands.yaml
  config/crd/volcano/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/volcano/v1beta1/bus.volcano.sh_commands.yaml
  go.mod
  go.sum
  hack/verify-golangci-lint.sh
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/bus.volcano.sh_commands.yaml
  installer/volcano-development.yaml
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/capabilities/volumebinding/assume_cache.go
  pkg/scheduler/capabilities/volumebinding/binder.go
  pkg/scheduler/capabilities/volumebinding/binder_test.go
  pkg/scheduler/capabilities/volumebinding/fake_binder.go
  pkg/scheduler/capabilities/volumebinding/test_utils.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/capabilities/volumebinding/volume_binding_test.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_assignment.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/util/test_utils.go
  test/e2e/jobp/job_controlled_resource.go
Labels: approved, lgtm, size/XXL

#3064 fix: task scheduling latancy metrics is not accurate
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/factory.go
  pkg/scheduler/capabilities/volumebinding/binder.go
Labels: approved, lgtm, size/L

#3092 Add reSync task callback
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#3115 successfully scheduled events will not be reported repeatedly for podGroup resource
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
Labels: approved, lgtm, size/XS

#3117 [cherry-pick for release-1.8]successfully scheduled events will not be reported repeatedly for podGroup resource
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
Labels: approved, lgtm, size/XS

#3119 [cherry-pick for release-1.8]Add reSync task callback
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#3124 Add podGroup status to session cache, fix the bug of repeatedly sending pordGroup update request when there is no condations field.
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/XS

#3125 [cherry-pick for release-1.8]Add podGroup status to session cache, fix the bug of repeatedly sending pordGroup update request when there is no condations field.
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/XS

#3069 correct spelling errors in comments and unify the package to apis/scheduling
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/resourcequota/resourcequota.go
  pkg/webhooks/admission/jobs/plugins/mpi/mpi.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
Labels: approved, lgtm, size/M

#2871 add helm install in readme
  README.md
Labels: approved, lgtm, size/S

#3136 Update image version for release v1.8.1
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.8.1.yaml
Labels: approved, lgtm, size/M

#3134 :zap: jobflow-controller jobtemplate-controller enqueue should use struct not pointer
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
Labels: approved, lgtm, size/L

#3139 fix: the pod anti-affinity constraint fails
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/S

#3140 [cherry-pick for release-1.8]fix: the pod anti-affinity constraint fails
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/S

#3133 update version compatibility instructions for volcano v1.8 version su…
  README.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#3098 [cherry-pick for release-1.8]:feat:add printing of MemStats in dumpall
  pkg/scheduler/cache/dumper.go
Labels: approved, lgtm, size/XS
