Repository volcano-sh/volcano, pull requests merged in 2023-03, with the labels that each got.

#2714 Fix MPI example not working in IPv6
  example/integrations/mpi/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#2715 fix daily release CI
  hack/publish.sh
Labels: approved, lgtm, size/M

#2698 Add rescheduling related location logs
  pkg/scheduler/plugins/rescheduling/low_node_utilization.go
Labels: approved, lgtm, size/XS

#2696 Skip stmt when tasks is empty
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/XS

#2722 Use the latest example-mpi mirror
  docs/user-guide/how_to_use_mpi_plugin.md
  example/integrations/mpi/mpi-example.yaml
  example/task-start-dependency/mpi.yaml
  test/e2e/util/util.go
Labels: approved, lgtm, size/S

#2718 Remove escape character to fix broken grafana dashboard configuration
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#2728 Fix trunk CI grafana.yaml file parsing error
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/XS

#2726 Avoid Panic when es has no data
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
Labels: approved, lgtm, size/S

#2732 Skip early when reclaimees is empty
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, lgtm, size/XS

#2730 Update roadmap.md
  docs/community/roadmap.md
Labels: approved, size/XS, retest-not-required-docs-only

#2530 Make helm chart imagePullPolicy configurable
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, kind/feature, lgtm, size/M

#2742 Allow config hostname field name
  docs/design/usage-based-scheduling.md
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
Labels: approved, lgtm, size/M

#2743 optimize nodeorder logprint to easy find from pod;
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/M

#2746 Fix: Multiplying Elasticsearch data by 100
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
Labels: approved, lgtm, size/XS

#2756 Make errorCache configurable for predicate helper
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/S

#2757 Refactor namespace fairshare function.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/namespace_info.go
  pkg/scheduler/api/namespace_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/util_test.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/util/configmap.go
Labels: approved, lgtm, size/XL

#2752 ignore no metrics server error log;
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/enqueue/enqueue.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/actions/shuffle/shuffle.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/binpack/binpack.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/rescheduling/rescheduling.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/plugins/usage/usage.go
  pkg/webhooks/router/server.go
Labels: approved, lgtm, size/M
