Repository volcano-sh/volcano, pull requests merged in 2023-05, with the labels that each got.

#2724 Vgpu feature for volcano
  docs/user-guide/how_to_use_gpu_number.md
  docs/user-guide/how_to_use_gpu_sharing.md
  docs/user-guide/how_to_use_vgpu.md
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info_test.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/shared_device_pool.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/XXL, priority/important-soon

#2767 add label to service, name to port, to make it selectable via Service Monitors
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, ok-to-test, size/XS, priority/important-soon

#2811 fix: UT works fine and covers
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
Labels: approved, lgtm, size/L, priority/high, priority/important-soon

#2836 added nodeSelector & affinity & tolerations
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#2834 Fix: the admission-init error is reported when Volcano is installed repeatedly.
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
Labels: approved, lgtm, size/XS, priority/important-soon

#2775 fix: high priority job of two tasks cannot preempt low priority job of one task
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XS, priority/important-soon

#2704 add the impact of updating and deleting jobflow and jobtemplate. Stat…
  docs/design/jobflow/README.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only, priority/important-soon

#2751 Fix the problem that the program crashes if the gpuShare Devices is empty
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/M, priority/important-soon

#2823 Volcano automatically releases the corresponding helm charts package
  .github/workflows/release.yaml
  .github/workflows/release_chart.yaml
  Makefile
  hack/generate-charts.sh
Labels: approved, lgtm, size/L, priority/important-soon

#2827 fix: nodeinfo clone
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S, priority/important-soon

#2849 fix goimport check error
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/pod_info_test.go
Labels: approved, lgtm, size/M

#2844 fix synchronous pvc/pv bind error when volcano schedule pod with pvc
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/M

#2850 Ensure delete event is handled
  pkg/scheduler/cache/cache.go
Labels: approved, kind/bug, lgtm, size/S

#2868 add jobflow rbac in controller's sa
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#2869 abstract Bind() param to kubernetes.Interface
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/XS

#2847 modify code comment
  pkg/cli/job/util.go
  pkg/cli/util/util.go
Labels: approved, lgtm, size/XS

#2864 resolve unused variable warning
  pkg/controllers/job/job_controller_util_test.go
Labels: approved, lgtm, size/XS

#2750 Add more enable switch for predicate plugin.
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L, priority/important-soon

#2828 fix issue that sa has no permit of leases when elect leader and enable leader elect by default
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  installer/README.md
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M
