Repository volcano-sh/volcano, pull requests merged in 2023-06, with the labels that each got.

#2874 make manifests and add crd about flow.volcano.sh
  Makefile
  config/crd/bases/flow.volcano.sh_jobflows.yaml
  config/crd/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/v1beta1/flow.volcano.sh_jobflows.yaml
  config/crd/v1beta1/flow.volcano.sh_jobtemplates.yaml
Labels: approved, lgtm, size/XXL, priority/important-soon

#2776 enhancement: add keyword about allocate/pipeline/evict information in log
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/M

#2886 fix pods pending but vcjob is running
  pkg/controllers/job/job_state_test.go
  pkg/controllers/job/state/running.go
Labels: approved, lgtm, size/L

#2917 Let the make manifest work properly
  Makefile
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
  hack/update-gencode.sh
Labels: approved, lgtm, size/M

#2637 🐛 fix: fix logic when deal with resource dimension not defined in ScalarResources of r
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#2942 fix some spelling issues reported by golint
  pkg/scheduler/api/devices/nvidia/gpushare/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/framework/util.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/webhooks/admission/pods/mutate/mutate_pod_test.go
  test/e2e/jobp/job_lifecycle.go
  test/e2e/jobseq/job_error_handling.go
  test/e2e/schedulingbase/sla.go
  test/e2e/util/job.go
  test/e2e/util/util.go
  test/e2e/vcctl/command.go
Labels: approved, lgtm, ok-to-test, size/M

#2788 Add more configuration options for helm chart
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/L, priority/important-soon

#2936 Add jobflow-related content to Volcano automatic installation and deployment
  .gitignore
  Makefile
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/v1beta1/flow.volcano.sh_jobflows.yaml
  config/crd/v1beta1/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/bus.volcano.sh_commands.yaml
  config/crd/volcano/bases/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  config/crd/volcano/v1beta1/batch.volcano.sh_jobs.yaml
  config/crd/volcano/v1beta1/bus.volcano.sh_commands.yaml
  config/crd/volcano/v1beta1/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/volcano/v1beta1/scheduling.volcano.sh_podgroups.yaml
  config/crd/volcano/v1beta1/scheduling.volcano.sh_queues.yaml
  hack/generate-yaml.sh
  hack/run-e2e-kind.sh
  installer/helm/chart/jobflow/.helmignore
  installer/helm/chart/jobflow/Chart.yaml
  installer/helm/chart/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/jobflow/crd/v1
  installer/helm/chart/jobflow/templates/NOTES.txt
  installer/helm/chart/jobflow/templates/_helpers.tpl
  installer/helm/chart/jobflow/templates/flow_v1alpha1_jobflows.yaml
  installer/helm/chart/jobflow/templates/flow_v1alpha1_jobtemplates.yaml
  installer/helm/chart/volcano/Chart.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#2888 install ginkgo bin if not exist
  hack/lib/install.sh
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S

#2929 fix PodToplogySpread plugin violates maxSkew
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, lgtm, size/M
