Repository volcano-sh/volcano, pull requests merged in 2023-10, with the labels that each got.

#3146 feat: dynamically change klog level through socket
  go.mod
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/scheduler.go
  pkg/util/socket.go
Labels: approved, lgtm, size/L

#3111 add dynamic conf design docs
  docs/design/dynamic-conf.md
  docs/design/images/dynamic-conf.jpg
Labels: approved, lgtm, size/M

#2955 backfill add score process
  pkg/scheduler/actions/backfill/backfill.go
Labels: approved, lgtm, size/M

#2990 Doc: design doc for pdb plugin
  docs/design/images/pdb-workflow.png
  docs/design/pdb-plugin.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only, lifecycle/stale

#3113 Feature: add pdb plugin
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/pdb/pdb.go
  pkg/scheduler/plugins/pdb/pdb_test.go
Labels: approved, lgtm, size/L

#3165 update volcano.sh/apis version
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#3166 [cherry-pick for release-1.8]update volcano.sh/apis version
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M
