Repository volcano-sh/volcano, pull requests merged in 2023-04, with the labels that each got.

#2769 Upgrade the ubuntu version to fix the problem that CI cannot run
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
Labels: approved, lgtm, size/S

#2737 pod admission mutate patch affinity
  docs/design/multi-scheduler.md
  pkg/webhooks/admission/pods/mutate/mutate_pod.go
  pkg/webhooks/admission/pods/mutate/mutate_pod_test.go
  pkg/webhooks/config/config.go
Labels: approved, lgtm, ok-to-test, size/L

#2784 Ensure deletion of pods is handled
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#2786 Modify binpack score on nodes with releasing resources.
  pkg/scheduler/plugins/binpack/binpack.go
Labels: approved, lgtm, size/S

#2780 Use cases for blocking CI probabilistic failures
  test/e2e/jobseq/pytorch_plugin.go
Labels: approved, lgtm, priority/high, size/XS

#2773 Change the error message.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/api/unschedule_info.go
Labels: approved, lgtm, size/L, priority/important-soon

#2801 fix: lint error
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/devices/nvidia/gpushare/device_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/dumper.go
  pkg/scheduler/metrics/source/metrics_client.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/scheduler/plugins/drf/drf.go
Labels: approved, lgtm, size/M, priority/high

#2770 Added version compatibility instructions for Volcano and K8s
  README.md
Labels: approved, lgtm, size/S

#2808 verify-golangci-lint fails to run in CI, code merging is not allowed
  hack/verify-golangci-lint.sh
Labels: approved, lgtm, size/S
