Repository volcano-sh/volcano, pull requests merged in 2023-11, with the labels that each got.

#3167 fix scheduler logs & provide metrics for vgpu
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
Labels: approved, lgtm, size/M

#3179 Update the default value of parameter worker-threads-for-podgroup to 5
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
Labels: approved, lgtm, size/XS

#3180 [cherry-pick for release-1.8]Update the default value of parameter worker-threads-for-podgroup to 5
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
Labels: approved, lgtm, size/XS

#3176 Obtains the actual load data of a node from the custom metrics API.
  docs/design/usage-based-scheduling.md
  go.mod
  go.sum
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/metrics/source/metrics_client.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch_test.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/scheduler/metrics/source/metrics_client_prometheus_adapt.go
  pkg/scheduler/plugins/usage/usage.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XXL

#3181 [cherry pick for release-1.8]Obtains the actual load data of a node from the custom metrics API
  docs/design/usage-based-scheduling.md
  go.mod
  go.sum
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/metrics/source/metrics_client.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch_test.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/scheduler/metrics/source/metrics_client_prometheus_adapt.go
  pkg/scheduler/plugins/usage/usage.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XXL

#3172 Fix multi volcano scheduler doc error
  docs/design/multi-volcano-schedulers.md
  go.mod
Labels: approved, lgtm, size/XS

#3184 chore: remove refs to deprecated io/ioutil
  example/extender/extender.go
  pkg/cli/job/run_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
Labels: approved, lgtm, ok-to-test, size/S

#3192 CVE-2023-2253: Bump github.com/docker/distribution to v2.8.2+incompatible
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#3200 Fix a typo in comments.
  pkg/controllers/jobtemplate/jobtemplate_controller.go
Labels: approved, lgtm, size/XS

#3164 [cherry-pick for release-1.8]backfill add score process
  pkg/scheduler/actions/backfill/backfill.go
Labels: approved, lgtm, size/M

#3197 fix job `CRD metadata.annotations: Too long` error
  Makefile
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#3076 Add task index
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#3122 fix: fix simple annotation error
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/XS

#3147 Add Kubernetes 1.26 to compatibility table
  README.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#3128 [cherry-pick for release-1.8]fix: task scheduling latancy metrics is not accurate
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/factory.go
  pkg/scheduler/capabilities/volumebinding/binder.go
Labels: approved, lgtm, size/L

#2950 doc: add wechat contact in readme
  README.md
Labels: approved, lgtm

#2848 sed syntax is compatible with linux and darwin systems
  hack/generate-charts.sh
Labels: approved, lgtm, size/S, priority/important-soon

#3206 fix queue update validation err when status.allocated empty
  pkg/controllers/queue/queue_controller_action.go
Labels: approved, lgtm, size/XS

#3168 Update README.md
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3183 Update device-sharing.md
  docs/design/device-sharing.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3188 support preemption when the number of pods of a node reaches the upper limit
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/predicates/proportional_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/XL

#3211 support preemption when the number of attachment volumes of a node reaches the upper limit
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/L

#3212 [cherry-pick for release-1.8]support preemption when the number of attachment volumes of a node reaches the upper limit
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/L

#3213 Delete duplicate logs generated by the predicate_helper method
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/XS

#3208 support preempting task with bound status
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/helpers.go
Labels: approved, lgtm, size/S

#3209 [cherry-pick for release-1.8]support preempting task with bound status
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/helpers.go
Labels: approved, lgtm, size/S

#3214 [cherry-pick for release-1.8]Delete duplicate logs generated by the predicate_helper method
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/XS

#3202 [cherry-pick for release-1.8]support preemption when the number of pods of a node reaches the upper limit
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/predicates/proportional_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/util/test_utils.go
  tatusq
Labels: approved, lgtm, size/XXL

#3219 queue realcapability change to min dimension of queue capability and …
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/XS

#3228 Avoid repeatedly creating links to obtain node metrics
  pkg/scheduler/metrics/source/metrics_client.go
  pkg/scheduler/metrics/source/metrics_client_prometheus_adapt.go
Labels: approved, lgtm, size/M

#3223 skip 'pods' resource when checking if the Resource is empty
  pkg/scheduler/api/resource_info.go
Labels: approved, lgtm, size/S

#3224 [cherry-pick for release-1.8]skip 'pods' resource when checking if the Resource is empty
  pkg/scheduler/api/resource_info.go
Labels: approved, lgtm, size/S

#3229 [cherry-pick for release-1.8]Avoid repeatedly creating links to obtain node metrics
  pkg/scheduler/metrics/source/metrics_client.go
  pkg/scheduler/metrics/source/metrics_client_prometheus_adapt.go
Labels: approved, lgtm, size/M

#3221 [cherry-pick for release-1.8] fix: allocated field in queue status is calcutated error
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/XS

#3232 update parameter BestEffort of taskInfo after changing parameter InitResreq
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/XS

#3231 [cherry-pick for release-1.8]update parameter BestEffort of taskInfo after changing parameter InitResreq
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/XS

#3233 Add Monokaix as reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3236 update MAINTAINERS
  MAINTAINERS.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only
