Repository volcano-sh/volcano, pull requests merged in 2023-12, with the labels that each got.

#3241 fix NPE issue#3141
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/S

#3243 add archlitchi as reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#2866 fix: events miss when there is a pod bind failed
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/factory.go
Labels: approved, lgtm, size/M

#3262 fix grafana dashboard format err
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/XS

#3265 [cherry-pick for release-1.8]fix grafana dashboard format err
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/XS

#3267 [cherry-pick for release-1.8]fix job `CRD metadata.annotations: Too long` error
  Makefile
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/v1beta1/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/v1beta1/batch.volcano.sh_jobs.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#3090 improve list job of jobflow
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, size/M, lifecycle/stale

#3276 fix e2e description error
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/XS

#3273 fix: json marsh error for unsupport type: func()
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#3282 [cherry-pick for release-1.8]fix: json marsh error for unsupport type: func()
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#3279 Chart: add configurable expressions for webhooks namespace selector
  installer/README.md
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/M

#3284 fix wrong pods field format output of queue status
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XS

#3272 fix k8s.io/dynamic-resource-allocation go mod not found err
  go.mod
Labels: approved, lgtm, size/XS

#3285 add ignored csi provisioner when compute csi resources
  cmd/scheduler/app/options/options.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M
