Repository volcano-sh/volcano, pull requests merged in 2023-08, with the labels that each got.

#3008 Fix panic issue with job taskMinAvailable clone
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#3016 Optimize the jobflow architecture design diagram
  docs/design/images/jobflow-1.png
  docs/design/images/jobflow-2.jpg
  docs/design/images/jobflow-2.png
  docs/design/images/jobflow-3.png
  docs/design/images/jobflow-4.png
  docs/design/jobflow/README.md
Labels: approved, lgtm, size/S

#3025 [cherry-pick for release-1.8] Optimize the jobflow architecture design diagram
  docs/design/images/jobflow-1.png
  docs/design/images/jobflow-2.jpg
  docs/design/images/jobflow-2.png
  docs/design/images/jobflow-3.png
  docs/design/images/jobflow-4.png
  docs/design/jobflow/README.md
Labels: approved, lgtm, size/S

#3017 [cherry-pick for release-1.8] use one command of helm install to do smooth upgrade
  .gitignore
  hack/generate-yaml.sh
  hack/local-up-volcano.sh
  hack/run-e2e-kind.sh
  installer/helm/chart/jobflow/Chart.yaml
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/charts/jobflow/.helmignore
  installer/helm/chart/volcano/charts/jobflow/Chart.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/v1
  installer/helm/chart/volcano/charts/jobflow/templates/NOTES.txt
  installer/helm/chart/volcano/charts/jobflow/templates/_helpers.tpl
  installer/helm/chart/volcano/charts/jobflow/templates/flow_v1alpha1_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/templates/flow_v1alpha1_jobtemplates.yaml
Labels: approved, lgtm, size/M

#3028 Fix the problem that resource info ut test fails probabilistically
  pkg/scheduler/api/resource_info_test.go
Labels: approved, lgtm, size/XS

#3021 fix: extender.PredicateResponse has no field or method ErrorMessage
  example/extender/extender.go
Labels: approved, lgtm, size/XS

#3026 Add wangyang0616 as reviewer
  OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3027 cherry-pick important bugfix to release-1.8 branch for v1.8.x
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  docs/design/Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
  pkg/controllers/framework/interface.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/L

#2815 Pods are preferentially scheduled to machines that meet the current session resources
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/M, priority/important-soon

#3035 [cherry-pick for release-1.8] Pods are preferentially scheduled to machines that meet the current session resources
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/M

#2802 Hotfix: keep updating task's min available number same as creating podgroup
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
Labels: approved, lgtm, size/S

#2927 fix: set leaderelection's ctx that can sense signal in controller
  cmd/controller-manager/app/server.go
Labels: approved, lgtm, size/XS

#3036 update image to v1.8.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.8.0.yaml
Labels: approved, lgtm, size/XL

#3054 Add nodelockEnable parameters default to false
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
Labels: approved, lgtm, size/S

#3011 make adpative percentage nodes to find be consistent with kube-scheduler
  cmd/scheduler/app/options/options.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, lgtm, size/M

#3060 [cherry-pick for release-1.8] fix nodelock issue when using gang-scheduling
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
Labels: approved, lgtm, size/S

#3059 update slack channel link and add Join slack link
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3062 Jobinfo enhancement
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/S

#3065 add docs about un-enqueueable reason
  docs/design/podgroup-condition-reason.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#3051 fix: schedule message burst with nodes number increasion
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/M, priority/critical-urgent

#3070 Fix the conflict between preemption and antiAffinity
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/framework/util.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/plugins/predicates/proportional_test.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/L

#3081 The status of a pod group is updated only when the pod group changes.
  pkg/scheduler/framework/job_updater.go
Labels: approved, lgtm, size/XS

#3082 [cherry-pick for release-1.8] msg information optimization; preemption logic optimization
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/util.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/plugins/predicates/proportional_test.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/L
