Repository volcano-sh/volcano, pull requests merged in 2024-05, with the labels that each got.

#3452 add ut for plugins: overcommit, sla, conformance, resourcequota
  pkg/scheduler/plugins/conformance/conformance_test.go
  pkg/scheduler/plugins/overcommit/overcommit_test.go
  pkg/scheduler/plugins/resourcequota/resourcequota_test.go
  pkg/scheduler/plugins/sla/sla_test.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/test_utils.go
Labels: approved, kind/feature, lgtm, size/L

#3409 improve: add rwlock to fakeBinder and fakeEvictor
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/plugins/nodegroup/nodegroup_test.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/test_utils.go
  pkg/scheduler/util/test_utils_test.go
Labels: approved, lgtm, size/L, priority/critical-urgent

#3443 fix nil pointer panic when evict
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#3449 Remove list secret in controller ClusterRole
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XS

#3448 fix: queue realcapability change to min dimension of queue capability and cluster realcapability
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/proportion/proportion_test.go
Labels: approved, lgtm, size/M

#3389 sort victims in reclaim action
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/framework/session_plugins.go
Labels: approved, lgtm, size/L

#3438 export the logs of Volcano components when the e2e test workflow fails
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S, priority/important-soon

#3450 fix: FilterNode err miss predicateStatus
  pkg/scheduler/api/shared_device_pool.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
Labels: approved, lgtm, size/M

#3321 update go to 1.21
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/licenses_lint.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
Labels: approved, lgtm, size/M

#3325 fix Data Race leading to panic in Scheduler (and use more efficient strings comparison)
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/shared_device_pool.go
  pkg/scheduler/api/shared_device_pool_test.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/L

#3283 Capacity plugin implement
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  config/crd/volcano/v1beta1/scheduling.volcano.sh_queues.yaml
  docs/user-guide/how_to_use_capacity_plugin.md
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/util/test_utils.go
  pkg/scheduler/util_test.go
  test/e2e/schedulingaction/reclaim.go
  test/e2e/stress/queue.go
  test/e2e/util/queue.go
  test/e2e/util/util.go
Labels: approved, lgtm, size/XL

#3458 ignore PredicateFn err info for preempt & reclaim scheduler plugin
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/conf/scheduler_conf.go
Labels: approved, lgtm, size/S

#3436 add image registry for helm
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, ok-to-test, size/S

#3404 Upgrade the version of kind and controller-gen to adapt k8s version upgrade
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_vcctl.yaml
  Makefile
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/bus.volcano.sh_commands.yaml
  config/crd/volcano/bases/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  hack/generate-yaml.sh
  hack/lib/install.sh
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/bases/nodeinfo.volcano.sh_numatopologies.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#3463 Fix queue metrics when there are no jobs in it
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/M

#3467 fix testcommonstruct
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, lgtm, size/L

#3471 Fix device share plugins npe & update devicescore
  docs/user-guide/how_to_use_gpu_number.md
  docs/user-guide/how_to_use_gpu_sharing.md
  pkg/scheduler/api/devices/nvidia/gpushare/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/shared_device_pool.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
  pkg/scheduler/plugins/deviceshare/deviceshare_test.go
Labels: approved, lgtm, size/L

#3453 add ut for enqueue action
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/enqueue/enqueue_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, kind/feature, lgtm, size/L

#3475 Bump image to v1.9.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.9.0.yaml
Labels: approved, lgtm, size/M

#3425 Add options: worker-threads-for-gc
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
  pkg/controllers/garbagecollector/garbagecollector.go
Labels: approved, lgtm, size/S

#3447 fix: log when outputting preempt error
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, lgtm, size/M

#3454 bugfix and code refactor around klog
  cmd/cli/vcancel/main.go
  cmd/cli/vcctl.go
  cmd/cli/vjobs/main.go
  cmd/cli/vqueues/main.go
  cmd/cli/vresume/main.go
  cmd/cli/vsub/main.go
  cmd/cli/vsuspend/main.go
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  cmd/webhook-manager/main.go
  test/e2e/vcctl/vcctl.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/L

#3459 Added documentation on what must be done to adapt volcano to the k8s version upgrade.
  docs/design/adapt-k8s-todo.md
  docs/design/images/adapt-k8s-todo.png
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#3462 fix job clone miss PgUID
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XS

#3457 test: add priority plugin UTs
  pkg/scheduler/plugins/priority/priority_test.go
Labels: approved, lgtm, size/L

#3423 feat: added question to issue template
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#3354 Feature/allow helm config overrides
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#3480 fix bug3476
  hack/lib/install.sh
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S

#3498 Update NominatedNodeName for pipelined task
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/M

#3501 [cherry-pick for release-1.9] Update NominatedNodeName for pipelined task
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/M

#3494 refactor vcctl
  cmd/cli/job.go
  cmd/cli/queue.go
  cmd/cli/vcancel/main.go
  cmd/cli/vcctl.go
  cmd/cli/vjobs/main.go
  cmd/cli/vqueues/main.go
  cmd/cli/vresume/main.go
  cmd/cli/vsub/main.go
  cmd/cli/vsuspend/main.go
  pkg/cli/job/common.go
  pkg/cli/job/delete.go
  pkg/cli/job/delete_test.go
  pkg/cli/job/list.go
  pkg/cli/job/list_test.go
  pkg/cli/job/resume.go
  pkg/cli/job/resume_test.go
  pkg/cli/job/run.go
  pkg/cli/job/run_test.go
  pkg/cli/job/suspend.go
  pkg/cli/job/suspend_test.go
  pkg/cli/job/util.go
  pkg/cli/job/util_test.go
  pkg/cli/job/view.go
  pkg/cli/job/view_test.go
  pkg/cli/queue/common.go
  pkg/cli/queue/create.go
  pkg/cli/queue/delete.go
  pkg/cli/queue/delete_test.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/queue/operate.go
  pkg/cli/queue/operate_test.go
  pkg/cli/queue/queue_test.go
  pkg/cli/queue/util.go
  pkg/cli/util/util.go
  pkg/cli/vcancel/cancel.go
  pkg/cli/vcancel/cancel_test.go
  pkg/cli/vjobs/view.go
  pkg/cli/vqueues/get.go
  pkg/cli/vresume/resume.go
  pkg/cli/vresume/resume_test.go
  pkg/cli/vsub/run.go
  pkg/cli/vsuspend/suspend.go
  pkg/cli/vsuspend/suspend_test.go
Labels: approved, kind/cleanup, lgtm, size/XL

#3479 add lock before read Jobs map #3478
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, ok-to-test, size/XS

#3483 Mark --lock-object-namespace as deprecated and throw a warning when it is used
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
Labels: approved, lgtm, size/XS
