Repository volcano-sh/volcano, pull requests merged in 2024-06, with the labels that each got.

#3497 optimizate controllers with one sharedInformerFactory
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
  pkg/controllers/garbagecollector/garbagecollector.go
  pkg/controllers/garbagecollector/garbagecollector_test.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_handler_test.go
  pkg/controllers/job/job_controller_plugins_test.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_test.go
  pkg/controllers/queue/queue_controller.go
  pkg/controllers/queue/queue_controller_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3493 Replace reflect.DeepEqual by equality.Semantic.DeepEqual
  cmd/controller-manager/app/options/options_test.go
  cmd/scheduler/app/options/options_test.go
  docs/ut_coverage/UT_coverage_v1.4.0.html
  docs/ut_coverage/UT_coverage_v1.5.0.html
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch_test.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/podgroup/pg_controller_test.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/helpers/helpers_test.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/capabilities/volumebinding/binder_test.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/cdp/cdp_test.go
  pkg/scheduler/plugins/conformance/conformance_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_best_effort_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_none_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_restricted_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_single_numa_node_test.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng_test.go
  pkg/scheduler/plugins/overcommit/overcommit_test.go
  pkg/scheduler/plugins/pdb/pdb_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/resourcequota/resourcequota_test.go
  pkg/scheduler/plugins/sla/sla_test.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/scheduler_helper_test.go
  pkg/scheduler/util_test.go
  pkg/webhooks/admission/jobs/validate/util_test.go
  pkg/webhooks/admission/pods/mutate/mutate_pod_test.go
  pkg/webhooks/admission/queues/mutate/mutate_queue_test.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, lgtm, size/L

#3506 Update unit-test && e2e to run on Mac
  Makefile
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
  hack/lib/install.sh
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/M

#3057 fix calculations of podgroup min resource
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/job_controller_util_test.go
  pkg/scheduler/api/job_info.go
Labels: approved, lgtm, size/XL

#3504 Add pre-install&pre-upgrade hook for admission-init job
  hack/generate-yaml.sh
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L

#3500 feat: add jobflow name for vcjob label and annotation when creating
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
Labels: approved, kind/feature, lgtm, size/M

#3508 feat: add vcctl jobtemplate
  cmd/cli/jobtemplate.go
  cmd/cli/vcctl.go
  pkg/cli/jobtemplate/create.go
  pkg/cli/jobtemplate/delete.go
  pkg/cli/jobtemplate/describe.go
  pkg/cli/jobtemplate/get.go
  pkg/cli/jobtemplate/jobtemplate_test.go
  pkg/cli/jobtemplate/list.go
  test/e2e/vcctl/vcctl.go
Labels: approved, kind/feature, lgtm, size/XXL

#3511 Add common labels for chart objects
  installer/README.md
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/templates/prometheus.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/L

#3529 typo: fix typo in sla plugin
  pkg/scheduler/plugins/sla/sla.go
Labels: approved, lgtm, size/XS

#3514 Avoid unnecessary API update and re-enqueue action
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#3515 put back the queue to priority queue after job's resource allocating finished
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/L

#3541 Added logic to avoid unnecessary API update
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/S

#3547 update pod status when bind error
  pkg/scheduler/api/unschedule_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/S

#3550 update pod status when bind error
  pkg/scheduler/api/unschedule_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/S
