Repository volcano-sh/volcano, pull requests merged in 2024-04, with the labels that each got.

#3377 fix comment
  pkg/controllers/job/job_controller.go
  pkg/controllers/queue/queue_controller.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/XS

#2809 fix(app): Introduced flag to specify leader election behavious
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/main.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  pkg/util/util.go
Labels: approved, lgtm, size/L

#3356 [cherry-pick for release-1.9]fix jobflow CRD metadata.annotations: Too long error
  Makefile
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  config/crd/volcano/v1beta1/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/v1beta1/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/XXL

#3383 fix: fix log print
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/scheduler/framework/interface.go
Labels: approved, lgtm, size/XS

#3380 fix(test/e2e): fix e2e test by retry update queuestatus
  test/e2e/util/queue.go
Labels: approved, lgtm, size/M

#3349 fix: exec job validate after init ssn.Tiers
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/M

#3346 refact preempt ut
  pkg/scheduler/actions/preempt/preempt_test.go
Labels: approved, lgtm, size/L

#3341 fix issue 2957: predicate plugin ut didn't really run due to kubeclient init failed
  pkg/scheduler/plugins/predicates/main_test.go
  pkg/scheduler/plugins/predicates/predicates_test.go
Labels: approved, lgtm, size/L

#3342 refact drf plugin ut
  pkg/scheduler/plugins/drf/hdrf_test.go
Labels: approved, lgtm, size/L

#3394 Revert "fix: exec job validate after init ssn.Tiers."
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/M

#3391 fix panic when the futureIdle resources are calculated to be negative
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#3393 [cherry-pick for release-1.9]fix panic when the futureIdle resources are calculated to be negative
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#3368 registe nodegroup plugin to factory
  pkg/scheduler/plugins/factory.go
Labels: approved, lgtm, size/XS

#3379 record error if task's jobID is null when deleting task
  pkg/scheduler/cache/event_handlers.go
Labels: approved, kind/cleanup, lgtm, size/S

#3390 fix err handle and wrap AddToScheme method with Must
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/schema/schema.go
Labels: approved, kind/cleanup, lgtm, size/S

#3365 refact shuffle action ut
  pkg/scheduler/actions/shuffle/shuffle_test.go
Labels: approved, lgtm, size/L

#3397 Update vgpu document
  docs/user-guide/how_to_use_vgpu.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#3353 refact binpack ut with common uthelpler framework
  pkg/scheduler/plugins/binpack/binpack_test.go
Labels: approved, lgtm, size/L

#3364 refact reclaim ut with common test framework
  pkg/scheduler/actions/reclaim/reclaim_test.go
Labels: approved, lgtm, size/L

#3398 sort tasks by UID when task index parsing fails
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
Labels: approved, lgtm, size/M

#3345 Refactor allocate action's UTs
  pkg/scheduler/actions/allocate/allocate_test.go
Labels: approved, lgtm, size/L

#3402 register nodegroup plugin to factory
  pkg/scheduler/plugins/factory.go
Labels: approved, lgtm, size/XS

#3400 test: add some ut test in plugins numaaware policy
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/plugins/binpack/binpack_test.go
  pkg/scheduler/plugins/drf/hdrf_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_best_effort_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_none_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_restricted_test.go
  pkg/scheduler/plugins/numaaware/policy/policy_single_numa_node_test.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/uthelper/interface.go
Labels: approved, lgtm, size/M

#3408 fix failed ut: reclaimee pod is randomly evicted
  pkg/scheduler/actions/reclaim/reclaim_test.go
Labels: approved, lgtm, size/XS, priority/critical-urgent, priority/important-soon

#3417 fix: ut reporting no permisson denied panic on macOS
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#3419 unify the namespace used in the e2e test script to volcano-system
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/S, priority/important-soon

#3434 fix errTask channel memory leak
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/M

#3435 fix errTask channel memory leak
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, lgtm, size/M

#3442 fix nil pointer panic when evict
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/XS

#3406 docs: fix custom plugin build docs
  example/custom-plugin/README.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only
