Repository volcano-sh/volcano, pull requests merged in 2024-12, with the labels that each got.

#3857 Delete current incorrect benchmark testing results
  benchmark/README.md
  benchmark/README_CN.md
  benchmark/img/grafana_catalog.png
  benchmark/img/k8s_scheduler_workload.png
  benchmark/img/predicate_cfg.png
  benchmark/img/res/g1-mini.png
  benchmark/img/res/g1.png
  benchmark/img/res/g1_aff.png
  benchmark/img/res/g1_nocache_aff.png
  benchmark/img/res/g1_rm_nodeorder_binpack.png
  benchmark/img/res/g2-mini.png
  benchmark/img/res/g2.png
  benchmark/img/res/g2_aff.png
  benchmark/img/res/g2_nocache_aff.png
  benchmark/img/res/g3-mini.png
  benchmark/img/res/g3.png
  benchmark/img/res/g3_aff.png
  benchmark/img/res/g3_nocache_aff.png
  benchmark/img/res/g4.png
  benchmark/img/res/g5.png
  benchmark/img/res/g6.png
  benchmark/img/res/g6_cpu.png
  benchmark/img/res/g6_mem.png
  benchmark/img/res/g6_v_cpu.png
  benchmark/img/res/g6_v_mem.png
  benchmark/img/scheduler_cfg.png
  benchmark/img/volcano_scheduler_workload.png
Labels: approved, lgtm, ok-to-test, size/XL, retest-not-required-docs-only

#3859 [cherry-pick for release 1.10] Fix predicate return unexpected result
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/predicates_test.go
Labels: approved, lgtm, size/L

#3863 Supports rollback when allocate callback function fails
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, ok-to-test, size/L

#3843 Update gen-admission-secret.sh
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
Labels: approved, lgtm, ok-to-test, size/XS

#3864 [cherry-pick for release-1.10]Supports rollback when allocate callback function fails
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/L

#3886 fix: nodegroup return nil 3880
  pkg/scheduler/plugins/nodegroup/nodegroup.go
Labels: approved, lgtm, ok-to-test, size/XS

#3837 Fix: Fix a bug when the hostname label of a node does not match the node name, pods bound to a PV with nodeAffinity using the hostname may be scheduled to the wrong node or experience scheduling failures.
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/nodeinfo.volcano.sh_numatopologies.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/nodeinfo.volcano.sh_numatopologies.yaml
  installer/volcano-development.yaml
  pkg/scheduler/capabilities/volumebinding/binder.go
  pkg/scheduler/capabilities/volumebinding/binder_test.go
  pkg/scheduler/capabilities/volumebinding/fake_binder.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/capabilities/volumebinding/volume_binding_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#3879 Remove duplicated codes
  pkg/cli/job/resume.go
  pkg/cli/job/run.go
  pkg/cli/job/suspend.go
  pkg/cli/job/util.go
  pkg/cli/job/util_test.go
  pkg/cli/job/view.go
Labels: approved, lgtm, ok-to-test, size/L

#3882 Update owners: add archlitchi to approver in scheduler plugins
  pkg/scheduler/plugins/OWNERS
Labels: approved, lgtm, ok-to-test, size/XS, retest-not-required-docs-only

#3807 fix: mark PodGroup completed when pod fails
  pkg/scheduler/api/helpers.go
  pkg/scheduler/framework/session.go
  test/e2e/schedulingbase/job_scheduling.go
  test/e2e/util/deployment.go
Labels: approved, lgtm, ok-to-test, size/M

#3905 Fix flaky ut of jobFlow cli
  pkg/cli/jobflow/jobflow_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#3891 fix: configmgr need wait for all processed avoid tests data race
  pkg/agent/config/source/fake_source.go
Labels: approved, lgtm, ok-to-test, size/XS

#3850 add network-topology-aware design doc
  docs/design/Network Topology Aware Scheduling.md
  docs/design/images/network-topology-aware/network-topology-example1.png
  docs/design/images/network-topology-aware/network-topology-example2.png
  docs/design/images/network-topology-aware/network-topology-implementation-01.png
  docs/design/images/network-topology-aware/network-topology-implementation-02.png
  docs/design/images/network-topology-aware/network-topology-usecase1.png
  docs/design/images/network-topology-aware/network-topology-usecase2.png
  docs/design/images/network-topology-aware/network-topology-usecase3.png
  docs/design/images/network-topology-aware/nework-topology-generation.png
Labels: approved, lgtm, ok-to-test, size/XL, retest-not-required-docs-only

#3874 Network topology scheduling implementations of volcano scheduler
  Makefile
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/volcano/bases/topology.volcano.sh_hypernodes.yaml
  go.mod
  go.sum
  hack/generate-yaml.sh
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/crd/bases/topology.volcano.sh_hypernodes.yaml
  installer/helm/chart/volcano/templates/topology_v1alpha1_hypernodes.yaml
  installer/volcano-development.yaml
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/dumper.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/priority_queue.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/XXL

#3908 chore: Fix minor comment issues
  pkg/scheduler/actions/allocate/allocate.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
Labels: approved, lgtm, ok-to-test, size/XS

#3933 chore: use Infof for slice taskinfo instead of InfoS log less details
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, ok-to-test, size/XS

#3924 fix NPU issue on vc-scheduler
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
Labels: approved, lgtm, ok-to-test, size/XS

#3927 export logs via workflow
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  hack/run-e2e-kind.sh
Labels: approved, lgtm, ok-to-test, size/L

#3942 Add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, ok-to-test, size/M, retest-not-required-docs-only

#3941 vs-scheduler: use max function to simplify code of capacity plugin
  pkg/scheduler/plugins/capacity/capacity.go
Labels: approved, lgtm, ok-to-test, size/XS
