Repository volcano-sh/volcano, pull requests merged in 2024-08, with the labels that each got.

#3566 upgrade kube-state-metrics image versio to v2.0.0-beta from v1.9.7
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/XS

#3543 feat: add vcctl jobflow command
  cmd/cli/jobflow.go
  cmd/cli/vcctl.go
  pkg/cli/jobflow/create.go
  pkg/cli/jobflow/delete.go
  pkg/cli/jobflow/describe.go
  pkg/cli/jobflow/get.go
  pkg/cli/jobflow/jobflow_test.go
  pkg/cli/jobflow/list.go
  test/e2e/vcctl/vcctl.go
Labels: approved, kind/feature, lgtm, size/XXL

#3598 use create pod result for statistic of job status
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#3643 add hwdef as approver
  OWNERS
  pkg/scheduler/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3524 feat: add vcctl job list queueName filter
  pkg/cli/job/list.go
  pkg/cli/job/list_test.go
  pkg/cli/jobtemplate/jobtemplate_test.go
  pkg/cli/util/util.go
  test/e2e/vcctl/vcctl.go
Labels: approved, kind/feature, lgtm, size/L

#3586 aggregate err when checking options
  cmd/controller-manager/app/options/options.go
Labels: approved, kind/feature, lgtm, size/S

#3622 Optimize bind event update logic
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/M

#3522 resource compare support only consider the requested resource item
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion_test.go
Labels: approved, lgtm, size/L

#3548 metrics: use milliseconds instead of microseconds as the time unit for scheduling latency
  pkg/scheduler/metrics/metrics.go
Labels: approved, lgtm, ok-to-test, size/S

#3553 Fix predicate return
  example/extender/extender.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/util.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
  pkg/scheduler/plugins/extender/argument.go
  pkg/scheduler/plugins/extender/extender.go
  pkg/scheduler/plugins/nodegroup/nodegroup.go
  pkg/scheduler/plugins/nodegroup/nodegroup_test.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/predicates/proportional.go
  pkg/scheduler/plugins/tdm/tdm.go
  pkg/scheduler/plugins/tdm/tdm_test.go
  pkg/scheduler/plugins/usage/usage.go
  pkg/scheduler/plugins/usage/usage_test.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/XL

#3583 fix: remove cache sync repeatedly
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, ok-to-test, size/XS

#3663 feat: add oidc's auth provider
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  cmd/webhook-manager/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#3655 Added the scorecard github action and its badge
  .github/workflows/scorecards.yml
  README.md
Labels: approved, lgtm, size/M

#3530 feat: add vcctl pod list
  cmd/cli/job.go
  cmd/cli/jobflow.go
  cmd/cli/jobtemplate.go
  cmd/cli/pod.go
  cmd/cli/vcctl.go
  pkg/cli/jobflow/create.go
  pkg/cli/jobflow/delete.go
  pkg/cli/jobflow/describe.go
  pkg/cli/jobflow/get.go
  pkg/cli/jobflow/jobflow_test.go
  pkg/cli/jobflow/list.go
  pkg/cli/jobtemplate/create.go
  pkg/cli/jobtemplate/delete.go
  pkg/cli/jobtemplate/describe.go
  pkg/cli/jobtemplate/get.go
  pkg/cli/jobtemplate/jobtemplate_test.go
  pkg/cli/jobtemplate/list.go
  pkg/cli/pod/pod.go
  pkg/cli/pod/pod_test.go
  test/e2e/vcctl/vcctl.go
Labels: approved, kind/feature, lgtm, size/XXL

#3672 fix pg controller create redundancy podGroup when schedulerName isn't matched
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3653 Update volcano-admission secret when it already exists
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, size/M

#3656 Expose volcano components (controller, scheduler, etc.) log level control to the helm chat values
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#3664 Improve capacity plugin: Only compare requested dimension resources when reclaim
  docs/user-guide/how_to_use_capacity_plugin.md
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, lgtm, size/M

#3678 add kind/question label for question issue
  .github/ISSUE_TEMPLATE/question.yaml
Labels: approved, lgtm, size/XS

#3675 [cherry-pick for release-1.9]fix pg controller create redundancy podGroup when schedulerName isn't matched
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3676 [cherry-pick for release-1.10]fix pg controller create redundancy podGroup when schedulerName isn't matched
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3680 fix always update pod nominatedNodeName when pod is pipelined
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill_test.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/M

#3682 [cherry-pick for release-1.10] fix always update pod nominatedNodeName when pod is pipelined
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill_test.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/statement.go
Labels: approved, lgtm, size/M
