Repository volcano-sh/volcano, pull requests merged in 2024-11, with the labels that each got.

#3801 chore: remove benchmark unuse g1\_aff.png
  benchmark/img/res/g1\_aff.png
Labels: approved, lgtm, ok-to-test, size/XS, retest-not-required-docs-only

#3803 fix the type error in dashboard's name
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/volcano-monitoring-latest.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3817 fix ci and add event logging to help debug ci
  .github/workflows/e2e_spark.yaml
  test/e2e/util/job.go
  test/e2e/util/util.go
Labels: approved, lgtm, ok-to-test, size/M

#3821 remove useless report file
  docs/ut_coverage/UT_coverage_v1.4.0.html
  docs/ut_coverage/UT_coverage_v1.5.0.html
Labels: approved, lgtm, ok-to-test, size/XXL

#3816 Add install dashboard guide
  README.md
Labels: approved, lgtm, ok-to-test, size/XS, retest-not-required-docs-only

#3811 fix untranslated sections.
  benchmark/README.md
Labels: approved, lgtm, ok-to-test, size/S, retest-not-required-docs-only

#3751 feature: Add podgroups statistics
  pkg/cli/podgroup/podgroup.go
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/controllers/metrics/queue.go
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_handler.go
  pkg/controllers/queue/queue_controller_test.go
  pkg/controllers/queue/queue_controller_util.go
  pkg/scheduler/metrics/queue.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
  test/e2e/jobseq/queue_job_status.go
  test/e2e/schedulingaction/reclaim.go
  test/e2e/util/podgroup.go
Labels: approved, lgtm, ok-to-test, size/XL

#3808 chore: Replace deprecation `ioutil` fucntions and add depguard rules in `.golangci.yml`
  .golangci.yml
  pkg/metriccollect/local/memory.go
Labels: approved, lgtm, ok-to-test, size/XS

#3849 Fix flaky ut
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
Labels: approved, lgtm, ok-to-test, size/M, priority/critical-urgent
