Repository volcano-sh/volcano, pull requests merged in 2024-09, with the labels that each got.

#3690 vulnerability fix
  go.mod
Labels: approved, lgtm, size/XS

#3683 fix: preempt in same job should also skip pod which is not preemptable
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, lgtm, size/XS

#3602 Add queue priority design doc
  docs/design/queue-priority.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#3538 improve unschedule message
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, size/M

#3546 delete reservation plugin doc
  docs/design/job-resource-reservation-design.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3707 Chart: remove duplicate label field
  installer/helm/chart/volcano/templates/admission-init.yaml
Labels: approved, lgtm, size/XS

#3692 vcctl(jobtemplate): fix describe miss APIVersion and Kind bug, and remove ManagedFields
  pkg/cli/jobflow/describe.go
  pkg/cli/jobtemplate/describe.go
  pkg/cli/jobtemplate/jobtemplate_test.go
Labels: approved, kind/bug, lgtm, size/M

#3700 Add queue priority
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/L

#3708 fix: vcctl unit test ci failed
  pkg/cli/jobflow/jobflow_test.go
  pkg/cli/pod/pod_test.go
Labels: approved, kind/bug, lgtm, size/S

#3706 Support sidecar scheduling
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/L

#3581 Proposal for Support of Pod Scheduling Readiness
  docs/design/pod-scheduling-readiness.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#2945 [Ready]docs about job's min resource
  docs/design/min-avaiable-member-resource.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only

#3704 feat: Add securityContext support at container level in helm chart templates
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/S

#3658 Pod Scheduling Readiness
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/webhooks/admission/jobs/validate/admit_job.go
  test/e2e/schedulingaction/allocate.go
  test/e2e/schedulingaction/enqueue.go
  test/e2e/schedulingaction/preempt.go
  test/e2e/util/deployment.go
  test/e2e/util/job.go
Labels: approved, lgtm, size/L

#3724 [cherry-pick for release-1.10] fix: not remove podgroup uid will cause topology annotation to be useless
  .github/workflows/e2e_spark.yaml
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/plugins/task-topology/topology_test.go
  test/e2e/schedulingaction/allocate.go
Labels: approved, lgtm, size/L

#3728 [cherry-pick for 1.10] fix: volumeZone and podTopologySpread don't work if nodeVolumeLimits is enabled
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/XS

#3727 fix: volumeZone and podTopologySpread don't work if nodeVolumeLimits is enabled
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, lgtm, size/XS

#3696 enquable and allocatable compare resource with the required dimensions
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, lgtm, size/M

#3649 don't enable error cache if task role spec is empty
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/conf/constants.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/M

#3732 [cherry-pick for release-1.10] enquable and allocatable compare resource with the required dimensions and add testcaes
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, lgtm, size/M

#3733 [cherry-pick for release-1.10]don't enable error cache if task role spec is empty
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/conf/constants.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/M

#3721 Bump image to v1.10.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/config/volcano-scheduler.conf
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.10.0.yaml
Labels: approved, lgtm, size/M

#3740 Remove hardcoded nodeSelector for kubestatematrics
  installer/README.md
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/XS

#3719 controllers: fix miscalculation of RunningDuration when killing job
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, ok-to-test, size/S

#3588 optimize the webhook manager
  pkg/webhooks/router/admission.go
Labels: approved, lgtm, size/XS

#3747 Specify the fields using the key Duration
  cmd/controller-manager/app/options/options_test.go
  cmd/scheduler/app/options/options_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#3746 fix job controller reports duplicate warnings
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
Labels: approved, lgtm, size/L

#3717 fix: nil pointer when set node other resources
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/XS

#3742 controllers: fix queue controller syncQueue bug
  pkg/controllers/queue/queue_controller_action.go
  pkg/controllers/queue/queue_controller_test.go
Labels: approved, lgtm, size/L

#3718 docs: fix README broken URL
  README.md
Labels: approved, lgtm, ok-to-test, size/XS, retest-not-required-docs-only

#3755 [cherry-pick for release-1.10]fix job controller reports duplicate warnings
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_actions_test.go
Labels: approved, lgtm, size/L

#3741 feat: allow configuration of ipFamilyPolicy
  installer/README.md
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/grafana.yaml
  installer/helm/chart/volcano/templates/kubestatemetrics.yaml
  installer/helm/chart/volcano/templates/prometheus.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/M
