Repository volcano-sh/volcano, pull requests merged in 2024-01, with the labels that each got.

#3286 [cherry-pick for release-1.8]add ignored csi provisioner when compute csi resources
  cmd/scheduler/app/options/options.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/predicates/predicates_test.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M

#3287 [cherry-pick for release1.8]fix wrong pods field format output of queue status
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, lgtm, size/XS

#3144 Fix the problem of slow job deletion
  pkg/controllers/cache/cache.go
  pkg/scheduler/cache/cache.go
Labels: approved, lgtm, size/S

#3266 [cherry-pick for release-1.8]fix queue update validation err when status.allocated empty
  pkg/controllers/queue/queue_controller_action.go
Labels: approved, lgtm, size/XS

#3290 Bump image to v1.8.2
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.8.2.yaml
  tatusq
Labels: approved, lgtm, size/L

#3292 Refactor Execute() of Allocate Method into Multiple Subfunctions for Enhanced Readability and Maintainability
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, lgtm, size/L

#3294 Enhancements to Comments and Code Adjustments in pkg/scheduler
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/M

#3277 Capacity scheduling design doc
  docs/design/capacity-scheduling.md
  docs/design/images/capacity-scheduling/queue-deserved.png
  docs/design/images/capacity-scheduling/queue-guarantee.png
  docs/design/images/capacity-scheduling/queue1-capability.png
  docs/design/images/capacity-scheduling/queue1-use-all.png
  docs/design/images/capacity-scheduling/queue2-reclaim-exclude-guarantee.png
  docs/design/images/capacity-scheduling/queue2-reclaim.png
  docs/design/img.png
Labels: approved, lgtm, size/L, retest-not-required-docs-only

#3132 add nodegroup plugin
  docs/design/images/nodegroup_plugin-predict-1.png
  docs/design/images/nodegroup_plugin-score-1.png
  docs/design/node-group.md
  docs/user-guide/how_to_use_nodegroup_plugin.md
  pkg/scheduler/plugins/nodegroup/nodegroup.go
  pkg/scheduler/plugins/nodegroup/nodegroup_test.go
Labels: approved, lgtm, size/XL

#3230 Fix preempt: when skipping continue on preempting, the overused judgement didn't consider the current task's resource
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/actions/shuffle/shuffle_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/XL

#3304 Fix ineffective volcano scheduler deployment string filter
  test/e2e/util/configmap.go
Labels: approved, lgtm, size/XS

#3109 fix update-development-yaml will remove more webhooks than disabled one
  installer/helm/chart/volcano/templates/webhooks.yaml
Labels: approved, lgtm, size/S

#3039 enhancement: copy cluster total resource from ssn, instead of summing up them again
  pkg/scheduler/plugins/overcommit/overcommit.go
Labels: approved, lgtm, size/XS

#3274 [feat] Add rest client metrics
  cmd/scheduler/app/server.go
Labels: approved, lgtm, size/S

#3306 change private function 'unmarshalSchedulerConf' to public function 'UnmarshalSchedulerConf'
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
Labels: approved, lgtm, size/S

#3142 Dockerfile: go mod cache
  Makefile
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
Labels: approved, lgtm, size/S
