Repository volcano-sh/volcano, pull requests merged in 2024-07, with the labels that each got.

#3545 Shrink permissions of vc scheduler & controller
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/S

#3556 Volcano adapts to the k8s v1.30
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yaml
  .gitignore
  Makefile
  README.md
  config/crd/jobflow/bases/flow.volcano.sh_jobflows.yaml
  config/crd/jobflow/bases/flow.volcano.sh_jobtemplates.yaml
  config/crd/volcano/bases/batch.volcano.sh_jobs.yaml
  config/crd/volcano/bases/bus.volcano.sh_commands.yaml
  config/crd/volcano/bases/nodeinfo.volcano.sh_numatopologies.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
  hack/lib/install.sh
  installer/dockerfile/controller-manager/Dockerfile
  installer/dockerfile/scheduler/Dockerfile
  installer/dockerfile/webhook-manager/Dockerfile
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobflows.yaml
  installer/helm/chart/volcano/charts/jobflow/crd/bases/flow.volcano.sh_jobtemplates.yaml
  installer/helm/chart/volcano/crd/bases/batch.volcano.sh_jobs.yaml
  installer/helm/chart/volcano/crd/bases/bus.volcano.sh_commands.yaml
  installer/helm/chart/volcano/crd/bases/nodeinfo.volcano.sh_numatopologies.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  licenses/k8s.io/kubernetes/LICENSES/third_party/forked/vishhstress/LICENSE
  licenses/k8s.io/kubernetes/third_party/forked/vishhstress/LICENSE
  pkg/scheduler/capabilities/volumebinding/assume_cache.go
  pkg/scheduler/capabilities/volumebinding/binder.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/capabilities/volumebinding/volume_binding_test.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/util/test_utils.go
  test/e2e/schedulingaction/reclaim.go
Labels: approved, lgtm, size/XXL

#3561 Fix podgroup not created
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3572 [cherry-pick for release-1.9]Fix podgroup not created
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3574 [cherry-pick for release-1.10]Fix podgroup not created
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, size/S

#3570 Update Kubernetes compatibility
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3569 Update Kubernetes compatibility
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3571 Add feature gates flag
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/main.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/main.go
Labels: approved, lgtm, size/M

#3540 reduce function calling
  pkg/controllers/job/job_controller_util.go
Labels: approved, kind/cleanup, lgtm, size/XS

#3532 Delete unused variables.
  pkg/controllers/job/job_controller_actions.go
Labels: approved, lgtm, size/XS

#3486 add controller gate flag
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  cmd/controller-manager/app/server_test.go
  cmd/controller-manager/main.go
Labels: approved, kind/feature, lgtm, size/L

#3544 Added pod annotation with job RetryCount
  go.mod
  go.sum
  pkg/controllers/job/job_controller_util.go
Labels: approved, lgtm, size/XS

#3580 optimization verion command
  cmd/controller-manager/main.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  cmd/webhook-manager/main.go
Labels: approved, lgtm, size/S

#3557 Remove invalid parameter IgnoredNamespaces
  cmd/webhook-manager/app/options/options.go
Labels: approved, lgtm, ok-to-test, size/S

#3585 fix: use built-in slices package from go1.21 for simplify code
  pkg/controllers/podgroup/pg_controller.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/util.go
  pkg/util/util.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
Labels: approved, lgtm, ok-to-test, size/S

#3432 filter out those nodes which are UnschedulableAndUnresolvable when preempting
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/api/unschedule_info.go
  pkg/scheduler/api/unschedule_info_test.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins_test.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/XL

#3430 improve: continue allocating if remain tasks is more than job's minMember
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/util/predicate_helper.go
Labels: approved, lgtm, size/L

#3599 handle job not found case
  pkg/controllers/garbagecollector/garbagecollector.go
Labels: approved, size/XS

#3610 fix lint error: third part imports should put after system package
  pkg/controllers/garbagecollector/garbagecollector.go
Labels: approved, lgtm, size/XS

#3609 Add container log size limit config for kind node
  hack/e2e-kind-config.yaml
Labels: approved, lgtm, size/XS

#3412 add ut and refactor for pkg/scheduler/plugins/util/k8s package
  pkg/scheduler/plugins/util/k8s/snapshot_test.go
  pkg/scheduler/plugins/util/nodelock/nodelock.go
  pkg/scheduler/plugins/util/nodelock/nodelock_test.go
Labels: approved, lgtm, size/L

#3584 add enhancement vcctl features docs
  docs/design/command-line-enhancement.md
Labels: approved, lgtm, size/M, kind/docs, retest-not-required-docs-only

#3625 Fix spark ci error
  .github/workflows/e2e_spark.yaml
Labels: approved, lgtm, size/XS

#3608 test ci
  .github/workflows/e2e_spark.yaml
Labels: size/XS, do-not-merge/hold

#3626 Improve ginkgo e2e case of preempt
  test/e2e/schedulingaction/preempt.go
Labels: approved, lgtm, size/M

#3615 Add config field to the ControllerOption
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
Labels: approved, lgtm, size/XS

#3628 [cherry-pick for release-1.10] Optimize bind event update logic
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/util/test_utils.go
Labels: approved, lgtm, size/M

#3627 [cherry-pick for release-1.10]Add config field to the ControllerOption
  cmd/controller-manager/app/server.go
  pkg/controllers/framework/interface.go
Labels: approved, lgtm, size/XS

#3639 Remove enqueue action in preempt e2e case
  test/e2e/schedulingaction/preempt.go
Labels: approved, lgtm, size/M

#3607 Add Monokaix as approver
  OWNERS
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3620 Update volcano-vgpu monitoring system
  docs/user-guide/how_to_use_gpu_number.md
  docs/user-guide/how_to_use_gpu_sharing.md
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
Labels: approved, lgtm, size/L

#3632 Add lowang-bh as approver
  OWNERS
  pkg/controllers/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#3644 update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
Labels: approved, lgtm, size/L
