Repository volcano-sh/volcano, pull requests merged in 2025-09, with the labels that each got.

#4590 Add permissions for managing namespaces in admission rules
  installer/helm/chart/volcano/templates/admission.yaml
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#4587 Minor docs changes
  .gitignore
  contribute.md
  docs/design/capacity-scheduling.md
  docs/development/development.md
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, lgtm, ok-to-test, size/S

#4588 use node.futureidle instead when pod has nominatedNodeName
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, kind/bug, lgtm, size/XS

#4345 network topology aware hard mode support hypernode binpack
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/hyper_node_info.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/network-topology-aware/network_topology_aware.go
  pkg/scheduler/plugins/network-topology-aware/network_topology_aware_test.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, lgtm, size/XL

#4608 Sync kube-scheduler: Improve CSILimits plugin accuracy by using VolumeAttachments
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/cache/cache.go
Labels: approved, kind/bug, lgtm, size/XS

#4610 🐛 fix mpi job plugin panic when mpi job only has master task
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
Labels: approved, lgtm, size/L

#4620 [Cherry-pick v1.11] fix mpi job plugin panic when mpi job only has master task
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
Labels: approved, lgtm, size/S

#4621 [Cherry-pick v1.10] fix mpi job plugin panic when mpi job only has master task
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
Labels: approved, lgtm, size/S

#4615 Fix an issue in vc-scheduler about vgpu device memory allocated
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
Labels: approved, lgtm, size/XS

#4544 feat: add detail msg for pg event
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/overcommit/overcommit.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, lgtm, size/L

#4619 [Cherry-pick v1.12] fix mpi job plugin panic when mpi job only has master task
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi_test.go
Labels: approved, lgtm, size/S

#4622 Cleanup: update MAINTAINERS.md with latest content location
  MAINTAINERS.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#4630 Expose more helm config for agent
  installer/build/volcano-agent/install.sh
  installer/helm/chart/volcano/templates/agent.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
Labels: approved, kind/feature, lgtm, size/M, area/colocation

#4581 feat: add ray plugin for job
  docs/design/distributed-framework-plugins.md
  docs/design/images/ray_plugin_cluster_architecture.png
  docs/images/ray-dashboard.png
  docs/user-guide/how_to_use_ray_plugin.md
  example/integrations/ray/ray-example.yaml
  pkg/controllers/job/plugins/distributed-framework/ray/ray.go
  pkg/controllers/job/plugins/distributed-framework/ray/ray_test.go
  pkg/controllers/job/plugins/factory.go
  pkg/webhooks/admission/jobs/mutate/mutate_job.go
  test/e2e/jobseq/ray_plugin.go
  test/e2e/util/util.go
Labels: approved, lgtm, ok-to-test, size/XL

#4642 Free up disk space
  hack/lib/install.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#4633 Fix panic on volcano-vgpu when allocating multiple containers in a pod
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/hamicore.go
Labels: approved, kind/bug, lgtm, size/XS

#4519 Fix bump version script
  hack/bump-version.sh
Labels: approved, kind/bug, lgtm, size/XS

#4654 Revise the user documentation for hypernode auto discovery
  docs/user-guide/how_to_use_hypernode_auto_discovery.md
  installer/helm/chart/volcano/values.yaml
  pkg/controllers/hypernode/api/example.yaml
Labels: approved, lgtm, size/M, kind/documentation
