Repository volcano-sh/volcano, pull requests merged in 2025-02, with the labels that each got.

#2778 Extend the default timeout for stale
  .github/stale.yml
Labels: approved, lgtm, ok-to-test, size/S

#3906 Dynamic-mig for volcano-vgpu design
  docs/design/dynamic-mig.md
  docs/design/images/dynamic-mig-example.png
  docs/design/images/volcano-dynamic-mig-procedure.png
  docs/design/images/volcano-dynamic-mig-structure.png
Labels: approved, lgtm, ok-to-test, size/L, retest-not-required-docs-only, kind/documentation

#4002 Add JesseStutler as reviewer
  OWNERS
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#4008 Fix typos
  cmd/network-qos/tools/options/options.go
  cmd/scheduler/app/options/options.go
  pkg/agent/config/configmgr.go
  pkg/agent/config/source/configmap_source.go
  pkg/agent/features/feature_gate.go
Labels: approved, kind/cleanup, lgtm, size/S

#4016 [DOCS] improve readme, visit to should be visit
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only, kind/documentation, area/documentation

#4012 skip the jobs that have no tasks during the close session step in gang plugin
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, lgtm, ok-to-test, area/scheduling, size/XS, kind/flake

#3988 add helm values scheduler_plugins_dir
  installer/README.md
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, kind/feature, lgtm, ok-to-test, size/XS, area/dependency

#3994 Fix: fix an issue where the wrong action name could not be ignored
  pkg/scheduler/util.go
Labels: approved, kind/bug, lgtm, ok-to-test, area/scheduling, size/XS

#4013 scheduler: correct mismatched error message
  pkg/scheduler/cache/cache.go
Labels: approved, kind/cleanup, lgtm, size/XS

#4036 [docs]: fix passive tone
  pkg/scheduler/plugins/task-topology/topology.go
  pkg/scheduler/plugins/task-topology/topology_test.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/XS

#4035 Fix typos
  cmd/controller-manager/app/options/options.go
  cmd/webhook-manager/app/options/options.go
  example/integrations/argo/README.md
  hack/generate-yaml.sh
  hack/sync-scheduler-code.sh
  hack/update-vendor-licenses.sh
  pkg/agent/events/probes/nodemonitor/node_monitor.go
  pkg/controllers/job/plugins/distributed-framework/tensorflow/tensorflow.go
  pkg/networkqos/networkqos.go
  pkg/networkqos/utils/utils.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/numa_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/numaaware/numaaware.go
  pkg/scheduler/plugins/numaaware/provider/cpumanager/cpu_mng.go
  pkg/scheduler/plugins/util/k8s/framework.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/test_utils_test.go
  pkg/webhooks/admission/jobs/validate/admit_job_test.go
  pkg/webhooks/admission/pods/mutate/factory.go
  test/e2e/schedulingaction/allocate.go
Labels: approved, kind/cleanup, lgtm, size/L

#3938 Update uninstall-volcano.sh
  benchmark/sh/uninstall-volcano.sh
Labels: approved, lgtm, ok-to-test, size/XS, area/test, area/deploy

#4024 typo: change `configure` to `configuration`
  pkg/cli/util/util.go
Labels: approved, kind/cleanup, lgtm, size/XS

#4029 fix: the problem that the pending tasks cannot be scheduled during the backfill action
  pkg/scheduler/actions/backfill/backfill.go
Labels: approved, kind/bug, lgtm, ok-to-test, area/scheduling, size/XS
