Repository volcano-sh/volcano, pull requests merged in 2025-04, with the labels that each got.

#4155 [Cherry-pick v1.11] Replace queue status update by using ApplyStatus method & Bump image to v1.11.1
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.11.1.yaml
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/M

#4154 Update release-1.10 api version to v1.10.1 and Bump image to v1.10.1
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.10.1.yaml
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, ok-to-test, size/M

#4160 fix: remove lessPartly condition in reclaimable fn from capacity and …
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/S

#4178 [Cherry-pick v1.11] fix: remove lessPartly condition in reclaimable fn from capacity and proportion plugins
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, kind/bug, lgtm, size/S

#4171 [Security] Remove the execute permission for some files, chmod to 644
  docs/design/jobflow/README.md
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobflow/state/factory.go
  pkg/controllers/jobflow/state/failed.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/jobflow/state/succeed.go
  pkg/controllers/jobflow/state/terminating.go
  pkg/controllers/jobtemplate/constant.go
  pkg/controllers/jobtemplate/jobTemplate_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_util.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/namespace.go
Labels: approved, lgtm, size/XS

#4177 Fix typos
  docs/design/Network Topology Aware Scheduling.md
  docs/design/capacity-scheduling.md
  docs/design/colocation/Overview.md
  docs/design/deploy-multi-volcano-schedulers-without-using-selector.md
  docs/design/tdm-plugin.md
  docs/user-guide/how_to_use_job_policy.md
  test/e2e/jobp/admission.go
  test/e2e/schedulingaction/allocate.go
  test/e2e/schedulingaction/enqueue.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/M

#4179 fix: panic when total guarantee of child queue exceeds capacity of parent
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, lgtm, ok-to-test, size/S

#4153 [Cherry-pick network-topology] Replace queue status update by using ApplyStatus method & Bump image to v1.11.0-network-topology-preview.2
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  config/crd/volcano/bases/topology.volcano.sh_hypernodes.yaml
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/crd/bases/topology.volcano.sh_hypernodes.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.11.0-network-topology-preview.2.yaml
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, kind/bug, lgtm, size/L

#4180 chore: rename VolcanoNamespace -> VolcanoSubSystemName in metrics
  pkg/controllers/job/state/metrics.go
  pkg/controllers/metrics/queue.go
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
  pkg/scheduler/metrics/job.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/metrics/namespace.go
  pkg/scheduler/metrics/queue.go
Labels: approved, kind/cleanup, lgtm, size/L

#4183 fix: allocated in queue status should include allocated tasks, not only running tasks
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, ok-to-test, size/M

#3953 volcano-devices unified config
  pkg/scheduler/api/devices/config/config.go
  pkg/scheduler/api/devices/config/config_test.go
  pkg/scheduler/api/devices/config/vgpu.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info_test.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/devices/util.go
Labels: approved, kind/feature, lgtm, size/XL, area/scheduling

#4181 feat/vcctl: add parent column to queue list cmd
  pkg/cli/queue/get.go
  pkg/cli/queue/list.go
  pkg/cli/queue/queue_test.go
Labels: approved, lgtm, ok-to-test, size/M

#4184 Add v1.11 compatibility matrix
  README.md
Labels: approved, kind/cleanup, lgtm, size/S, retest-not-required-docs-only

#4185 fix scorecards ci err
  .github/workflows/scorecards.yml
Labels: approved, kind/bug, lgtm, size/XS

#4186 Add topLevel permission for CI
  .github/workflows/e2e_parallel_jobs.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#4173 [Security] Add a switch to control whether enable pprof in scheduler
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, size/M

#4194 Update ubuntu base image
  .github/workflows/e2e_spark.yaml
  .github/workflows/licenses_lint.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#4197 Update ubuntu base image
  .github/workflows/e2e_spark.yaml
  .github/workflows/licenses_lint.yaml
Labels: approved, kind/cleanup, lgtm, size/XS

#3603 fix(controller): add statefulset gc for podgroup.
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
Labels: approved, lgtm, ok-to-test, size/M

#4201 Fix: remove controller-manager metrics that should not be introduced
  pkg/controllers/job/state/metrics.go
  pkg/controllers/metrics/queue.go
  pkg/controllers/util/const.go
Labels: approved, lgtm, size/M

#4192 Update readme
  README.md
  example/kubecon-2019-china/horovod-sample/lm-horovod-tf-mnist-v0.5.yaml
Labels: approved, lgtm, size/M, kind/documentation

#4068 HyperNode supports select Nodes By labels
  pkg/scheduler/api/hyper_node_info.go
  pkg/scheduler/api/hyper_node_info_test.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/api/test_utils_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/event_handlers_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#4202 [Cherry-pick v1.11] Fix: remove controller-manager metrics that should not be introduced
  .github/workflows/e2e_spark.yaml
  .github/workflows/licenses_lint.yaml
  pkg/controllers/job/state/metrics.go
  pkg/controllers/metrics/queue.go
  pkg/controllers/util/const.go
Labels: approved, kind/bug, lgtm, size/M

#4206 Add wangyang0616 as approver
  OWNERS
  pkg/controllers/OWNERS
  pkg/scheduler/OWNERS
  pkg/webhooks/OWNERS
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#4149 Fix bug for vgpu type check
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils_test.go
Labels: approved, lgtm, size/L

#4000 use replicas when initializing pg minResources
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/podgroup/pg_controller.go
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
  pkg/controllers/util/util.go
  pkg/controllers/util/util_test.go
Labels: approved, lgtm, ok-to-test, size/L

#4212 adjust e2e log level
  hack/run-e2e-kind.sh
Labels: approved, lgtm, size/XS, area/test

#4208 [Security] Add http server timeout
  cmd/agent/app/app.go
  cmd/controller-manager/app/server.go
  cmd/scheduler/app/server.go
  cmd/webhook-manager/app/server.go
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/volcano-development.yaml
  pkg/util/socket.go
Labels: approved, lgtm, size/M, area/security

#4211 [Security] Add warning msg when TLS verification disabled
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
Labels: approved, lgtm, size/XS, area/security

#4223 Fix ci err caused by slow change of scheduling configMap
  test/e2e/schedulingaction/enqueue.go
  test/e2e/schedulingaction/preempt.go
  test/e2e/schedulingaction/reclaim.go
  test/e2e/util/configmap.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/L, priority/important-soon, area/test

#4224 [Cherry-pick v1.11] fix security related issues
  cmd/agent/app/app.go
  cmd/controller-manager/app/server.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  docs/design/jobflow/README.md
  go.mod
  go.sum
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobflow/state/factory.go
  pkg/controllers/jobflow/state/failed.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/jobflow/state/succeed.go
  pkg/controllers/jobflow/state/terminating.go
  pkg/controllers/jobtemplate/constant.go
  pkg/controllers/jobtemplate/jobTemplate_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_util.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/util/socket.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/namespace.go
Labels: approved, lgtm, size/M, area/security

#4225 [Cherry-pick network topology] fix security related issues
  cmd/agent/app/app.go
  cmd/controller-manager/app/server.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  docs/design/jobflow/README.md
  go.mod
  go.sum
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobflow/state/factory.go
  pkg/controllers/jobflow/state/failed.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/jobflow/state/succeed.go
  pkg/controllers/jobflow/state/terminating.go
  pkg/controllers/jobtemplate/constant.go
  pkg/controllers/jobtemplate/jobTemplate_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_util.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/util/socket.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/namespace.go
Labels: approved, lgtm, size/M, area/security

#4226 [Cherry-pick v1.10] fix security related issues
  .github/workflows/e2e_spark.yaml
  .github/workflows/licenses_lint.yaml
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  docs/design/jobflow/README.md
  go.mod
  go.sum
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobflow/state/factory.go
  pkg/controllers/jobflow/state/failed.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/jobflow/state/succeed.go
  pkg/controllers/jobflow/state/terminating.go
  pkg/controllers/jobtemplate/constant.go
  pkg/controllers/jobtemplate/jobTemplate_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_util.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/util/socket.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/namespace.go
Labels: approved, lgtm, size/M, area/security

#4215 Clear multiple generated hash values
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, size/S

#4230 Cherry-pick some bug fix into release-1.9 and bump image to v1.9.1
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
  Makefile
  Makefile.def
  README.md
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.9.1.yaml
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, size/L

#4236 [Cherry-pick v1.9] fix security related issues
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/server.go
  cmd/scheduler/main.go
  cmd/webhook-manager/app/server.go
  docs/design/jobflow/README.md
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  pkg/controllers/jobflow/constant.go
  pkg/controllers/jobflow/jobflow_controller.go
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/jobflow_controller_handler.go
  pkg/controllers/jobflow/jobflow_controller_handler_test.go
  pkg/controllers/jobflow/jobflow_controller_util.go
  pkg/controllers/jobflow/jobflow_controller_util_test.go
  pkg/controllers/jobflow/state/factory.go
  pkg/controllers/jobflow/state/failed.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/jobflow/state/succeed.go
  pkg/controllers/jobflow/state/terminating.go
  pkg/controllers/jobtemplate/constant.go
  pkg/controllers/jobtemplate/jobTemplate_controller_util_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action.go
  pkg/controllers/jobtemplate/jobtemplate_controller_action_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler.go
  pkg/controllers/jobtemplate/jobtemplate_controller_handler_test.go
  pkg/controllers/jobtemplate/jobtemplate_controller_util.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_prometheus.go
  pkg/util/socket.go
  pkg/webhooks/admission/pods/mutate/annotation.go
  pkg/webhooks/admission/pods/mutate/factory.go
  pkg/webhooks/admission/pods/mutate/namespace.go
Labels: approved, lgtm, size/M, area/security

#4213 Add NetworkTopology plugin score doc
  docs/design/Network Topology Aware Scheduling.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only

#4240 Filter useless logs in binpack
  pkg/scheduler/plugins/binpack/binpack.go
Labels: approved, kind/feature, lgtm, size/XS

#4207 [Security] Add security context configuration
  installer/build/volcano-agent/install.sh
  installer/dockerfile/agent/Dockerfile
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/agent.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L, area/security

#4203 render scripts using TAG env
  .github/workflows/release.yaml
  hack/check-generated-yaml.sh
  hack/generate-charts.sh
Labels: approved, kind/cleanup, lgtm, size/S

#4245 [Cherry-pick 1.11] Add security context configuration
  installer/build/volcano-agent/install.sh
  installer/dockerfile/agent/Dockerfile
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/agent.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L, area/security

#4246 [Cherry-pick 1.10] Add security context configuration
  installer/dockerfile/webhook-manager/gen-admission-secret.sh
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L, area/security

#4250 [Cherry-pick network-topology] Add security context configuration
  installer/build/volcano-agent/install.sh
  installer/dockerfile/agent/Dockerfile
  installer/helm/chart/volcano/templates/admission-init.yaml
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/agent.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L, area/security

#4249 [Cherry-pick 1.9] Add security context configuration
  installer/helm/chart/volcano/templates/admission.yaml
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/L, area/security

#4251 Revert github action bump
  .github/workflows/code_verify.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/fossa.yml
  .github/workflows/licenses_lint.yaml
  .github/workflows/release.yaml
  .github/workflows/release_chart.yaml
  .github/workflows/scorecards.yml
Labels: approved, kind/bug, lgtm, size/M

#4254 [Cherry-pick 1.9] Add http response body size limit
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch_test.go
  pkg/scheduler/plugins/extender/extender.go
  pkg/scheduler/plugins/extender/extender_test.go
Labels: approved, lgtm, size/L, area/security

#4255 [Cherry-pick network-topology] Add http response body size limit
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch_test.go
  pkg/scheduler/plugins/extender/extender.go
  pkg/scheduler/plugins/extender/extender_test.go
Labels: approved, lgtm, size/L, area/security

#4252 [Cherry-pick 1.11] Add http response body size limit
  pkg/scheduler/metrics/source/metrics_client_elasticsearch.go
  pkg/scheduler/metrics/source/metrics_client_elasticsearch_test.go
  pkg/scheduler/plugins/extender/extender.go
  pkg/scheduler/plugins/extender/extender_test.go
Labels: approved, lgtm, size/L, area/security
