Repository volcano-sh/volcano, pull requests merged in 2025-08, with the labels that each got.

#4494 Automated cherry pick of #4487: Add missing capacity metrics in hierarchical queues
  pkg/scheduler/plugins/capacity/capacity.go
Labels: approved, lgtm, size/XS

#4483 Fix volume binding e2e testing
  Makefile
  go.mod
  hack/run-e2e-kind.sh
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  licenses/github.com/kylelemons/godebug/LICENSE
  pkg/scheduler/plugins/predicates/predicates.go
  test/e2e/schedulingbase/volume_binding.go
  test/e2e/util/scheduler_injector.go
  test/e2e/util/util.go
Labels: approved, kind/bug, lgtm, size/L

#4500 fix #4499: scheduler panic caused by pod using gpu-number scheduled by volcano with old version (e.g v1.7)
  pkg/scheduler/api/node_info.go
Labels: approved, lgtm, size/S

#4517 fix: update podGroup when statefulSet update
  pkg/controllers/podgroup/pg_controller_handler.go
  pkg/controllers/podgroup/pg_controller_test.go
Labels: approved, lgtm, size/XL

#4518 Automated: Bump version to v1.12.2
  .release-version
  README.md
  go.mod
  go.sum
  hack/bump-version.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M

#4531 Fix dra flaky test: use `exec env` instead logs
  test/e2e/dra/builder.go
  test/e2e/dra/test.go
Labels: approved, lgtm, size/M, kind/flake

#4524 ✨ add hcclrank job plugin
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
  pkg/controllers/job/plugins/distributed-framework/hcclrank/hcclrank.go
  pkg/controllers/job/plugins/distributed-framework/hcclrank/hcclrank_test.go
  pkg/controllers/job/plugins/factory.go
Labels: approved, lgtm, size/XXL

#4553 [Cherry-pick v1.9] add hcclrank job plugin
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/helpers/helpers_test.go
  pkg/controllers/job/plugins/distributed-framework/hcclrank/hcclrank.go
  pkg/controllers/job/plugins/distributed-framework/hcclrank/hcclrank_test.go
  pkg/controllers/job/plugins/factory.go
Labels: approved, lgtm, size/XXL
