Repository volcano-sh/volcano, pull requests merged in 2025-03, with the labels that each got.

#4034 update document for volcano-vgpu feature
  docs/user-guide/how_to_use_volcano_vgpu.md
Labels: approved, lgtm, size/L, retest-not-required-docs-only, kind/documentation

#4053 Improve overused messaging
  pkg/scheduler/plugins/capacity/capacity.go
Labels: approved, kind/bug, kind/feature, kind/cleanup, lgtm, ok-to-test, area/scheduling, area/controllers, area/cli, size/XS, area/dependency, kind/failing-test, kind/flake, kind/documentation, area/test, area/webhooks, area/deploy, area/documentation, area/performance

#4045 Refactor: move DeviceName const into its own package
  docs/design/device-sharing.md
  pkg/scheduler/api/devices/nvidia/gpushare/type.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/shared_device_pool.go
Labels: approved, kind/cleanup, lgtm, size/M

#4059 change to action cache v4
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S, area/deploy

#4009 scheduler: fix a bug where the job NodesFitErrors field is not updated when ssn.Allocate failed
  pkg/scheduler/actions/backfill/backfill.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#4058 refactor: Optimized code
  pkg/controllers/job/plugins/svc/svc.go
Labels: approved, kind/cleanup, lgtm, area/controllers, size/XS

#4020 fix typo in comment
  pkg/webhooks/admission/jobs/validate/admit_job.go
Labels: approved, kind/cleanup, lgtm, size/XS

#4060 Fix inaccurate statements in node-lock.md
  docs/design/node-lock.md
Labels: approved, kind/cleanup, lgtm, size/XS, retest-not-required-docs-only

#4033 [bugfix]fix creating a hierarchical sub-queue will be rejected
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/L, area/webhooks

#4018 [docs] improve the `development.md` document
  docs/development/development.md
Labels: approved, lgtm, size/M, retest-not-required-docs-only, kind/documentation, area/documentation

#4042 fix custom plugin doc and build script
  Makefile
  Makefile.def
  example/custom-plugin/Dockerfile
  example/custom-plugin/README.md
Labels: approved, kind/bug, kind/cleanup, lgtm, ok-to-test, size/M, area/scheduling, kind/documentation, area/deploy

#4075 [cherry-pick]change to action cache v4
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/S

#4074 [cherry-pick]change to action cache v4
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/S

#4067 delete label tempalte
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/cleanup, lgtm, size/S, retest-not-required-docs-only

#4080 [cherry-pick]fix creating a hierarchical sub-queue will be rejected
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, lgtm, ok-to-test, size/L

#4082 Optimized code
  pkg/controllers/cache/cache.go
  pkg/controllers/job/job_controller_resync.go
Labels: approved, lgtm, ok-to-test, size/S

#4090 fix: Fix jobflow `status` confusion problem
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, size/L

#3901 take gpu-number into consideration
  pkg/scheduler/api/devices/nvidia/gpushare/device_info.go
Labels: approved, lgtm, ok-to-test, size/XS

#4097 Add more info when e2e failed
  test/e2e/util/job.go
Labels: approved, lgtm, ok-to-test, size/S, area/test

#4096 change to action cache v4
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_sequence.yaml
  .github/workflows/e2e_spark.yaml
  .github/workflows/e2e_vcctl.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/S

#4092 [fix] update feature flag for job support
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#4094 [cherry-pick] Fix jobflow `status` confusion problem
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, ok-to-test, size/L

#4095 [cherry-pick] Fix jobflow `status` confusion problem
  pkg/controllers/jobflow/jobflow_controller_action.go
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, size/L

#4087 Optimize append operations for better performance
  pkg/controllers/job/plugins/env/env.go
Labels: approved, lgtm, size/XS

#4088 [Refactor] controller cache deletePod logic,skip create
  pkg/controllers/cache/cache.go
Labels: approved, kind/cleanup, lgtm, size/S

#4103 [cherry-pick] fix panic when get job's elastic resource
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/test_utils.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, ok-to-test, size/L

#4077 CI: add dependabot
  .github/dependabot.yml
Labels: approved, size/M, area/deploy

#4113 update readme
  README.md
Labels: approved, lgtm, size/XS, retest-not-required-docs-only

#4121 fix flaky test
  pkg/controllers/jobflow/jobflow_controller_action_test.go
Labels: approved, lgtm, size/XS, area/test

#4120 Remove pod mutate webhook by default
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, size/M, area/performance

#4128 Remove podgroup mutating webhook by default
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup.go
  pkg/webhooks/admission/podgroups/mutate/mutate_podgroup_test.go
Labels: approved, lgtm, size/L, area/performance

#4119 fix: add hierarchy queue validation and update for enqueueable
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, kind/bug, lgtm, size/L, area/scheduling

#4132 Move queue state validate from pod to podgroup
  cmd/webhook-manager/main.go
  config/crd/volcano/bases/scheduling.volcano.sh_podgroups.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_podgroups.yaml
  installer/helm/chart/volcano/templates/webhooks.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-development.yaml
  pkg/webhooks/admission/podgroups/validate/validate_podgroup.go
  pkg/webhooks/admission/podgroups/validate/validate_podgroup_test.go
  pkg/webhooks/admission/pods/validate/admit_pod.go
  pkg/webhooks/admission/pods/validate/admit_pod_test.go
Labels: approved, lgtm, size/XL, area/performance

#4124 fix: remove hostpath mount in volcano-scheduler
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#4123 Enabled Cooldown Protection Plugin for reclaiming also
  pkg/scheduler/plugins/cdp/cdp.go
Labels: approved, lgtm, ok-to-test, size/S

#4136 chore: Change dependabot schedule interval to weekly
  .github/dependabot.yml
Labels: approved, lgtm, ok-to-test, size/XS

#4138 cleanup residual useless victims code in preempt action
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, kind/cleanup, lgtm, size/S

#4079 scheduler: consider the nominated node first when allocating Node for Pod
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, kind/feature, lgtm, size/S

#4142 fix: the problem that PVC will be continuously created indefinitely
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#4144 [cherry-pick] fix: the problem that PVC will be continuously created indefinitely
  pkg/controllers/job/job_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#4117 improve fail messages for pod scheduling in gang unschedulable scenario
  docs/design/scheduling-reason.md
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
Labels: approved, lgtm, ok-to-test, size/M

#4141 Replace queue status update by using ApplyStatus method
  config/crd/volcano/bases/scheduling.volcano.sh_queues.yaml
  go.mod
  go.sum
  installer/helm/chart/volcano/crd/bases/scheduling.volcano.sh_queues.yaml
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/controllers/queue/queue_controller_action.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, kind/bug, lgtm, size/M

#3937 feat: support scalar resources metric
  docs/design/metrics.md
  pkg/scheduler/metrics/queue.go
  pkg/scheduler/metrics/queue_test.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, ok-to-test, size/L
