Repository volcano-sh/volcano, pull requests merged in 2025-05, with the labels that each got.

#4205 Add fuzz tests for job controller
  go.mod
  go.sum
  hack/oss-fuzz-build.sh
  licenses/github.com/AdaLogics/go-fuzz-headers/LICENSE
  pkg/controllers/job/fuzz_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3894 Add network-topology-aware plugin and hyperNode score callback
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/network-topology-aware/network_topology_aware.go
  pkg/scheduler/plugins/network-topology-aware/network_topology_aware_test.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
  pkg/scheduler/util_test.go
Labels: approved, kind/feature, lgtm, area/scheduling, size/XXL

#4222 Optimize multiple 'if' statements in the code
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/defaults_test.go
Labels: approved, lgtm, size/L

#3946 in capacity plugin attr.deserved no need MinDimensionResource with attr.request
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, area/scheduling, size/XS

#4264 chore: change BuildPodWithPreeemptionPolicy -> BuildPodWithPreemptionPolicy
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, kind/cleanup, lgtm, size/XS

#4282 fix: scheduler leader elect namespace not take effect
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
Labels: approved, kind/bug, lgtm, size/XS

#4283 [Cherry-pick 1.11] fix: scheduler leader elect namespace not take effect
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
Labels: approved, kind/bug, lgtm, size/XS

#4284 [Cherry-pick 1.10]fix: scheduler leader elect namespace not take effect
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
Labels: approved, kind/bug, lgtm, size/S

#4280 Add error msg when check hierarchical queue fail
  pkg/scheduler/plugins/capacity/capacity.go
Labels: approved, kind/feature, lgtm, size/XS

#4273 Fix panic while queues' total guarantee exceed the total resource of the cluster in some situations.
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, lgtm, ok-to-test, size/XS

#4274 fix: add miss queue state check in allocatable action
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, kind/bug, lgtm, size/S

#4272 fix controller panic for mpi job
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
Labels: approved, kind/bug, lgtm, size/M

#4293 Check queue spec to ensure the rationality of resource size
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, kind/bug, lgtm, size/L

#4281 WORLD_SIZE calculation for PyTorch Jobs
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch_test.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/S

#4289 [Cherry-pick 1.11]fix controller panic for mpi job
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
Labels: approved, kind/bug, lgtm, size/M

#4287 [Cherry-pick 1.9]fix controller panic for mpi job
  pkg/controllers/job/plugins/distributed-framework/mpi/mpi.go
Labels: kind/bug, lgtm, size/M

#4266 Feature stale action
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: approved, lgtm, size/M

#4300 [ci] debug security score workflow artifact upload failure
  .github/workflows/scorecards.yml
Labels: approved, lgtm, size/XS

#4285 feat: add graceful shutdown server for webhook manager.
  cmd/webhook-manager/app/options/options.go
  cmd/webhook-manager/app/options/options_test.go
  cmd/webhook-manager/app/server.go
  pkg/webhooks/config/config.go
Labels: approved, kind/feature, lgtm, size/L

#4307 Prevent pod scheduling when reclaim
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim_test.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, kind/feature, lgtm, size/M

#4152 Refactor volume binding and add prebind implementation
  docs/design/prebind.md
  docs/design/volume-binding.md
  go.mod
  go.sum
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/helm/chart/volcano/values.yaml
  licenses/github.com/containerd/containerd/api/LICENSE
  licenses/github.com/containerd/errdefs/LICENSE
  licenses/github.com/containerd/log/LICENSE
  licenses/github.com/containerd/ttrpc/LICENSE
  licenses/github.com/docker/go-units/LICENSE
  licenses/github.com/euank/go-kmsg-parser/LICENSE
  licenses/github.com/gorilla/websocket/LICENSE
  licenses/github.com/karrick/godirwalk/LICENSE
  licenses/github.com/mistifyio/go-zfs/LICENSE
  licenses/github.com/moby/spdystream/LICENSE
  licenses/github.com/mxk/go-flowrate/LICENSE
  licenses/k8s.io/kubectl/LICENSE
  licenses/k8s.io/pod-security-admission/LICENSE
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/backfill/backfill_test.go
  pkg/scheduler/actions/enqueue/enqueue_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_mock.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/factory.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/capabilities/volumebinding/volume_binding.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/job_updater.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/helper.go
  pkg/scheduler/plugins/predicates/helper_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/proportion/proportion_test.go
  pkg/scheduler/plugins/util/nodescore/score_helper.go
  pkg/scheduler/uthelper/helper.go
  pkg/scheduler/util/test_utils.go
  test/e2e/schedulingbase/main_test.go
  test/e2e/schedulingbase/volume_binding.go
  test/e2e/util/statefulset.go
  test/e2e/util/util.go
Labels: approved, kind/feature, lgtm, area/scheduling, size/XXL

#4105 Fix: Incorrect conversion between integer types
  pkg/controllers/job/job_controller_handler.go
Labels: approved, lgtm, size/XS

#4047 Add resync-period flag for k8s native informers
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/scheduler.go
Labels: approved, kind/feature, lgtm, size/S

#4174 ✨ feat: add clusterrole for editor & viewer
  installer/helm/chart/volcano/templates/vcjob_editor_role.yaml
  installer/helm/chart/volcano/templates/vcjob_viewer_role.yaml
  installer/helm/chart/volcano/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4319 fix go mod and informer resync
  go.mod
  go.sum
  pkg/scheduler/cache/cache.go
Labels: approved, kind/bug, lgtm, size/S

#4290 Add vgpu dynamic mig
  pkg/scheduler/api/devices/config/config.go
  pkg/scheduler/api/devices/config/vgpu.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info.go
  pkg/scheduler/api/devices/nvidia/vgpu/device_info_test.go
  pkg/scheduler/api/devices/nvidia/vgpu/hamicore.go
  pkg/scheduler/api/devices/nvidia/vgpu/metrics.go
  pkg/scheduler/api/devices/nvidia/vgpu/mig.go
  pkg/scheduler/api/devices/nvidia/vgpu/mig_test.go
  pkg/scheduler/api/devices/nvidia/vgpu/sharing_factory.go
  pkg/scheduler/api/devices/nvidia/vgpu/type.go
  pkg/scheduler/api/devices/nvidia/vgpu/utils.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
  pkg/scheduler/plugins/deviceshare/deviceshare_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#4302 Add citation
  CITATION.cff
  README.md
Labels: approved, lgtm, size/M

#4321 Fix admission webhook with labelSelector for hyperNode
  pkg/webhooks/admission/hypernodes/validate/admit_hypernode.go
  pkg/webhooks/admission/hypernodes/validate/admit_hypernode_test.go
Labels: approved, lgtm, ok-to-test, size/M

#4325 Add NetworkTopology plugin score doc
  docs/design/Network Topology Aware Scheduling.md
Labels: approved, lgtm, size/S, retest-not-required-docs-only, kind/documentation

#4169 feat: Add jobflow metrics
  pkg/controllers/jobflow/state/metrics.go
  pkg/controllers/jobflow/state/pending.go
  pkg/controllers/jobflow/state/running.go
  pkg/controllers/util/const.go
Labels: approved, lgtm, size/M

#4330 Bump image to v1.12.0
  .github/workflows/code_verify.yaml
  .github/workflows/e2e_spark.yaml
  Makefile
  Makefile.def
  README.md
  go.mod
  go.sum
  hack/check-generated-yaml.sh
  hack/run-e2e-kind.sh
  installer/helm/chart/volcano/Chart.yaml
  installer/helm/chart/volcano/values.yaml
  installer/volcano-agent-development.yaml
  installer/volcano-development.yaml
  installer/volcano-monitoring-v1.12.0.yaml
Labels: approved, lgtm, size/M, area/deploy

#4336 Fix queue update conflicts when upgrading to new version
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
Labels: approved, kind/bug, lgtm, size/S
