Repository volcano-sh/volcano, pull requests merged in 2025-07, with the labels that each got.

#4365 Automated cherry pick of #4281: WORLD_SIZE calculation for PyTorch Jobs
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch.go
  pkg/controllers/job/plugins/distributed-framework/pytorch/pytorch_test.go
Labels: approved, lgtm, size/S

#4384 Only refresh podgroup to running when pods are scheduled
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, kind/bug, lgtm, size/M

#4428 Fix panic while `vcctl queue list` after podgroups' queue was deleted
  pkg/cli/queue/list.go
  pkg/cli/queue/queue_test.go
Labels: approved, kind/bug, lgtm, size/L

#4347 When some scalar resources are 0 in deserved, hierarychical queues validation can not pass
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, kind/bug, lgtm, size/M

#4422 Move kube-scheduler related metrics initilization to server.go to avoid panic
  cmd/scheduler/app/server.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/nodeorder/nodeorder_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, kind/bug, lgtm, size/L

#4440 Automated cherry pick of #4336: Fix queue update conflicts when upgrading to new version
  installer/helm/chart/volcano/templates/scheduler.yaml
  installer/volcano-development.yaml
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
Labels: approved, lgtm, size/S

#4409 Add support for skipping handler registration and QoS manager initialization based on configuration in Volcano Agent
  Makefile
  cmd/agent/app/agent.go
  pkg/agent/events/eventsmgr.go
  pkg/agent/healthcheck/healthcheck.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/M

#4443 Fix: Sync Jobflow status with vcjob Status Terminated
  pkg/controllers/jobflow/jobflow_controller_action_test.go
  pkg/controllers/jobflow/state/pending.go
Labels: approved, lgtm, size/M

#4464 Correct step order to enable caching in E2E workflows
  .github/workflows/e2e_dra.yml
  .github/workflows/e2e_parallel_jobs.yaml
  .github/workflows/e2e_scheduling_actions.yaml
  .github/workflows/e2e_scheduling_basic.yaml
  .github/workflows/e2e_vcctl.yaml
Labels: approved, lgtm, size/S

#4340 fix enable node device score plugin
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/plugins/deviceshare/deviceshare.go
Labels: approved, lgtm, ok-to-test, size/L

#4461 Automated cherry pick of #4422: Move kube-scheduler related metrics initilization to server.go to avoid panic
  cmd/scheduler/app/server.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/nodeorder/nodeorder_test.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/uthelper/helper.go
Labels: approved, lgtm, ok-to-test, size/L

#4445 Fix the issue where SelectBestNode returns nil when plugin scores are…
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, kind/bug, lgtm, size/S

#4470 [Cherry-pick master] Check queue spec to ensure the rationality of resource size
  pkg/webhooks/admission/queues/validate/validate_queue.go
  pkg/webhooks/admission/queues/validate/validate_queue_test.go
Labels: approved, kind/bug, lgtm, size/L

#4487 Add missing capacity metrics in hierarchical queues
  pkg/scheduler/plugins/capacity/capacity.go
Labels: approved, kind/bug, lgtm, size/XS

#4488 Automated cherry pick of #4473: fix node count reconcile
  installer/helm/chart/volcano/templates/controllers.yaml
  installer/volcano-development.yaml
  pkg/controllers/hypernode/hypernode_controller.go
  pkg/controllers/hypernode/hypernode_handler.go
  pkg/controllers/hypernode/hypernode_handler_test.go
  pkg/scheduler/api/hyper_node_info.go
  pkg/scheduler/api/hyper_node_info_test.go
Labels: approved, lgtm, size/L

#4490 [cherry-pick for 1.12]Fix incorrect definition of ReleaseNameEnvKey
  pkg/controllers/hypernode/config/loader.go
Labels: approved, kind/bug, lgtm, size/XS

#4354 Set root capability only when user not set it
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/capacity/capacity.go
  pkg/scheduler/plugins/capacity/capacity_test.go
Labels: approved, lgtm, ok-to-test, size/M

#4472 [cherry-pick for 1.12]Fix the issue where SelectBestNode returns nil when plugin scores are negative
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, lgtm, size/S
